# Proyecto Final - Conditional Imitation Learning - Equipo 19

Entrenamiento reproducible para los comandos **STRAIGHT (0)**,
**LEFT (1)** y **RIGHT (2)**. La division entrenamiento/validacion se
realiza antes del aumento para impedir fuga entre una imagen y su reflejo.

In [1]:
# Primera celda de codigo requerida por la actividad: clonar el dataset desde GitHub.
import os, sys
from pathlib import Path

IN_COLAB = "google.colab" in sys.modules
REPO_URL = "https://github.com/xak47d/proyecto-final-cil-equipo19.git"
if IN_COLAB:
    PROJECT_ROOT = Path("/content/proyecto-final-cil-equipo19")
    if not PROJECT_ROOT.exists():
        !git clone https://github.com/xak47d/proyecto-final-cil-equipo19.git /content/proyecto-final-cil-equipo19
    !pip install -q -r /content/proyecto-final-cil-equipo19/requirements_colab.txt
else:
    PROJECT_ROOT = Path.cwd()

print("Proyecto:", PROJECT_ROOT)

Proyecto: /content/proyecto-final-cil-equipo19

## 1. Configuracion reproducible

Se fijan semillas y se centralizan dimensiones, lote y rutas. El
preprocesamiento se replica exactamente en el controlador de Webots.

In [2]:
import json, math, random, shutil
from collections import Counter
from pathlib import Path

import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.layers import Input, Conv2D, Dense, Flatten, Dropout, Concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import Sequence, to_categorical

SEED = 19
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

IMG_H, IMG_W = 80, 160
BATCH_SIZE = 32
EPOCHS = 12
COMMANDS = {0: "STRAIGHT", 1: "LEFT", 2: "RIGHT"}

RAW_DIR = PROJECT_ROOT / "dataset"
RAW_IMAGES = RAW_DIR / "images"
RAW_CSV = RAW_DIR / "driving_log.csv"
AUG_DIR = PROJECT_ROOT / "dataset_augmented"
AUG_IMAGES = AUG_DIR / "images"
AUG_CSV = AUG_DIR / "driving_log_augmented.csv"
FIGURES = PROJECT_ROOT / "docs" / "figures"
MODEL_DIR = PROJECT_ROOT / "controllers" / "cil_autonomous_driver"
FIGURES.mkdir(parents=True, exist_ok=True)
MODEL_DIR.mkdir(parents=True, exist_ok=True)

## 2. Auditoria del dataset original

Se valida el esquema, los tres comandos permitidos y la correspondencia
uno-a-uno entre registros e imagenes antes de entrenar.

In [3]:
raw_df = pd.read_csv(RAW_CSV)
assert list(raw_df.columns) == ["image", "steering_angle", "command"]
assert set(raw_df["command"].unique()) == set(COMMANDS)
assert raw_df["image"].is_unique
missing = [name for name in raw_df["image"] if not (RAW_IMAGES / name).exists()]
assert not missing, f"Imagenes faltantes: {missing[:5]}"

raw_df["source_id"] = raw_df["image"].map(lambda name: Path(name).stem)
print("Registros originales:", len(raw_df))
print(raw_df["command"].map(COMMANDS).value_counts())
display(raw_df.head())

counts = raw_df["command"].map(COMMANDS).value_counts().reindex(COMMANDS.values())
ax = counts.plot(kind="bar", color=["#2E74B5", "#70AD47", "#ED7D31"])
ax.set_title("Distribucion original por comando")
ax.set_ylabel("Imagenes")
ax.set_xlabel("")
plt.tight_layout()
plt.savefig(FIGURES / "command_distribution_original.png", dpi=180)
plt.show()

Registros originales: 6129
command
RIGHT       3032
LEFT        1895
STRAIGHT    1202
Name: count, dtype: int64

                image  steering_angle  command       source_id
0  img_1782317332.png             0.0        0  img_1782317332
1  img_1782317333.png             0.0        0  img_1782317333
2  img_1782317334.png             0.0        0  img_1782317334
3  img_1782317335.png             0.0        0  img_1782317335
4  img_1782317336.png             0.0        0  img_1782317336

/var/folders/50/pzhcqw5j5212_pw_y99p2ky80000gn/T/ipykernel_87500/1690021843.py:20: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 3. Division por fuente y aumento

La division estratificada ocurre sobre las imagenes originales. Solo
despues se crean reflejos; LEFT y RIGHT se intercambian al reflejar.
Para equilibrar STRAIGHT se agregan dos variantes de brillo.

In [4]:
train_raw, val_raw = train_test_split(
    raw_df,
    test_size=0.20,
    random_state=SEED,
    stratify=raw_df["command"],
)
train_sources = set(train_raw["source_id"])
val_sources = set(val_raw["source_id"])
assert train_sources.isdisjoint(val_sources)

expected_signature = {
    "seed": SEED,
    "raw_records": len(raw_df),
    "train_sources": len(train_raw),
    "validation_sources": len(val_raw),
    "commands": COMMANDS,
}
signature_path = AUG_DIR / "augmentation_signature.json"
rebuild = True
if signature_path.exists() and AUG_CSV.exists():
    rebuild = json.loads(signature_path.read_text()) != expected_signature

if rebuild:
    if AUG_DIR.exists():
        shutil.rmtree(AUG_DIR)
    AUG_IMAGES.mkdir(parents=True, exist_ok=True)
    augmented_rows = []

    def save_variant(row, split, variant, image, steering, command):
        output_name = f"{split}_{variant}_{row.image}"
        ok = cv2.imwrite(str(AUG_IMAGES / output_name), image)
        if not ok:
            raise IOError(f"No se pudo escribir {output_name}")
        augmented_rows.append({
            "image": output_name,
            "steering_angle": float(steering),
            "command": int(command),
            "source_id": row.source_id,
            "split": split,
            "variant": variant,
        })

    for row in train_raw.itertuples(index=False):
        image = cv2.imread(str(RAW_IMAGES / row.image))
        save_variant(row, "train", "original", image, row.steering_angle, row.command)
        flipped_command = 2 if row.command == 1 else 1 if row.command == 2 else 0
        save_variant(row, "train", "flip", cv2.flip(image, 1), -row.steering_angle, flipped_command)
        if row.command == 0:
            darker = cv2.convertScaleAbs(image, alpha=0.75, beta=0)
            brighter_flip = cv2.convertScaleAbs(cv2.flip(image, 1), alpha=1.20, beta=0)
            save_variant(row, "train", "dark", darker, row.steering_angle, 0)
            save_variant(row, "train", "bright_flip", brighter_flip, -row.steering_angle, 0)

    for row in val_raw.itertuples(index=False):
        image = cv2.imread(str(RAW_IMAGES / row.image))
        save_variant(row, "validation", "original", image, row.steering_angle, row.command)

    augmented_df = pd.DataFrame(augmented_rows)
    AUG_DIR.mkdir(parents=True, exist_ok=True)
    augmented_df.to_csv(AUG_CSV, index=False)
    signature_path.write_text(json.dumps(expected_signature, indent=2))
else:
    augmented_df = pd.read_csv(AUG_CSV)

train_df = augmented_df.query("split == 'train'").reset_index(drop=True)
val_df = augmented_df.query("split == 'validation'").reset_index(drop=True)
assert set(train_df.source_id).isdisjoint(set(val_df.source_id))
assert len(augmented_df) > 10_000
print("Muestras finales:", len(augmented_df))
print("Entrenamiento:", len(train_df), "Validacion:", len(val_df))
print(train_df["command"].map(COMMANDS).value_counts())

Muestras finales: 12956
Entrenamiento: 11730 Validacion: 1226
command
LEFT        3941
RIGHT       3941
STRAIGHT    3848
Name: count, dtype: int64

## 4. Generador y preprocesamiento

La camara se recorta 25% desde arriba para reducir cielo/edificios,
cambia a RGB, redimensiona a 160x80 y normaliza a [0, 1].

In [5]:
def preprocess_image(path):
    image = cv2.imread(str(path))
    if image is None:
        raise FileNotFoundError(path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = image[int(image.shape[0] * 0.25):, :, :]
    image = cv2.resize(image, (IMG_W, IMG_H), interpolation=cv2.INTER_AREA)
    return image.astype(np.float32) / 255.0

class CILSequence(Sequence):
    def __init__(self, dataframe, shuffle=True, **kwargs):
        super().__init__(**kwargs)
        self.df = dataframe.reset_index(drop=True)
        self.shuffle = shuffle
        self.indexes = np.arange(len(self.df))
        self.on_epoch_end()

    def __len__(self):
        return int(np.ceil(len(self.df) / BATCH_SIZE))

    def __getitem__(self, index):
        ids = self.indexes[index * BATCH_SIZE:(index + 1) * BATCH_SIZE]
        batch = self.df.iloc[ids]
        images = np.stack([preprocess_image(AUG_IMAGES / name) for name in batch.image])
        commands = to_categorical(batch.command.astype(int), num_classes=3)
        steering = batch.steering_angle.to_numpy(dtype=np.float32)
        return (images, commands), steering

    def on_epoch_end(self):
        if self.shuffle:
            np.random.shuffle(self.indexes)

train_gen = CILSequence(train_df, shuffle=True)
val_gen = CILSequence(val_df, shuffle=False)
sample_inputs, sample_targets = train_gen[0]
print(sample_inputs[0].shape, sample_inputs[1].shape, sample_targets.shape)

(32, 80, 160, 3) (32, 3) (32,)

## 5. CNN condicionada

La rama visual comparte cinco capas convolucionales. El comando one-hot
se concatena antes de las capas densas para condicionar el angulo.

In [6]:
image_input = Input(shape=(IMG_H, IMG_W, 3), name="image_input")
x = Conv2D(24, 5, strides=2, activation="relu")(image_input)
x = Conv2D(36, 5, strides=2, activation="relu")(x)
x = Conv2D(48, 5, strides=2, activation="relu")(x)
x = Conv2D(64, 3, activation="relu")(x)
x = Conv2D(64, 3, activation="relu")(x)
x = Flatten()(x)

command_input = Input(shape=(3,), name="command_input")
x = Concatenate()([x, command_input])
x = Dense(100, activation="relu")(x)
x = Dropout(0.30)(x)
x = Dense(50, activation="relu")(x)
x = Dense(10, activation="relu")(x)
steering_output = Dense(1, name="steering_output")(x)

model = Model([image_input, command_input], steering_output, name="CIL_Equipo19")
model.compile(optimizer=Adam(1e-4), loss="mse", metrics=["mae"])
model.summary()

Model: "CIL_Equipo19"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ image_input         │ (None, 80, 160,   │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d (Conv2D)     │ (None, 38, 78,    │      1,824 │ image_input[0][0] │
│                     │ 24)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_1 (Conv2D)   │ (None, 17, 37,    │     21,636 │ conv2d[0][0]      │
│                     │ 36)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_2 (Conv2D)   │ (None, 7, 17, 48) │     43,248 │ conv2d_1[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_3 (Conv2D)   │ (None, 5, 15, 64) │     27,712 │ conv2d_2[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_4 (Conv2D)   │ (None, 3, 13, 64) │     36,928 │ conv2d_3[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten (Flatten)   │ (None, 2496)      │          0 │ conv2d_4[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ command_input       │ (None, 3)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 2499)      │          0 │ flatten[0][0],    │
│ (Concatenate)       │                   │            │ command_input[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 100)       │    250,000 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 100)       │          0 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 50)        │      5,050 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 10)        │        510 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ steering_output     │ (None, 1)         │         11 │ dense_2[0][0]     │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 386,919 (1.48 MB)

 Trainable params: 386,919 (1.48 MB)

 Non-trainable params: 0 (0.00 B)

## 6. Entrenamiento con callbacks

In [7]:
checkpoint = MODEL_DIR / "cil_model_best.h5"
callbacks = [
    EarlyStopping(monitor="val_mae", patience=3, restore_best_weights=True, mode="min"),
    ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2, min_lr=1e-6),
    ModelCheckpoint(checkpoint, monitor="val_mae", save_best_only=True, mode="min"),
]
history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=EPOCHS,
    callbacks=callbacks,
    verbose=1,
)

Epoch 1/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 5:43 940ms/step - loss: 0.0069 - mae: 0.0612

  3/367 ━━━━━━━━━━━━━━━━━━━━ 18s 51ms/step - loss: 0.0082 - mae: 0.0607

  4/367 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - loss: 0.0084 - mae: 0.0625

  5/367 ━━━━━━━━━━━━━━━━━━━━ 20s 57ms/step - loss: 0.0081 - mae: 0.0620

  6/367 ━━━━━━━━━━━━━━━━━━━━ 20s 56ms/step - loss: 0.0081 - mae: 0.0621

  7/367 ━━━━━━━━━━━━━━━━━━━━ 20s 56ms/step - loss: 0.0081 - mae: 0.0626

  8/367 ━━━━━━━━━━━━━━━━━━━━ 20s 56ms/step - loss: 0.0076 - mae: 0.0604

  9/367 ━━━━━━━━━━━━━━━━━━━━ 20s 56ms/step - loss: 0.0074 - mae: 0.0596

 10/367 ━━━━━━━━━━━━━━━━━━━━ 19s 56ms/step - loss: 0.0071 - mae: 0.0579

 11/367 ━━━━━━━━━━━━━━━━━━━━ 19s 56ms/step - loss: 0.0070 - mae: 0.0573

 12/367 ━━━━━━━━━━━━━━━━━━━━ 19s 56ms/step - loss: 0.0067 - mae: 0.0559

 14/367 ━━━━━━━━━━━━━━━━━━━━ 19s 56ms/step - loss: 0.0067 - mae: 0.0557

 15/367 ━━━━━━━━━━━━━━━━━━━━ 19s 56ms/step - loss: 0.0072 - mae: 0.0574

 16/367 ━━━━━━━━━━━━━━━━━━━━ 19s 56ms/step - loss: 0.0072 - mae: 0.0573

 17/367 ━━━━━━━━━━━━━━━━━━━━ 19s 55ms/step - loss: 0.0072 - mae: 0.0569

 18/367 ━━━━━━━━━━━━━━━━━━━━ 19s 55ms/step - loss: 0.0070 - mae: 0.0563

 19/367 ━━━━━━━━━━━━━━━━━━━━ 19s 55ms/step - loss: 0.0069 - mae: 0.0555

 20/367 ━━━━━━━━━━━━━━━━━━━━ 19s 55ms/step - loss: 0.0071 - mae: 0.0565

 21/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0070 - mae: 0.0562

 22/367 ━━━━━━━━━━━━━━━━━━━━ 19s 55ms/step - loss: 0.0071 - mae: 0.0564

 23/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0070 - mae: 0.0559

 24/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0070 - mae: 0.0561

 25/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0071 - mae: 0.0561

 26/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0070 - mae: 0.0558

 27/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0070 - mae: 0.0560

 28/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0070 - mae: 0.0557

 29/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0070 - mae: 0.0556

 30/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0071 - mae: 0.0561

 31/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0070 - mae: 0.0555

 32/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0069 - mae: 0.0552

 33/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0069 - mae: 0.0553

 34/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0070 - mae: 0.0558

 35/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0071 - mae: 0.0559

 36/367 ━━━━━━━━━━━━━━━━━━━━ 18s 55ms/step - loss: 0.0070 - mae: 0.0555

 37/367 ━━━━━━━━━━━━━━━━━━━━ 18s 57ms/step - loss: 0.0071 - mae: 0.0558

 38/367 ━━━━━━━━━━━━━━━━━━━━ 18s 57ms/step - loss: 0.0071 - mae: 0.0555

 40/367 ━━━━━━━━━━━━━━━━━━━━ 18s 56ms/step - loss: 0.0068 - mae: 0.0545

 41/367 ━━━━━━━━━━━━━━━━━━━━ 18s 56ms/step - loss: 0.0068 - mae: 0.0546

 42/367 ━━━━━━━━━━━━━━━━━━━━ 18s 56ms/step - loss: 0.0067 - mae: 0.0541

 43/367 ━━━━━━━━━━━━━━━━━━━━ 18s 56ms/step - loss: 0.0067 - mae: 0.0540

 44/367 ━━━━━━━━━━━━━━━━━━━━ 18s 56ms/step - loss: 0.0067 - mae: 0.0537

 45/367 ━━━━━━━━━━━━━━━━━━━━ 18s 57ms/step - loss: 0.0066 - mae: 0.0535

 46/367 ━━━━━━━━━━━━━━━━━━━━ 18s 57ms/step - loss: 0.0066 - mae: 0.0536

 47/367 ━━━━━━━━━━━━━━━━━━━━ 18s 57ms/step - loss: 0.0066 - mae: 0.0536

 48/367 ━━━━━━━━━━━━━━━━━━━━ 18s 57ms/step - loss: 0.0066 - mae: 0.0535

 49/367 ━━━━━━━━━━━━━━━━━━━━ 18s 57ms/step - loss: 0.0066 - mae: 0.0536

 50/367 ━━━━━━━━━━━━━━━━━━━━ 18s 57ms/step - loss: 0.0066 - mae: 0.0535

 51/367 ━━━━━━━━━━━━━━━━━━━━ 18s 57ms/step - loss: 0.0066 - mae: 0.0537

 52/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0065 - mae: 0.0533

 53/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0065 - mae: 0.0535

 54/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0065 - mae: 0.0535

 55/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0065 - mae: 0.0532

 56/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0065 - mae: 0.0533

 57/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0064 - mae: 0.0531

 58/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0065 - mae: 0.0534

 59/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0065 - mae: 0.0534

 60/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0065 - mae: 0.0535

 61/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0065 - mae: 0.0535

 62/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0066 - mae: 0.0539

 63/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0066 - mae: 0.0539

 64/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0066 - mae: 0.0541

 65/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0067 - mae: 0.0542

 66/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0067 - mae: 0.0544

 67/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0067 - mae: 0.0544

 68/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0067 - mae: 0.0544

 69/367 ━━━━━━━━━━━━━━━━━━━━ 17s 57ms/step - loss: 0.0067 - mae: 0.0544

 70/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0067 - mae: 0.0545

 71/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0067 - mae: 0.0544

 72/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0067 - mae: 0.0545

 73/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0067 - mae: 0.0543

 74/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0067 - mae: 0.0543

 75/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0067 - mae: 0.0543

 76/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0066 - mae: 0.0543

 77/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0066 - mae: 0.0542

 78/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0066 - mae: 0.0541

 79/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0066 - mae: 0.0541

 80/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0067 - mae: 0.0543

 81/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0067 - mae: 0.0544

 82/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0067 - mae: 0.0546

 83/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0068 - mae: 0.0546

 85/367 ━━━━━━━━━━━━━━━━━━━━ 16s 57ms/step - loss: 0.0067 - mae: 0.0546

 86/367 ━━━━━━━━━━━━━━━━━━━━ 16s 58ms/step - loss: 0.0068 - mae: 0.0546

 87/367 ━━━━━━━━━━━━━━━━━━━━ 16s 58ms/step - loss: 0.0068 - mae: 0.0547

 88/367 ━━━━━━━━━━━━━━━━━━━━ 16s 58ms/step - loss: 0.0068 - mae: 0.0547

 89/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0068 - mae: 0.0548

 91/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0068 - mae: 0.0549

 92/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0068 - mae: 0.0549

 93/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0068 - mae: 0.0550

 94/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0552

 95/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0553

 96/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0551

 97/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0551

 98/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0550

 99/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0551

100/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0552

101/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0552

102/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0553

103/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0070 - mae: 0.0554

104/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0070 - mae: 0.0555

105/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0553

106/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0552

107/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0553

108/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0070 - mae: 0.0554

109/367 ━━━━━━━━━━━━━━━━━━━━ 15s 58ms/step - loss: 0.0069 - mae: 0.0555

110/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0070 - mae: 0.0556

111/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0070 - mae: 0.0557

112/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0070 - mae: 0.0556

113/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0070 - mae: 0.0558

114/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0070 - mae: 0.0557

115/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0070 - mae: 0.0556

117/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0070 - mae: 0.0555

118/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0070 - mae: 0.0557

119/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0071 - mae: 0.0559

120/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0071 - mae: 0.0559

121/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0071 - mae: 0.0559

122/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0071 - mae: 0.0558

124/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0071 - mae: 0.0559

125/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0071 - mae: 0.0559

126/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0071 - mae: 0.0559

127/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0072 - mae: 0.0561

129/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0071 - mae: 0.0560

131/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0071 - mae: 0.0562

132/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0071 - mae: 0.0561

133/367 ━━━━━━━━━━━━━━━━━━━━ 13s 59ms/step - loss: 0.0071 - mae: 0.0561

134/367 ━━━━━━━━━━━━━━━━━━━━ 13s 59ms/step - loss: 0.0071 - mae: 0.0560

135/367 ━━━━━━━━━━━━━━━━━━━━ 13s 60ms/step - loss: 0.0071 - mae: 0.0560

136/367 ━━━━━━━━━━━━━━━━━━━━ 14s 61ms/step - loss: 0.0071 - mae: 0.0559

137/367 ━━━━━━━━━━━━━━━━━━━━ 14s 62ms/step - loss: 0.0070 - mae: 0.0558

138/367 ━━━━━━━━━━━━━━━━━━━━ 14s 62ms/step - loss: 0.0070 - mae: 0.0558

139/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0070 - mae: 0.0557

140/367 ━━━━━━━━━━━━━━━━━━━━ 14s 64ms/step - loss: 0.0070 - mae: 0.0556

141/367 ━━━━━━━━━━━━━━━━━━━━ 14s 65ms/step - loss: 0.0070 - mae: 0.0556

142/367 ━━━━━━━━━━━━━━━━━━━━ 14s 66ms/step - loss: 0.0070 - mae: 0.0556

143/367 ━━━━━━━━━━━━━━━━━━━━ 14s 66ms/step - loss: 0.0070 - mae: 0.0558

144/367 ━━━━━━━━━━━━━━━━━━━━ 14s 67ms/step - loss: 0.0071 - mae: 0.0559

145/367 ━━━━━━━━━━━━━━━━━━━━ 15s 68ms/step - loss: 0.0071 - mae: 0.0559

146/367 ━━━━━━━━━━━━━━━━━━━━ 15s 69ms/step - loss: 0.0071 - mae: 0.0559

147/367 ━━━━━━━━━━━━━━━━━━━━ 15s 70ms/step - loss: 0.0071 - mae: 0.0559

148/367 ━━━━━━━━━━━━━━━━━━━━ 15s 71ms/step - loss: 0.0071 - mae: 0.0560

149/367 ━━━━━━━━━━━━━━━━━━━━ 15s 71ms/step - loss: 0.0070 - mae: 0.0559

150/367 ━━━━━━━━━━━━━━━━━━━━ 15s 71ms/step - loss: 0.0070 - mae: 0.0557

151/367 ━━━━━━━━━━━━━━━━━━━━ 15s 71ms/step - loss: 0.0070 - mae: 0.0556

152/367 ━━━━━━━━━━━━━━━━━━━━ 15s 71ms/step - loss: 0.0070 - mae: 0.0556

153/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0070 - mae: 0.0555

154/367 ━━━━━━━━━━━━━━━━━━━━ 15s 73ms/step - loss: 0.0070 - mae: 0.0556

155/367 ━━━━━━━━━━━━━━━━━━━━ 15s 73ms/step - loss: 0.0070 - mae: 0.0557

156/367 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - loss: 0.0070 - mae: 0.0556

157/367 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - loss: 0.0070 - mae: 0.0556

158/367 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - loss: 0.0070 - mae: 0.0557

159/367 ━━━━━━━━━━━━━━━━━━━━ 15s 74ms/step - loss: 0.0070 - mae: 0.0557

160/367 ━━━━━━━━━━━━━━━━━━━━ 15s 73ms/step - loss: 0.0070 - mae: 0.0557

161/367 ━━━━━━━━━━━━━━━━━━━━ 15s 73ms/step - loss: 0.0070 - mae: 0.0557

162/367 ━━━━━━━━━━━━━━━━━━━━ 15s 73ms/step - loss: 0.0070 - mae: 0.0555

163/367 ━━━━━━━━━━━━━━━━━━━━ 14s 73ms/step - loss: 0.0070 - mae: 0.0555

164/367 ━━━━━━━━━━━━━━━━━━━━ 14s 73ms/step - loss: 0.0070 - mae: 0.0555

165/367 ━━━━━━━━━━━━━━━━━━━━ 14s 73ms/step - loss: 0.0070 - mae: 0.0555

166/367 ━━━━━━━━━━━━━━━━━━━━ 14s 73ms/step - loss: 0.0070 - mae: 0.0554

167/367 ━━━━━━━━━━━━━━━━━━━━ 14s 73ms/step - loss: 0.0069 - mae: 0.0554

168/367 ━━━━━━━━━━━━━━━━━━━━ 14s 73ms/step - loss: 0.0069 - mae: 0.0554

169/367 ━━━━━━━━━━━━━━━━━━━━ 14s 72ms/step - loss: 0.0069 - mae: 0.0553

170/367 ━━━━━━━━━━━━━━━━━━━━ 14s 72ms/step - loss: 0.0070 - mae: 0.0554

171/367 ━━━━━━━━━━━━━━━━━━━━ 14s 72ms/step - loss: 0.0070 - mae: 0.0554

172/367 ━━━━━━━━━━━━━━━━━━━━ 14s 72ms/step - loss: 0.0070 - mae: 0.0554

173/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0070 - mae: 0.0555

174/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0070 - mae: 0.0555

176/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0070 - mae: 0.0554

177/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0070 - mae: 0.0554

178/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0070 - mae: 0.0554

179/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0070 - mae: 0.0554

180/367 ━━━━━━━━━━━━━━━━━━━━ 13s 71ms/step - loss: 0.0070 - mae: 0.0554

181/367 ━━━━━━━━━━━━━━━━━━━━ 13s 71ms/step - loss: 0.0070 - mae: 0.0553

182/367 ━━━━━━━━━━━━━━━━━━━━ 13s 71ms/step - loss: 0.0069 - mae: 0.0552

183/367 ━━━━━━━━━━━━━━━━━━━━ 13s 71ms/step - loss: 0.0070 - mae: 0.0552

184/367 ━━━━━━━━━━━━━━━━━━━━ 13s 71ms/step - loss: 0.0070 - mae: 0.0552

185/367 ━━━━━━━━━━━━━━━━━━━━ 12s 71ms/step - loss: 0.0069 - mae: 0.0552

186/367 ━━━━━━━━━━━━━━━━━━━━ 12s 71ms/step - loss: 0.0070 - mae: 0.0552

187/367 ━━━━━━━━━━━━━━━━━━━━ 12s 71ms/step - loss: 0.0069 - mae: 0.0552

189/367 ━━━━━━━━━━━━━━━━━━━━ 12s 71ms/step - loss: 0.0069 - mae: 0.0552

190/367 ━━━━━━━━━━━━━━━━━━━━ 12s 71ms/step - loss: 0.0069 - mae: 0.0552

191/367 ━━━━━━━━━━━━━━━━━━━━ 12s 70ms/step - loss: 0.0069 - mae: 0.0552

192/367 ━━━━━━━━━━━━━━━━━━━━ 12s 70ms/step - loss: 0.0069 - mae: 0.0552

193/367 ━━━━━━━━━━━━━━━━━━━━ 12s 70ms/step - loss: 0.0069 - mae: 0.0551

194/367 ━━━━━━━━━━━━━━━━━━━━ 12s 70ms/step - loss: 0.0069 - mae: 0.0551

195/367 ━━━━━━━━━━━━━━━━━━━━ 12s 70ms/step - loss: 0.0069 - mae: 0.0552

196/367 ━━━━━━━━━━━━━━━━━━━━ 11s 70ms/step - loss: 0.0069 - mae: 0.0552

198/367 ━━━━━━━━━━━━━━━━━━━━ 11s 70ms/step - loss: 0.0069 - mae: 0.0553

199/367 ━━━━━━━━━━━━━━━━━━━━ 11s 70ms/step - loss: 0.0069 - mae: 0.0552

200/367 ━━━━━━━━━━━━━━━━━━━━ 11s 70ms/step - loss: 0.0069 - mae: 0.0551

201/367 ━━━━━━━━━━━━━━━━━━━━ 11s 70ms/step - loss: 0.0069 - mae: 0.0552

202/367 ━━━━━━━━━━━━━━━━━━━━ 11s 70ms/step - loss: 0.0069 - mae: 0.0552

204/367 ━━━━━━━━━━━━━━━━━━━━ 11s 70ms/step - loss: 0.0069 - mae: 0.0551

205/367 ━━━━━━━━━━━━━━━━━━━━ 11s 69ms/step - loss: 0.0069 - mae: 0.0551

206/367 ━━━━━━━━━━━━━━━━━━━━ 11s 69ms/step - loss: 0.0069 - mae: 0.0550

207/367 ━━━━━━━━━━━━━━━━━━━━ 11s 69ms/step - loss: 0.0069 - mae: 0.0550

208/367 ━━━━━━━━━━━━━━━━━━━━ 11s 69ms/step - loss: 0.0069 - mae: 0.0550

209/367 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - loss: 0.0069 - mae: 0.0550

210/367 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - loss: 0.0069 - mae: 0.0550

211/367 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - loss: 0.0069 - mae: 0.0551

212/367 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - loss: 0.0069 - mae: 0.0551

214/367 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - loss: 0.0069 - mae: 0.0552

215/367 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - loss: 0.0069 - mae: 0.0551

216/367 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - loss: 0.0069 - mae: 0.0550

217/367 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - loss: 0.0069 - mae: 0.0550

218/367 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - loss: 0.0069 - mae: 0.0551

219/367 ━━━━━━━━━━━━━━━━━━━━ 10s 69ms/step - loss: 0.0069 - mae: 0.0551

221/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0069 - mae: 0.0550

222/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0069 - mae: 0.0549

223/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0069 - mae: 0.0549

224/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0069 - mae: 0.0549

225/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0069 - mae: 0.0549

227/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0069 - mae: 0.0548

228/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0068 - mae: 0.0547

229/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0068 - mae: 0.0547

230/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0069 - mae: 0.0548

231/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0069 - mae: 0.0548

232/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0069 - mae: 0.0548

233/367 ━━━━━━━━━━━━━━━━━━━━ 9s 68ms/step - loss: 0.0069 - mae: 0.0548

234/367 ━━━━━━━━━━━━━━━━━━━━ 8s 68ms/step - loss: 0.0069 - mae: 0.0547

236/367 ━━━━━━━━━━━━━━━━━━━━ 8s 67ms/step - loss: 0.0069 - mae: 0.0547

238/367 ━━━━━━━━━━━━━━━━━━━━ 8s 67ms/step - loss: 0.0069 - mae: 0.0546

239/367 ━━━━━━━━━━━━━━━━━━━━ 8s 67ms/step - loss: 0.0069 - mae: 0.0546

241/367 ━━━━━━━━━━━━━━━━━━━━ 8s 67ms/step - loss: 0.0068 - mae: 0.0545

243/367 ━━━━━━━━━━━━━━━━━━━━ 8s 67ms/step - loss: 0.0068 - mae: 0.0545

244/367 ━━━━━━━━━━━━━━━━━━━━ 8s 67ms/step - loss: 0.0068 - mae: 0.0544

246/367 ━━━━━━━━━━━━━━━━━━━━ 8s 67ms/step - loss: 0.0068 - mae: 0.0545

247/367 ━━━━━━━━━━━━━━━━━━━━ 8s 67ms/step - loss: 0.0068 - mae: 0.0544

248/367 ━━━━━━━━━━━━━━━━━━━━ 7s 67ms/step - loss: 0.0068 - mae: 0.0544

249/367 ━━━━━━━━━━━━━━━━━━━━ 7s 67ms/step - loss: 0.0068 - mae: 0.0544

250/367 ━━━━━━━━━━━━━━━━━━━━ 7s 67ms/step - loss: 0.0068 - mae: 0.0545

251/367 ━━━━━━━━━━━━━━━━━━━━ 7s 67ms/step - loss: 0.0068 - mae: 0.0545

252/367 ━━━━━━━━━━━━━━━━━━━━ 7s 67ms/step - loss: 0.0068 - mae: 0.0545

253/367 ━━━━━━━━━━━━━━━━━━━━ 7s 67ms/step - loss: 0.0068 - mae: 0.0545

254/367 ━━━━━━━━━━━━━━━━━━━━ 7s 67ms/step - loss: 0.0068 - mae: 0.0544

255/367 ━━━━━━━━━━━━━━━━━━━━ 7s 67ms/step - loss: 0.0068 - mae: 0.0544

256/367 ━━━━━━━━━━━━━━━━━━━━ 7s 66ms/step - loss: 0.0068 - mae: 0.0544

257/367 ━━━━━━━━━━━━━━━━━━━━ 7s 66ms/step - loss: 0.0068 - mae: 0.0544

258/367 ━━━━━━━━━━━━━━━━━━━━ 7s 66ms/step - loss: 0.0068 - mae: 0.0544

259/367 ━━━━━━━━━━━━━━━━━━━━ 7s 66ms/step - loss: 0.0068 - mae: 0.0544

260/367 ━━━━━━━━━━━━━━━━━━━━ 7s 66ms/step - loss: 0.0068 - mae: 0.0543

261/367 ━━━━━━━━━━━━━━━━━━━━ 7s 66ms/step - loss: 0.0068 - mae: 0.0544

262/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0544

263/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0544

264/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0544

266/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0543

267/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0543

268/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0543

269/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0543

270/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0543

271/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0543

272/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0543

273/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0543

274/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0543

275/367 ━━━━━━━━━━━━━━━━━━━━ 6s 66ms/step - loss: 0.0068 - mae: 0.0543

276/367 ━━━━━━━━━━━━━━━━━━━━ 5s 66ms/step - loss: 0.0068 - mae: 0.0543

277/367 ━━━━━━━━━━━━━━━━━━━━ 5s 66ms/step - loss: 0.0068 - mae: 0.0543

278/367 ━━━━━━━━━━━━━━━━━━━━ 5s 66ms/step - loss: 0.0068 - mae: 0.0543

279/367 ━━━━━━━━━━━━━━━━━━━━ 5s 66ms/step - loss: 0.0068 - mae: 0.0543

280/367 ━━━━━━━━━━━━━━━━━━━━ 5s 66ms/step - loss: 0.0068 - mae: 0.0543

281/367 ━━━━━━━━━━━━━━━━━━━━ 5s 66ms/step - loss: 0.0068 - mae: 0.0543

282/367 ━━━━━━━━━━━━━━━━━━━━ 5s 66ms/step - loss: 0.0068 - mae: 0.0542

283/367 ━━━━━━━━━━━━━━━━━━━━ 5s 66ms/step - loss: 0.0068 - mae: 0.0542

284/367 ━━━━━━━━━━━━━━━━━━━━ 5s 65ms/step - loss: 0.0068 - mae: 0.0542

285/367 ━━━━━━━━━━━━━━━━━━━━ 5s 65ms/step - loss: 0.0068 - mae: 0.0542

286/367 ━━━━━━━━━━━━━━━━━━━━ 5s 65ms/step - loss: 0.0068 - mae: 0.0542

287/367 ━━━━━━━━━━━━━━━━━━━━ 5s 65ms/step - loss: 0.0068 - mae: 0.0542

289/367 ━━━━━━━━━━━━━━━━━━━━ 5s 65ms/step - loss: 0.0068 - mae: 0.0542

290/367 ━━━━━━━━━━━━━━━━━━━━ 5s 65ms/step - loss: 0.0068 - mae: 0.0542

291/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0541

292/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0542

293/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0541

294/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0541

295/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0541

296/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0542

297/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0542

298/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0542

299/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0541

300/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0540

301/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0540

302/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0068 - mae: 0.0541

303/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0067 - mae: 0.0541

304/367 ━━━━━━━━━━━━━━━━━━━━ 4s 65ms/step - loss: 0.0067 - mae: 0.0540

306/367 ━━━━━━━━━━━━━━━━━━━━ 3s 65ms/step - loss: 0.0067 - mae: 0.0540

307/367 ━━━━━━━━━━━━━━━━━━━━ 3s 65ms/step - loss: 0.0067 - mae: 0.0540

308/367 ━━━━━━━━━━━━━━━━━━━━ 3s 65ms/step - loss: 0.0067 - mae: 0.0540

309/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0068 - mae: 0.0540

310/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0068 - mae: 0.0541

311/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0068 - mae: 0.0541

312/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0068 - mae: 0.0540

313/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0067 - mae: 0.0540

314/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0067 - mae: 0.0540

315/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0067 - mae: 0.0539

316/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0067 - mae: 0.0538

317/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0067 - mae: 0.0538

319/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0067 - mae: 0.0537

320/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0067 - mae: 0.0537

321/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0067 - mae: 0.0537

322/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0067 - mae: 0.0537

323/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0067 - mae: 0.0536

324/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0536

325/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0535

326/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0535

327/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0535

328/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0534

329/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0534

330/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0534

331/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0534

332/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0534

333/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0534

334/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0534

335/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0066 - mae: 0.0533

336/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0533

337/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0534

338/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0534

339/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0534

340/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0533

341/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0534

342/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0534

343/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0534

344/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0534

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0533

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0533

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0532

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0533

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0533

350/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0532

351/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0066 - mae: 0.0532

352/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0533

353/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0533

354/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0533

355/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0533

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0533

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0533

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0533

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0533

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0533

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0533

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0534

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0534

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0534

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0066 - mae: 0.0534

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 26s 68ms/step - loss: 0.0066 - mae: 0.0534 - val_loss: 0.0064 - val_mae: 0.0514 - learning_rate: 1.0000e-04

Epoch 2/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 30s 83ms/step - loss: 0.0106 - mae: 0.0685

  2/367 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - loss: 0.0066 - mae: 0.0517

  4/367 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - loss: 0.0046 - mae: 0.0428

  5/367 ━━━━━━━━━━━━━━━━━━━━ 19s 54ms/step - loss: 0.0045 - mae: 0.0429

  6/367 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - loss: 0.0051 - mae: 0.0456

  7/367 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - loss: 0.0059 - mae: 0.0466

  8/367 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - loss: 0.0062 - mae: 0.0479

 10/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0062 - mae: 0.0477

 11/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0062 - mae: 0.0480

 13/367 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - loss: 0.0059 - mae: 0.0475

 15/367 ━━━━━━━━━━━━━━━━━━━━ 18s 51ms/step - loss: 0.0057 - mae: 0.0472

 17/367 ━━━━━━━━━━━━━━━━━━━━ 17s 51ms/step - loss: 0.0055 - mae: 0.0470

 18/367 ━━━━━━━━━━━━━━━━━━━━ 17s 51ms/step - loss: 0.0055 - mae: 0.0476

 19/367 ━━━━━━━━━━━━━━━━━━━━ 17s 51ms/step - loss: 0.0057 - mae: 0.0480

 21/367 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - loss: 0.0057 - mae: 0.0483

 23/367 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - loss: 0.0055 - mae: 0.0481

 25/367 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - loss: 0.0056 - mae: 0.0486

 27/367 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - loss: 0.0056 - mae: 0.0487

 28/367 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - loss: 0.0056 - mae: 0.0484

 29/367 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - loss: 0.0057 - mae: 0.0488

 30/367 ━━━━━━━━━━━━━━━━━━━━ 17s 51ms/step - loss: 0.0057 - mae: 0.0489

 32/367 ━━━━━━━━━━━━━━━━━━━━ 16s 51ms/step - loss: 0.0058 - mae: 0.0497

 33/367 ━━━━━━━━━━━━━━━━━━━━ 16s 51ms/step - loss: 0.0059 - mae: 0.0499

 34/367 ━━━━━━━━━━━━━━━━━━━━ 16s 51ms/step - loss: 0.0059 - mae: 0.0501

 36/367 ━━━━━━━━━━━━━━━━━━━━ 16s 51ms/step - loss: 0.0059 - mae: 0.0501

 37/367 ━━━━━━━━━━━━━━━━━━━━ 16s 51ms/step - loss: 0.0058 - mae: 0.0501

 38/367 ━━━━━━━━━━━━━━━━━━━━ 16s 51ms/step - loss: 0.0058 - mae: 0.0500

 39/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0058 - mae: 0.0498

 40/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0057 - mae: 0.0495

 41/367 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - loss: 0.0057 - mae: 0.0495

 42/367 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - loss: 0.0059 - mae: 0.0503

 43/367 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - loss: 0.0060 - mae: 0.0505

 45/367 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - loss: 0.0062 - mae: 0.0512

 46/367 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - loss: 0.0061 - mae: 0.0513

 47/367 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - loss: 0.0063 - mae: 0.0514

 48/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0064 - mae: 0.0517

 49/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0064 - mae: 0.0517

 50/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0064 - mae: 0.0518

 51/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0063 - mae: 0.0517

 52/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0063 - mae: 0.0516

 53/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0062 - mae: 0.0515

 54/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0062 - mae: 0.0514

 55/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0063 - mae: 0.0518

 56/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0063 - mae: 0.0517

 57/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0063 - mae: 0.0514

 58/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0062 - mae: 0.0513

 59/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0062 - mae: 0.0512

 60/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0062 - mae: 0.0512

 61/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0061 - mae: 0.0510

 62/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0061 - mae: 0.0507

 63/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0060 - mae: 0.0505

 64/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0060 - mae: 0.0505

 65/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0060 - mae: 0.0504

 67/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0060 - mae: 0.0505

 68/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0060 - mae: 0.0505

 69/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0061 - mae: 0.0506

 71/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0061 - mae: 0.0507

 72/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0061 - mae: 0.0508

 73/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0061 - mae: 0.0507

 74/367 ━━━━━━━━━━━━━━━━━━━━ 15s 54ms/step - loss: 0.0061 - mae: 0.0507

 75/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0061 - mae: 0.0506

 76/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0061 - mae: 0.0506

 77/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0060 - mae: 0.0505

 79/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0060 - mae: 0.0504

 80/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0060 - mae: 0.0504

 82/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0061 - mae: 0.0507

 83/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0061 - mae: 0.0509

 85/367 ━━━━━━━━━━━━━━━━━━━━ 15s 54ms/step - loss: 0.0062 - mae: 0.0509

 86/367 ━━━━━━━━━━━━━━━━━━━━ 15s 54ms/step - loss: 0.0063 - mae: 0.0510

 87/367 ━━━━━━━━━━━━━━━━━━━━ 15s 54ms/step - loss: 0.0064 - mae: 0.0513

 89/367 ━━━━━━━━━━━━━━━━━━━━ 15s 54ms/step - loss: 0.0063 - mae: 0.0513

 90/367 ━━━━━━━━━━━━━━━━━━━━ 15s 54ms/step - loss: 0.0063 - mae: 0.0510

 91/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0063 - mae: 0.0511

 92/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0510

 93/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0508

 94/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0509

 95/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0509

 97/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0509

 99/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0509

100/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0509

101/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0508

102/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0061 - mae: 0.0506

103/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0061 - mae: 0.0506

105/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0507

106/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0508

108/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0507

109/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0062 - mae: 0.0508

110/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0062 - mae: 0.0508

111/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0062 - mae: 0.0508

112/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0062 - mae: 0.0508

113/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0062 - mae: 0.0508

115/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0062 - mae: 0.0508

116/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0062 - mae: 0.0508

117/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0062 - mae: 0.0508

118/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0062 - mae: 0.0508

119/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0062 - mae: 0.0507

120/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0061 - mae: 0.0507

121/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0061 - mae: 0.0506

122/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0061 - mae: 0.0506

123/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0061 - mae: 0.0507

124/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0062 - mae: 0.0508

125/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0061 - mae: 0.0508

126/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0061 - mae: 0.0509

127/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0061 - mae: 0.0509

128/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0062 - mae: 0.0510

129/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0062 - mae: 0.0510

130/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0061 - mae: 0.0510

131/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0061 - mae: 0.0508

133/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0061 - mae: 0.0509

134/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0062 - mae: 0.0510

135/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0062 - mae: 0.0510

136/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0062 - mae: 0.0510

137/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0062 - mae: 0.0510

138/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0062 - mae: 0.0511

139/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0062 - mae: 0.0511

140/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0061 - mae: 0.0511

141/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0061 - mae: 0.0511

142/367 ━━━━━━━━━━━━━━━━━━━━ 12s 54ms/step - loss: 0.0061 - mae: 0.0510

143/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0061 - mae: 0.0510

144/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0061 - mae: 0.0510

145/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0061 - mae: 0.0510

146/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0061 - mae: 0.0510

147/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0061 - mae: 0.0511

148/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0061 - mae: 0.0512

149/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0061 - mae: 0.0511

150/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0061 - mae: 0.0512

151/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0062 - mae: 0.0514

152/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0062 - mae: 0.0514

153/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0062 - mae: 0.0514

154/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0062 - mae: 0.0514

155/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0062 - mae: 0.0514

156/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0061 - mae: 0.0513

157/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0061 - mae: 0.0513

158/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0061 - mae: 0.0513

159/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0061 - mae: 0.0513

160/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0062 - mae: 0.0514

161/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0062 - mae: 0.0515

162/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0062 - mae: 0.0516

163/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0062 - mae: 0.0516

164/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0062 - mae: 0.0516

165/367 ━━━━━━━━━━━━━━━━━━━━ 11s 56ms/step - loss: 0.0062 - mae: 0.0514

166/367 ━━━━━━━━━━━━━━━━━━━━ 11s 56ms/step - loss: 0.0062 - mae: 0.0514

167/367 ━━━━━━━━━━━━━━━━━━━━ 11s 56ms/step - loss: 0.0062 - mae: 0.0514

168/367 ━━━━━━━━━━━━━━━━━━━━ 11s 56ms/step - loss: 0.0062 - mae: 0.0514

169/367 ━━━━━━━━━━━━━━━━━━━━ 11s 56ms/step - loss: 0.0061 - mae: 0.0514

170/367 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - loss: 0.0062 - mae: 0.0514

172/367 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - loss: 0.0061 - mae: 0.0513

173/367 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - loss: 0.0061 - mae: 0.0513

174/367 ━━━━━━━━━━━━━━━━━━━━ 10s 55ms/step - loss: 0.0061 - mae: 0.0513

175/367 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - loss: 0.0061 - mae: 0.0513

177/367 ━━━━━━━━━━━━━━━━━━━━ 10s 55ms/step - loss: 0.0061 - mae: 0.0513

178/367 ━━━━━━━━━━━━━━━━━━━━ 10s 55ms/step - loss: 0.0061 - mae: 0.0513

179/367 ━━━━━━━━━━━━━━━━━━━━ 10s 55ms/step - loss: 0.0061 - mae: 0.0513

180/367 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - loss: 0.0061 - mae: 0.0512

181/367 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - loss: 0.0061 - mae: 0.0513

182/367 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - loss: 0.0061 - mae: 0.0513

184/367 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - loss: 0.0061 - mae: 0.0513

186/367 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - loss: 0.0061 - mae: 0.0513

187/367 ━━━━━━━━━━━━━━━━━━━━ 10s 56ms/step - loss: 0.0061 - mae: 0.0513

188/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0513

190/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0513

191/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0513

192/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0514

194/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0514

195/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0514

196/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0514

197/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0514

198/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0513

199/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0513

200/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0513

201/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0513

202/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0513

203/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0061 - mae: 0.0513

204/367 ━━━━━━━━━━━━━━━━━━━━ 9s 56ms/step - loss: 0.0060 - mae: 0.0512

206/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0061 - mae: 0.0512

207/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0512

208/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0512

209/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0512

210/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0512

211/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0512

212/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0511

213/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0512

214/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0061 - mae: 0.0513

215/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0061 - mae: 0.0512

216/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0061 - mae: 0.0512

217/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0512

218/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0512

219/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0061 - mae: 0.0513

220/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0061 - mae: 0.0513

221/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0061 - mae: 0.0513

222/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0513

223/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0061 - mae: 0.0513

225/367 ━━━━━━━━━━━━━━━━━━━━ 8s 56ms/step - loss: 0.0060 - mae: 0.0512

226/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0060 - mae: 0.0511

227/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0060 - mae: 0.0511

228/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0061 - mae: 0.0512

229/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0061 - mae: 0.0512

230/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0061 - mae: 0.0512

231/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0061 - mae: 0.0512

232/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0061 - mae: 0.0512

233/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0061 - mae: 0.0512

234/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0061 - mae: 0.0512

235/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0061 - mae: 0.0513

236/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0060 - mae: 0.0512

237/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0060 - mae: 0.0512

238/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0060 - mae: 0.0511

239/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0060 - mae: 0.0511

240/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0060 - mae: 0.0511

241/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0060 - mae: 0.0511

242/367 ━━━━━━━━━━━━━━━━━━━━ 7s 56ms/step - loss: 0.0060 - mae: 0.0511

243/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0510

244/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0511

245/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0511

246/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0510

247/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0511

248/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0510

249/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0510

250/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0509

251/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0510

252/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0510

253/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0060 - mae: 0.0511

254/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0061 - mae: 0.0511

256/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0061 - mae: 0.0511

257/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0061 - mae: 0.0511

258/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0061 - mae: 0.0511

260/367 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - loss: 0.0061 - mae: 0.0512

261/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0061 - mae: 0.0513

263/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0061 - mae: 0.0512

264/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0061 - mae: 0.0512

265/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0061 - mae: 0.0512

266/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0061 - mae: 0.0511

268/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0061 - mae: 0.0511

269/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0061 - mae: 0.0511

270/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0061 - mae: 0.0511

271/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0060 - mae: 0.0511

272/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0060 - mae: 0.0510

273/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0060 - mae: 0.0511

274/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0060 - mae: 0.0511

275/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0061 - mae: 0.0512

277/367 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step - loss: 0.0061 - mae: 0.0512

278/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

280/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

281/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

282/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

283/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

284/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

285/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

286/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

287/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

289/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

291/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0512

292/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0513

293/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0512

294/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0512

295/367 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step - loss: 0.0061 - mae: 0.0511

296/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

297/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0512

298/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

299/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

300/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

301/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

302/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

303/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0512

304/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0512

305/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

306/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

307/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

308/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0512

309/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0060 - mae: 0.0511

310/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0512

311/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

313/367 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - loss: 0.0061 - mae: 0.0511

314/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0061 - mae: 0.0511

315/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0510

316/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0510

317/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0509

318/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0509

319/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0509

320/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0509

321/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0509

323/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0508

325/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0508

326/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0508

328/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0508

330/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0508

331/367 ━━━━━━━━━━━━━━━━━━━━ 2s 56ms/step - loss: 0.0060 - mae: 0.0508

332/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

333/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

334/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

335/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

336/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

337/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

338/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

339/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

340/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

341/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

342/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0508

343/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0507

344/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0507

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0506

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0506

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0507

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0507

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step - loss: 0.0060 - mae: 0.0507

350/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

351/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

352/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

353/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

354/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0508

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0508

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0508

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0508

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0508

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0060 - mae: 0.0507

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 22s 60ms/step - loss: 0.0060 - mae: 0.0507 - val_loss: 0.0059 - val_mae: 0.0497 - learning_rate: 1.0000e-04

Epoch 3/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 33s 91ms/step - loss: 0.0049 - mae: 0.0478

  2/367 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - loss: 0.0046 - mae: 0.0455

  3/367 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - loss: 0.0050 - mae: 0.0469

  4/367 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - loss: 0.0051 - mae: 0.0480

  5/367 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - loss: 0.0056 - mae: 0.0502

  6/367 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - loss: 0.0055 - mae: 0.0499

  7/367 ━━━━━━━━━━━━━━━━━━━━ 19s 54ms/step - loss: 0.0053 - mae: 0.0492

  9/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0054 - mae: 0.0489

 10/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0054 - mae: 0.0485

 11/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0056 - mae: 0.0486

 12/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0056 - mae: 0.0491

 13/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0062 - mae: 0.0506

 14/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0062 - mae: 0.0503

 15/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0062 - mae: 0.0508

 16/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0060 - mae: 0.0501

 17/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0061 - mae: 0.0509

 18/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0064 - mae: 0.0521

 19/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0062 - mae: 0.0516

 20/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0064 - mae: 0.0517

 21/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0063 - mae: 0.0512

 22/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0064 - mae: 0.0517

 24/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0065 - mae: 0.0518

 25/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0064 - mae: 0.0519

 26/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0063 - mae: 0.0516

 27/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0063 - mae: 0.0517

 28/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0063 - mae: 0.0518

 29/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0062 - mae: 0.0514

 30/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0062 - mae: 0.0513

 31/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0064 - mae: 0.0524

 32/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0064 - mae: 0.0524

 34/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0064 - mae: 0.0523

 35/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0064 - mae: 0.0523

 36/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0063 - mae: 0.0521

 37/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0063 - mae: 0.0525

 38/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0064 - mae: 0.0527

 39/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0064 - mae: 0.0528

 40/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0063 - mae: 0.0527

 41/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0063 - mae: 0.0525

 42/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0064 - mae: 0.0529

 43/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0064 - mae: 0.0531

 44/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0064 - mae: 0.0529

 45/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0064 - mae: 0.0529

 46/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0064 - mae: 0.0529

 48/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0063 - mae: 0.0528

 49/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0063 - mae: 0.0528

 50/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0063 - mae: 0.0529

 51/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0062 - mae: 0.0524

 52/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0062 - mae: 0.0525

 54/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0062 - mae: 0.0525

 56/367 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - loss: 0.0062 - mae: 0.0526

 57/367 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - loss: 0.0062 - mae: 0.0522

 59/367 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - loss: 0.0062 - mae: 0.0522

 60/367 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - loss: 0.0063 - mae: 0.0524

 62/367 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - loss: 0.0064 - mae: 0.0530

 64/367 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - loss: 0.0063 - mae: 0.0528

 66/367 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - loss: 0.0063 - mae: 0.0527

 67/367 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - loss: 0.0063 - mae: 0.0526

 69/367 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - loss: 0.0063 - mae: 0.0525

 70/367 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - loss: 0.0062 - mae: 0.0523

 71/367 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - loss: 0.0062 - mae: 0.0521

 72/367 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - loss: 0.0062 - mae: 0.0519

 74/367 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - loss: 0.0061 - mae: 0.0517

 75/367 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - loss: 0.0061 - mae: 0.0516

 77/367 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - loss: 0.0061 - mae: 0.0514

 78/367 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - loss: 0.0060 - mae: 0.0511

 79/367 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - loss: 0.0060 - mae: 0.0510

 80/367 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - loss: 0.0061 - mae: 0.0512

 81/367 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - loss: 0.0060 - mae: 0.0511

 82/367 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - loss: 0.0060 - mae: 0.0509

 84/367 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - loss: 0.0060 - mae: 0.0508

 85/367 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - loss: 0.0060 - mae: 0.0509

 86/367 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - loss: 0.0060 - mae: 0.0507

 87/367 ━━━━━━━━━━━━━━━━━━━━ 14s 52ms/step - loss: 0.0060 - mae: 0.0507

 88/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0060 - mae: 0.0508

 89/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0060 - mae: 0.0509

 90/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0060 - mae: 0.0509

 92/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0060 - mae: 0.0508

 93/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0060 - mae: 0.0506

 95/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0060 - mae: 0.0505

 96/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0060 - mae: 0.0504

 97/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0060 - mae: 0.0504

 98/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0059 - mae: 0.0503

 99/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0059 - mae: 0.0502

100/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0059 - mae: 0.0501

101/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0059 - mae: 0.0502

102/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0059 - mae: 0.0501

103/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0059 - mae: 0.0499

104/367 ━━━━━━━━━━━━━━━━━━━━ 14s 54ms/step - loss: 0.0058 - mae: 0.0497

105/367 ━━━━━━━━━━━━━━━━━━━━ 14s 53ms/step - loss: 0.0058 - mae: 0.0495

106/367 ━━━━━━━━━━━━━━━━━━━━ 13s 53ms/step - loss: 0.0058 - mae: 0.0495

108/367 ━━━━━━━━━━━━━━━━━━━━ 13s 53ms/step - loss: 0.0059 - mae: 0.0497

109/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0059 - mae: 0.0497

110/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0059 - mae: 0.0496

111/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0059 - mae: 0.0496

112/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0059 - mae: 0.0496

113/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0058 - mae: 0.0495

114/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0059 - mae: 0.0497

115/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0059 - mae: 0.0498

116/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0058 - mae: 0.0496

117/367 ━━━━━━━━━━━━━━━━━━━━ 13s 54ms/step - loss: 0.0059 - mae: 0.0497

118/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0497

119/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0497

120/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0497

121/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0498

122/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0498

123/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0498

124/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0498

125/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0497

126/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0497

127/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0498

128/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0498

129/367 ━━━━━━━━━━━━━━━━━━━━ 13s 55ms/step - loss: 0.0059 - mae: 0.0499

130/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0059 - mae: 0.0499

131/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0059 - mae: 0.0499

132/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0059 - mae: 0.0499

133/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0059 - mae: 0.0499

134/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0498

135/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0497

136/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0497

137/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0498

138/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0498

139/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0498

140/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0497

141/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0496

143/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0496

144/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0496

145/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0496

146/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0496

147/367 ━━━━━━━━━━━━━━━━━━━━ 12s 55ms/step - loss: 0.0058 - mae: 0.0496

148/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0058 - mae: 0.0496

149/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0058 - mae: 0.0497

150/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0058 - mae: 0.0495

151/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0058 - mae: 0.0495

152/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0057 - mae: 0.0494

153/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0057 - mae: 0.0494

154/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0057 - mae: 0.0494

155/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0057 - mae: 0.0494

157/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0057 - mae: 0.0495

159/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0058 - mae: 0.0497

160/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0058 - mae: 0.0497

161/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0058 - mae: 0.0497

162/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0058 - mae: 0.0497

164/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0058 - mae: 0.0498

165/367 ━━━━━━━━━━━━━━━━━━━━ 11s 55ms/step - loss: 0.0058 - mae: 0.0497

167/367 ━━━━━━━━━━━━━━━━━━━━ 10s 55ms/step - loss: 0.0058 - mae: 0.0497

168/367 ━━━━━━━━━━━━━━━━━━━━ 10s 55ms/step - loss: 0.0058 - mae: 0.0497

170/367 ━━━━━━━━━━━━━━━━━━━━ 10s 55ms/step - loss: 0.0058 - mae: 0.0497

172/367 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - loss: 0.0058 - mae: 0.0498

173/367 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - loss: 0.0058 - mae: 0.0498

174/367 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - loss: 0.0058 - mae: 0.0498

175/367 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - loss: 0.0058 - mae: 0.0499

176/367 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - loss: 0.0058 - mae: 0.0499

177/367 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - loss: 0.0058 - mae: 0.0498

178/367 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - loss: 0.0058 - mae: 0.0499

179/367 ━━━━━━━━━━━━━━━━━━━━ 10s 55ms/step - loss: 0.0058 - mae: 0.0499

180/367 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - loss: 0.0058 - mae: 0.0498

181/367 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - loss: 0.0058 - mae: 0.0498

182/367 ━━━━━━━━━━━━━━━━━━━━ 10s 54ms/step - loss: 0.0058 - mae: 0.0498

183/367 ━━━━━━━━━━━━━━━━━━━━ 10s 55ms/step - loss: 0.0057 - mae: 0.0498

184/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0498

185/367 ━━━━━━━━━━━━━━━━━━━━ 9s 54ms/step - loss: 0.0057 - mae: 0.0497

186/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0497

188/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0496

189/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0495

190/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0495

191/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0494

192/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0056 - mae: 0.0494

193/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0056 - mae: 0.0494

194/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0494

195/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0494

196/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0495

197/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0496

198/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0496

199/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0496

200/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0495

201/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0495

203/367 ━━━━━━━━━━━━━━━━━━━━ 9s 55ms/step - loss: 0.0057 - mae: 0.0496

204/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0496

205/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0496

206/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0497

207/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0496

208/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0496

209/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0497

210/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0497

211/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0497

212/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0497

213/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0497

214/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0496

215/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0496

217/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0497

218/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0497

219/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0497

220/367 ━━━━━━━━━━━━━━━━━━━━ 8s 55ms/step - loss: 0.0057 - mae: 0.0496

222/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0495

223/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0495

225/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0495

226/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0494

227/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0494

228/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0493

229/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0493

230/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0494

231/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0494

232/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0493

233/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0493

234/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0494

235/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0493

236/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0493

237/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0493

238/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0056 - mae: 0.0493

239/367 ━━━━━━━━━━━━━━━━━━━━ 7s 55ms/step - loss: 0.0057 - mae: 0.0493

240/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0493

241/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0493

242/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0493

243/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0492

244/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0492

245/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0492

247/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0492

248/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0492

249/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0491

250/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0491

251/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0491

252/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0492

253/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0492

255/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0492

256/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0492

257/367 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step - loss: 0.0056 - mae: 0.0492

258/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0492

259/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

260/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

262/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0055 - mae: 0.0490

263/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

264/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

265/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

267/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

268/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

269/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

270/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0055 - mae: 0.0490

271/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

272/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

273/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0056 - mae: 0.0491

274/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0055 - mae: 0.0490

275/367 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step - loss: 0.0055 - mae: 0.0490

276/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0490

277/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0490

278/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0490

279/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0490

280/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0490

281/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0490

282/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0489

283/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0489

284/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0489

285/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0489

286/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0489

287/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0489

288/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0489

290/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0489

291/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0489

292/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0489

293/367 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step - loss: 0.0055 - mae: 0.0490

294/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0490

295/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0490

297/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0490

298/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0490

299/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0489

300/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0490

301/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0490

303/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0491

304/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0491

305/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0491

306/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0492

307/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0492

308/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0492

309/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0492

310/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0492

311/367 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - loss: 0.0055 - mae: 0.0491

313/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0492

314/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0492

315/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0491

316/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0491

318/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0490

319/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0490

320/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0490

322/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0491

323/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0491

324/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0491

325/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0491

327/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0491

328/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0491

329/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0491

330/367 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - loss: 0.0055 - mae: 0.0491

331/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

332/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0491

333/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

334/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

336/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

337/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

338/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

339/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

340/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0491

341/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

342/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

343/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

344/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0490

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step - loss: 0.0055 - mae: 0.0489

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - loss: 0.0055 - mae: 0.0489

349/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0055 - mae: 0.0489

351/367 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0055 - mae: 0.0489

352/367 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0055 - mae: 0.0489

353/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0055 - mae: 0.0489

354/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0055 - mae: 0.0489

355/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0055 - mae: 0.0489

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0055 - mae: 0.0488

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0055 - mae: 0.0488

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0054 - mae: 0.0488

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0054 - mae: 0.0488

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0054 - mae: 0.0488

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0054 - mae: 0.0488

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0054 - mae: 0.0488

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0054 - mae: 0.0488

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0054 - mae: 0.0488

366/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0055 - mae: 0.0489

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0055 - mae: 0.0489

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 22s 60ms/step - loss: 0.0055 - mae: 0.0489 - val_loss: 0.0054 - val_mae: 0.0472 - learning_rate: 1.0000e-04

Epoch 4/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 33s 92ms/step - loss: 0.0115 - mae: 0.0629

  2/367 ━━━━━━━━━━━━━━━━━━━━ 22s 61ms/step - loss: 0.0097 - mae: 0.0619

  3/367 ━━━━━━━━━━━━━━━━━━━━ 20s 57ms/step - loss: 0.0072 - mae: 0.0513

  4/367 ━━━━━━━━━━━━━━━━━━━━ 19s 54ms/step - loss: 0.0067 - mae: 0.0505

  5/367 ━━━━━━━━━━━━━━━━━━━━ 20s 56ms/step - loss: 0.0061 - mae: 0.0490

  6/367 ━━━━━━━━━━━━━━━━━━━━ 19s 55ms/step - loss: 0.0055 - mae: 0.0464

  7/367 ━━━━━━━━━━━━━━━━━━━━ 19s 55ms/step - loss: 0.0054 - mae: 0.0463

  8/367 ━━━━━━━━━━━━━━━━━━━━ 19s 55ms/step - loss: 0.0053 - mae: 0.0452

  9/367 ━━━━━━━━━━━━━━━━━━━━ 19s 54ms/step - loss: 0.0053 - mae: 0.0457

 10/367 ━━━━━━━━━━━━━━━━━━━━ 19s 54ms/step - loss: 0.0051 - mae: 0.0454

 11/367 ━━━━━━━━━━━━━━━━━━━━ 19s 54ms/step - loss: 0.0052 - mae: 0.0457

 12/367 ━━━━━━━━━━━━━━━━━━━━ 19s 54ms/step - loss: 0.0051 - mae: 0.0454

 13/367 ━━━━━━━━━━━━━━━━━━━━ 19s 54ms/step - loss: 0.0054 - mae: 0.0470

 15/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0054 - mae: 0.0469

 17/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0052 - mae: 0.0462

 18/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0052 - mae: 0.0466

 20/367 ━━━━━━━━━━━━━━━━━━━━ 18s 53ms/step - loss: 0.0055 - mae: 0.0471

 22/367 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - loss: 0.0057 - mae: 0.0478

 24/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0056 - mae: 0.0477

 26/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0059 - mae: 0.0484

 27/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0058 - mae: 0.0484

 28/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0057 - mae: 0.0482

 29/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0058 - mae: 0.0489

 30/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0057 - mae: 0.0488

 31/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0057 - mae: 0.0487

 32/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0056 - mae: 0.0487

 33/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0056 - mae: 0.0489

 34/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0056 - mae: 0.0486

 35/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0055 - mae: 0.0482

 36/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0055 - mae: 0.0484

 38/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0056 - mae: 0.0491

 39/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0056 - mae: 0.0492

 40/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0056 - mae: 0.0492

 41/367 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - loss: 0.0056 - mae: 0.0492

 42/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0056 - mae: 0.0491

 43/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0056 - mae: 0.0493

 45/367 ━━━━━━━━━━━━━━━━━━━━ 17s 53ms/step - loss: 0.0057 - mae: 0.0499

 47/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0056 - mae: 0.0494

 48/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0056 - mae: 0.0492

 49/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0056 - mae: 0.0493

 50/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0056 - mae: 0.0495

 51/367 ━━━━━━━━━━━━━━━━━━━━ 16s 53ms/step - loss: 0.0056 - mae: 0.0494

 52/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0056 - mae: 0.0493

 53/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0056 - mae: 0.0495

 55/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0057 - mae: 0.0500

 56/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0058 - mae: 0.0503

 57/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0058 - mae: 0.0503

 58/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0057 - mae: 0.0501

 59/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0057 - mae: 0.0498

 60/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0056 - mae: 0.0498

 61/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0056 - mae: 0.0495

 62/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0055 - mae: 0.0493

 63/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0056 - mae: 0.0492

 64/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0056 - mae: 0.0492

 65/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0055 - mae: 0.0491

 66/367 ━━━━━━━━━━━━━━━━━━━━ 16s 54ms/step - loss: 0.0055 - mae: 0.0489

 67/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0055 - mae: 0.0490

 68/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0055 - mae: 0.0488

 69/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0054 - mae: 0.0488

 70/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0054 - mae: 0.0486

 71/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0054 - mae: 0.0487

 72/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0054 - mae: 0.0486

 73/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0054 - mae: 0.0486

 74/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0054 - mae: 0.0488

 75/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0054 - mae: 0.0487

 76/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0054 - mae: 0.0487

 77/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0054 - mae: 0.0486

 78/367 ━━━━━━━━━━━━━━━━━━━━ 16s 55ms/step - loss: 0.0054 - mae: 0.0488

 79/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0488

 80/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0487

 81/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0053 - mae: 0.0486

 82/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0485

 83/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0053 - mae: 0.0484

 84/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0053 - mae: 0.0484

 85/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0053 - mae: 0.0483

 86/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0485

 87/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0485

 88/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0488

 89/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0486

 90/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0485

 91/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0053 - mae: 0.0484

 92/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0484

 93/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0486

 94/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0485

 95/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0054 - mae: 0.0483

 96/367 ━━━━━━━━━━━━━━━━━━━━ 15s 55ms/step - loss: 0.0053 - mae: 0.0483

 98/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0053 - mae: 0.0481

 99/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0053 - mae: 0.0480

100/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0053 - mae: 0.0481

101/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0053 - mae: 0.0480

102/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0053 - mae: 0.0481

103/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0053 - mae: 0.0480

104/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0053 - mae: 0.0481

105/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0053 - mae: 0.0481

106/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0053 - mae: 0.0481

107/367 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - loss: 0.0053 - mae: 0.0482

108/367 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - loss: 0.0053 - mae: 0.0482

109/367 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - loss: 0.0053 - mae: 0.0482

110/367 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - loss: 0.0052 - mae: 0.0481

111/367 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - loss: 0.0052 - mae: 0.0481

112/367 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - loss: 0.0052 - mae: 0.0480

113/367 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - loss: 0.0052 - mae: 0.0481

114/367 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - loss: 0.0052 - mae: 0.0481

115/367 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - loss: 0.0052 - mae: 0.0482

116/367 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - loss: 0.0052 - mae: 0.0482

117/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0052 - mae: 0.0482

118/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0052 - mae: 0.0483

119/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0052 - mae: 0.0483

120/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0052 - mae: 0.0482

121/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0052 - mae: 0.0483

122/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0052 - mae: 0.0481

123/367 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - loss: 0.0052 - mae: 0.0480

124/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0052 - mae: 0.0480

125/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0052 - mae: 0.0479

126/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0052 - mae: 0.0481

127/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0052 - mae: 0.0480

128/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0052 - mae: 0.0479

129/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0478

130/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0477

131/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0477

132/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0052 - mae: 0.0478

133/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0478

134/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0477

135/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0475

136/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0476

137/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0475

138/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0474

139/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0473

140/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0473

141/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0473

142/367 ━━━━━━━━━━━━━━━━━━━━ 13s 58ms/step - loss: 0.0051 - mae: 0.0473

143/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0051 - mae: 0.0472

144/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0051 - mae: 0.0473

145/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0051 - mae: 0.0472

146/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0472

147/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0472

148/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0471

149/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0471

150/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0471

151/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0471

152/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0470

153/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0470

154/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0471

155/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0471

156/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0472

157/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0472

158/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0472

159/367 ━━━━━━━━━━━━━━━━━━━━ 12s 58ms/step - loss: 0.0050 - mae: 0.0472

160/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

161/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

162/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

163/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

164/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

165/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

166/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

167/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

168/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

169/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0470

170/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

171/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0470

172/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0469

173/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0470

174/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0469

175/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0470

176/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0471

177/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0470

178/367 ━━━━━━━━━━━━━━━━━━━━ 11s 58ms/step - loss: 0.0050 - mae: 0.0470

179/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0050 - mae: 0.0470

180/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0470

181/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0050 - mae: 0.0470

182/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0469

183/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0469

184/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0469

185/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0469

186/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0468

187/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0468

188/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0468

189/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0468

190/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0468

191/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0468

192/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0468

193/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0468

194/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0468

195/367 ━━━━━━━━━━━━━━━━━━━━ 10s 59ms/step - loss: 0.0049 - mae: 0.0468

196/367 ━━━━━━━━━━━━━━━━━━━━ 10s 58ms/step - loss: 0.0049 - mae: 0.0467

197/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0468

198/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0468

199/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0467

200/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0467

201/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0466

202/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0467

203/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0466

204/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0466

205/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0466

206/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0466

207/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0465

208/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0466

209/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0466

210/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0467

211/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0466

212/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0049 - mae: 0.0466

213/367 ━━━━━━━━━━━━━━━━━━━━ 9s 58ms/step - loss: 0.0048 - mae: 0.0466

214/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0465

215/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0465

216/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0465

217/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0465

218/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0465

219/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0465

220/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0464

221/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0464

222/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0464

223/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0463

224/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0463

225/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0463

226/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0463

227/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0463

228/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0463

229/367 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step - loss: 0.0048 - mae: 0.0462

230/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0463

231/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0462

232/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0462

233/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0462

234/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0462

235/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0462

236/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0462

237/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0461

238/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0462

239/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0462

240/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0462

241/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0461

242/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0461

243/367 ━━━━━━━━━━━━━━━━━━━━ 7s 58ms/step - loss: 0.0048 - mae: 0.0461

244/367 ━━━━━━━━━━━━━━━━━━━━ 7s 59ms/step - loss: 0.0048 - mae: 0.0461

245/367 ━━━━━━━━━━━━━━━━━━━━ 7s 59ms/step - loss: 0.0048 - mae: 0.0461

246/367 ━━━━━━━━━━━━━━━━━━━━ 7s 59ms/step - loss: 0.0048 - mae: 0.0461

247/367 ━━━━━━━━━━━━━━━━━━━━ 7s 59ms/step - loss: 0.0047 - mae: 0.0461

248/367 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - loss: 0.0048 - mae: 0.0461

249/367 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - loss: 0.0048 - mae: 0.0462

250/367 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - loss: 0.0047 - mae: 0.0461

251/367 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step - loss: 0.0047 - mae: 0.0461

252/367 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - loss: 0.0047 - mae: 0.0461

253/367 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - loss: 0.0047 - mae: 0.0461

254/367 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - loss: 0.0047 - mae: 0.0460

255/367 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - loss: 0.0047 - mae: 0.0460

256/367 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - loss: 0.0047 - mae: 0.0460

257/367 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step - loss: 0.0047 - mae: 0.0460

258/367 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step - loss: 0.0047 - mae: 0.0461

259/367 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step - loss: 0.0047 - mae: 0.0460

260/367 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step - loss: 0.0047 - mae: 0.0461

261/367 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step - loss: 0.0047 - mae: 0.0461

262/367 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step - loss: 0.0047 - mae: 0.0461

263/367 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step - loss: 0.0047 - mae: 0.0461

264/367 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step - loss: 0.0047 - mae: 0.0461

265/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0047 - mae: 0.0461

266/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0047 - mae: 0.0461

267/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0047 - mae: 0.0462

268/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0462

269/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0462

270/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0463

271/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0463

272/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0463

273/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0462

274/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0462

275/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0462

276/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0462

277/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0462

278/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0047 - mae: 0.0462

279/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0047 - mae: 0.0461

280/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0462

281/367 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step - loss: 0.0048 - mae: 0.0462

282/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0048 - mae: 0.0461

283/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0461

284/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0461

285/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0461

286/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0461

287/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0461

288/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0460

289/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0460

290/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0460

291/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0460

292/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0459

293/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0459

294/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0459

295/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0459

296/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0459

297/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0459

298/367 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step - loss: 0.0047 - mae: 0.0459

299/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0459

300/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0459

301/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

302/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

303/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

304/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

305/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

306/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

307/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

308/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

309/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

310/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

311/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0458

312/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0457

313/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0046 - mae: 0.0457

314/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0457

315/367 ━━━━━━━━━━━━━━━━━━━━ 3s 58ms/step - loss: 0.0047 - mae: 0.0457

316/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0047 - mae: 0.0457

317/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0047 - mae: 0.0457

318/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0047 - mae: 0.0457

319/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0046 - mae: 0.0456

320/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0046 - mae: 0.0456

321/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0046 - mae: 0.0456

322/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0046 - mae: 0.0456

323/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0046 - mae: 0.0455

324/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0046 - mae: 0.0455

325/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0046 - mae: 0.0455

326/367 ━━━━━━━━━━━━━━━━━━━━ 2s 58ms/step - loss: 0.0046 - mae: 0.0455

327/367 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 0.0046 - mae: 0.0455

328/367 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 0.0046 - mae: 0.0455

329/367 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 0.0046 - mae: 0.0454

330/367 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 0.0046 - mae: 0.0454

331/367 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 0.0046 - mae: 0.0454

332/367 ━━━━━━━━━━━━━━━━━━━━ 2s 59ms/step - loss: 0.0046 - mae: 0.0453

333/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

334/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

335/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

336/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

337/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0454

338/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0454

339/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0454

340/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0454

341/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

342/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

343/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

344/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 59ms/step - loss: 0.0046 - mae: 0.0453

350/367 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0046 - mae: 0.0453

352/367 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0046 - mae: 0.0453

353/367 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0046 - mae: 0.0453

354/367 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0046 - mae: 0.0453

355/367 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0046 - mae: 0.0453

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0046 - mae: 0.0453

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0046 - mae: 0.0453

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0046 - mae: 0.0453

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0046 - mae: 0.0453

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0046 - mae: 0.0453

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0046 - mae: 0.0453

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0046 - mae: 0.0453

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0046 - mae: 0.0453

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0046 - mae: 0.0452

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0046 - mae: 0.0452

366/367 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0046 - mae: 0.0452

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0045 - mae: 0.0452

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 23s 63ms/step - loss: 0.0045 - mae: 0.0452 - val_loss: 0.0043 - val_mae: 0.0439 - learning_rate: 1.0000e-04

Epoch 5/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 37s 103ms/step - loss: 0.0039 - mae: 0.0457

  2/367 ━━━━━━━━━━━━━━━━━━━━ 22s 62ms/step - loss: 0.0052 - mae: 0.0479

  3/367 ━━━━━━━━━━━━━━━━━━━━ 24s 66ms/step - loss: 0.0043 - mae: 0.0451

  4/367 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - loss: 0.0043 - mae: 0.0460

  5/367 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - loss: 0.0038 - mae: 0.0433

  6/367 ━━━━━━━━━━━━━━━━━━━━ 22s 63ms/step - loss: 0.0037 - mae: 0.0425

  7/367 ━━━━━━━━━━━━━━━━━━━━ 22s 62ms/step - loss: 0.0038 - mae: 0.0432

  8/367 ━━━━━━━━━━━━━━━━━━━━ 22s 62ms/step - loss: 0.0038 - mae: 0.0440

  9/367 ━━━━━━━━━━━━━━━━━━━━ 22s 63ms/step - loss: 0.0038 - mae: 0.0441

 10/367 ━━━━━━━━━━━━━━━━━━━━ 22s 62ms/step - loss: 0.0039 - mae: 0.0445

 11/367 ━━━━━━━━━━━━━━━━━━━━ 22s 62ms/step - loss: 0.0041 - mae: 0.0445

 12/367 ━━━━━━━━━━━━━━━━━━━━ 21s 62ms/step - loss: 0.0043 - mae: 0.0448

 13/367 ━━━━━━━━━━━━━━━━━━━━ 21s 62ms/step - loss: 0.0041 - mae: 0.0435

 14/367 ━━━━━━━━━━━━━━━━━━━━ 21s 62ms/step - loss: 0.0040 - mae: 0.0435

 15/367 ━━━━━━━━━━━━━━━━━━━━ 21s 62ms/step - loss: 0.0040 - mae: 0.0434

 16/367 ━━━━━━━━━━━━━━━━━━━━ 21s 62ms/step - loss: 0.0040 - mae: 0.0439

 17/367 ━━━━━━━━━━━━━━━━━━━━ 21s 62ms/step - loss: 0.0040 - mae: 0.0435

 18/367 ━━━━━━━━━━━━━━━━━━━━ 21s 62ms/step - loss: 0.0042 - mae: 0.0439

 19/367 ━━━━━━━━━━━━━━━━━━━━ 21s 62ms/step - loss: 0.0041 - mae: 0.0435

 20/367 ━━━━━━━━━━━━━━━━━━━━ 21s 62ms/step - loss: 0.0041 - mae: 0.0432

 21/367 ━━━━━━━━━━━━━━━━━━━━ 21s 62ms/step - loss: 0.0040 - mae: 0.0429

 22/367 ━━━━━━━━━━━━━━━━━━━━ 21s 61ms/step - loss: 0.0042 - mae: 0.0438

 23/367 ━━━━━━━━━━━━━━━━━━━━ 21s 61ms/step - loss: 0.0041 - mae: 0.0434

 24/367 ━━━━━━━━━━━━━━━━━━━━ 20s 61ms/step - loss: 0.0041 - mae: 0.0432

 25/367 ━━━━━━━━━━━━━━━━━━━━ 20s 61ms/step - loss: 0.0041 - mae: 0.0432

 26/367 ━━━━━━━━━━━━━━━━━━━━ 20s 61ms/step - loss: 0.0040 - mae: 0.0429

 27/367 ━━━━━━━━━━━━━━━━━━━━ 20s 61ms/step - loss: 0.0041 - mae: 0.0431

 28/367 ━━━━━━━━━━━━━━━━━━━━ 20s 61ms/step - loss: 0.0041 - mae: 0.0431

 29/367 ━━━━━━━━━━━━━━━━━━━━ 20s 61ms/step - loss: 0.0040 - mae: 0.0427

 30/367 ━━━━━━━━━━━━━━━━━━━━ 20s 60ms/step - loss: 0.0040 - mae: 0.0429

 31/367 ━━━━━━━━━━━━━━━━━━━━ 20s 60ms/step - loss: 0.0040 - mae: 0.0426

 32/367 ━━━━━━━━━━━━━━━━━━━━ 20s 60ms/step - loss: 0.0039 - mae: 0.0423

 33/367 ━━━━━━━━━━━━━━━━━━━━ 20s 60ms/step - loss: 0.0039 - mae: 0.0425

 34/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0039 - mae: 0.0424

 35/367 ━━━━━━━━━━━━━━━━━━━━ 20s 61ms/step - loss: 0.0039 - mae: 0.0422

 36/367 ━━━━━━━━━━━━━━━━━━━━ 20s 61ms/step - loss: 0.0038 - mae: 0.0420

 37/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0038 - mae: 0.0419

 38/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0038 - mae: 0.0421

 39/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0038 - mae: 0.0419

 40/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0038 - mae: 0.0419

 41/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0037 - mae: 0.0415

 42/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0037 - mae: 0.0416

 43/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0037 - mae: 0.0413

 44/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0037 - mae: 0.0414

 45/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0037 - mae: 0.0412

 46/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0037 - mae: 0.0415

 47/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0038 - mae: 0.0416

 48/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0038 - mae: 0.0414

 49/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0038 - mae: 0.0414

 50/367 ━━━━━━━━━━━━━━━━━━━━ 18s 60ms/step - loss: 0.0038 - mae: 0.0417

 51/367 ━━━━━━━━━━━━━━━━━━━━ 19s 60ms/step - loss: 0.0039 - mae: 0.0418

 52/367 ━━━━━━━━━━━━━━━━━━━━ 19s 61ms/step - loss: 0.0039 - mae: 0.0419

 53/367 ━━━━━━━━━━━━━━━━━━━━ 19s 61ms/step - loss: 0.0039 - mae: 0.0420

 54/367 ━━━━━━━━━━━━━━━━━━━━ 19s 61ms/step - loss: 0.0039 - mae: 0.0418

 55/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0038 - mae: 0.0417

 56/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0039 - mae: 0.0418

 57/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0039 - mae: 0.0421

 58/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0039 - mae: 0.0422

 59/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0039 - mae: 0.0421

 60/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0039 - mae: 0.0422

 61/367 ━━━━━━━━━━━━━━━━━━━━ 18s 60ms/step - loss: 0.0039 - mae: 0.0421

 62/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0039 - mae: 0.0422

 63/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0039 - mae: 0.0422

 64/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0038 - mae: 0.0421

 65/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0038 - mae: 0.0422

 66/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0038 - mae: 0.0423

 67/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0038 - mae: 0.0423

 68/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0038 - mae: 0.0423

 69/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0038 - mae: 0.0423

 70/367 ━━━━━━━━━━━━━━━━━━━━ 18s 61ms/step - loss: 0.0038 - mae: 0.0423

 71/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0038 - mae: 0.0424

 72/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0425

 73/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0038 - mae: 0.0424

 74/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0424

 75/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0424

 76/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0424

 77/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0424

 78/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0423

 79/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0423

 80/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0424

 81/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0425

 82/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0426

 83/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0426

 84/367 ━━━━━━━━━━━━━━━━━━━━ 17s 61ms/step - loss: 0.0039 - mae: 0.0425

 85/367 ━━━━━━━━━━━━━━━━━━━━ 17s 62ms/step - loss: 0.0039 - mae: 0.0424

 87/367 ━━━━━━━━━━━━━━━━━━━━ 17s 62ms/step - loss: 0.0039 - mae: 0.0425

 88/367 ━━━━━━━━━━━━━━━━━━━━ 17s 62ms/step - loss: 0.0039 - mae: 0.0427

 89/367 ━━━━━━━━━━━━━━━━━━━━ 17s 62ms/step - loss: 0.0039 - mae: 0.0427

 90/367 ━━━━━━━━━━━━━━━━━━━━ 17s 62ms/step - loss: 0.0039 - mae: 0.0426

 91/367 ━━━━━━━━━━━━━━━━━━━━ 17s 62ms/step - loss: 0.0039 - mae: 0.0428

 92/367 ━━━━━━━━━━━━━━━━━━━━ 17s 62ms/step - loss: 0.0039 - mae: 0.0428

 93/367 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 0.0039 - mae: 0.0428

 94/367 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 0.0039 - mae: 0.0427

 95/367 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 0.0039 - mae: 0.0427

 96/367 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 0.0039 - mae: 0.0426

 97/367 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 0.0039 - mae: 0.0427

 98/367 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 0.0039 - mae: 0.0427

 99/367 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 0.0039 - mae: 0.0427

100/367 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 0.0039 - mae: 0.0426

101/367 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 0.0039 - mae: 0.0426

102/367 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - loss: 0.0039 - mae: 0.0425

103/367 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - loss: 0.0039 - mae: 0.0424

104/367 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - loss: 0.0039 - mae: 0.0425

105/367 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - loss: 0.0039 - mae: 0.0424

106/367 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - loss: 0.0039 - mae: 0.0423

107/367 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - loss: 0.0039 - mae: 0.0423

108/367 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - loss: 0.0039 - mae: 0.0422

109/367 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - loss: 0.0038 - mae: 0.0422

110/367 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - loss: 0.0038 - mae: 0.0421

111/367 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - loss: 0.0039 - mae: 0.0422

112/367 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - loss: 0.0039 - mae: 0.0422

114/367 ━━━━━━━━━━━━━━━━━━━━ 15s 63ms/step - loss: 0.0039 - mae: 0.0423

116/367 ━━━━━━━━━━━━━━━━━━━━ 15s 63ms/step - loss: 0.0039 - mae: 0.0423

117/367 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - loss: 0.0039 - mae: 0.0423

118/367 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - loss: 0.0039 - mae: 0.0421

119/367 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - loss: 0.0039 - mae: 0.0421

120/367 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - loss: 0.0038 - mae: 0.0421

121/367 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - loss: 0.0038 - mae: 0.0419

122/367 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - loss: 0.0038 - mae: 0.0419

123/367 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - loss: 0.0038 - mae: 0.0420

124/367 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - loss: 0.0038 - mae: 0.0420

125/367 ━━━━━━━━━━━━━━━━━━━━ 15s 63ms/step - loss: 0.0038 - mae: 0.0420

126/367 ━━━━━━━━━━━━━━━━━━━━ 15s 63ms/step - loss: 0.0038 - mae: 0.0421

127/367 ━━━━━━━━━━━━━━━━━━━━ 15s 63ms/step - loss: 0.0038 - mae: 0.0420

128/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0038 - mae: 0.0419

129/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0038 - mae: 0.0419

130/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0038 - mae: 0.0418

131/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0038 - mae: 0.0418

132/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0038 - mae: 0.0418

133/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0038 - mae: 0.0418

134/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0038 - mae: 0.0417

135/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0037 - mae: 0.0417

136/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0037 - mae: 0.0417

137/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0037 - mae: 0.0416

138/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0037 - mae: 0.0416

139/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0037 - mae: 0.0416

140/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0037 - mae: 0.0415

141/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0037 - mae: 0.0414

142/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0037 - mae: 0.0414

143/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0037 - mae: 0.0413

144/367 ━━━━━━━━━━━━━━━━━━━━ 14s 63ms/step - loss: 0.0037 - mae: 0.0413

145/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0413

146/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0412

147/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0412

148/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0413

149/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0413

150/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0413

151/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0413

152/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0413

153/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0412

154/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0412

155/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0413

156/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0414

157/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0413

158/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0412

159/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0412

160/367 ━━━━━━━━━━━━━━━━━━━━ 13s 63ms/step - loss: 0.0037 - mae: 0.0412

161/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0411

162/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0411

163/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0411

164/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0411

165/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0411

166/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0411

167/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0411

168/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0410

169/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0036 - mae: 0.0410

170/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0036 - mae: 0.0410

171/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0036 - mae: 0.0410

172/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0411

173/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0036 - mae: 0.0410

174/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0036 - mae: 0.0410

175/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0036 - mae: 0.0410

176/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0410

177/367 ━━━━━━━━━━━━━━━━━━━━ 12s 63ms/step - loss: 0.0037 - mae: 0.0411

178/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0411

179/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0411

180/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0410

181/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0409

182/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0410

183/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0409

184/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0409

185/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0036 - mae: 0.0409

186/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0036 - mae: 0.0408

187/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0409

188/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0409

189/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0409

190/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0410

191/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0410

192/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0409

193/367 ━━━━━━━━━━━━━━━━━━━━ 11s 63ms/step - loss: 0.0037 - mae: 0.0410

194/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0410

195/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0410

196/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0410

197/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0410

198/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0410

199/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0411

200/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0411

201/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0411

202/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0411

203/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0411

204/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0412

205/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0412

206/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0411

207/367 ━━━━━━━━━━━━━━━━━━━━ 10s 63ms/step - loss: 0.0037 - mae: 0.0412

209/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0412

210/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0413

211/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0412

212/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0412

213/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0412

214/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0412

215/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0411

216/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0411

217/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0411

218/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0411

219/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0411

220/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0411

221/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0411

222/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0411

223/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0411

224/367 ━━━━━━━━━━━━━━━━━━━━ 9s 63ms/step - loss: 0.0037 - mae: 0.0410

225/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0410

226/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0410

227/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0410

228/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0410

229/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0410

230/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0410

231/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0410

232/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0409

233/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0409

234/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0409

235/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0409

236/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0409

237/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0408

238/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0408

239/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0408

240/367 ━━━━━━━━━━━━━━━━━━━━ 8s 63ms/step - loss: 0.0037 - mae: 0.0407

241/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0037 - mae: 0.0407

242/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0037 - mae: 0.0407

243/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0406

244/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0407

245/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0407

246/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0406

247/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0406

248/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0405

249/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0406

250/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0405

251/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0405

252/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0405

253/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0406

254/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0406

255/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0407

256/367 ━━━━━━━━━━━━━━━━━━━━ 7s 63ms/step - loss: 0.0036 - mae: 0.0406

257/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0407

258/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0407

259/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

260/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

261/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0407

262/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

263/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

264/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

265/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

266/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

267/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

268/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

269/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

270/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

271/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

272/367 ━━━━━━━━━━━━━━━━━━━━ 6s 63ms/step - loss: 0.0036 - mae: 0.0406

273/367 ━━━━━━━━━━━━━━━━━━━━ 5s 63ms/step - loss: 0.0036 - mae: 0.0406

274/367 ━━━━━━━━━━━━━━━━━━━━ 5s 63ms/step - loss: 0.0036 - mae: 0.0406

275/367 ━━━━━━━━━━━━━━━━━━━━ 5s 63ms/step - loss: 0.0036 - mae: 0.0405

276/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0405

277/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

278/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

279/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

280/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

281/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

282/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

283/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

284/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

285/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0405

286/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

287/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

288/367 ━━━━━━━━━━━━━━━━━━━━ 5s 64ms/step - loss: 0.0036 - mae: 0.0404

289/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0404

290/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0404

291/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0404

292/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0404

293/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0403

294/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0403

295/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0035 - mae: 0.0403

296/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0035 - mae: 0.0403

297/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0035 - mae: 0.0403

298/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0035 - mae: 0.0403

299/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0035 - mae: 0.0403

300/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0403

301/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0404

302/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0403

303/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0404

304/367 ━━━━━━━━━━━━━━━━━━━━ 4s 64ms/step - loss: 0.0036 - mae: 0.0404

305/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0035 - mae: 0.0403

306/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0035 - mae: 0.0403

307/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0035 - mae: 0.0403

308/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0035 - mae: 0.0403

309/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0035 - mae: 0.0403

310/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0035 - mae: 0.0403

311/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0036 - mae: 0.0403

312/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0036 - mae: 0.0403

313/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0036 - mae: 0.0403

314/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0036 - mae: 0.0403

315/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0036 - mae: 0.0403

316/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0036 - mae: 0.0403

317/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0035 - mae: 0.0402

318/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0035 - mae: 0.0402

319/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0035 - mae: 0.0402

320/367 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 0.0035 - mae: 0.0402

321/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0402

322/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0402

323/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0401

324/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0401

325/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0401

326/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0400

327/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0400

328/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0400

329/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0400

330/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0400

331/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0400

332/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0400

333/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0400

334/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0400

335/367 ━━━━━━━━━━━━━━━━━━━━ 2s 64ms/step - loss: 0.0035 - mae: 0.0400

336/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0035 - mae: 0.0400

337/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0035 - mae: 0.0400

338/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0035 - mae: 0.0400

339/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0035 - mae: 0.0400

340/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0035 - mae: 0.0400

341/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0035 - mae: 0.0400

342/367 ━━━━━━━━━━━━━━━━━━━━ 1s 64ms/step - loss: 0.0035 - mae: 0.0400

343/367 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 0.0035 - mae: 0.0400

344/367 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 0.0035 - mae: 0.0400

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 0.0035 - mae: 0.0400

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 0.0035 - mae: 0.0400

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 0.0035 - mae: 0.0400

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 0.0035 - mae: 0.0400

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 0.0035 - mae: 0.0400

350/367 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 0.0035 - mae: 0.0400

351/367 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - loss: 0.0035 - mae: 0.0400

352/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

353/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

354/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

355/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0401

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0401

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

366/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0400

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0035 - mae: 0.0399

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 26s 71ms/step - loss: 0.0035 - mae: 0.0399 - val_loss: 0.0031 - val_mae: 0.0383 - learning_rate: 1.0000e-04

Epoch 6/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 34s 94ms/step - loss: 0.0029 - mae: 0.0435

  2/367 ━━━━━━━━━━━━━━━━━━━━ 24s 66ms/step - loss: 0.0038 - mae: 0.0461

  3/367 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - loss: 0.0031 - mae: 0.0421

  4/367 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - loss: 0.0033 - mae: 0.0417

  5/367 ━━━━━━━━━━━━━━━━━━━━ 22s 63ms/step - loss: 0.0029 - mae: 0.0389

  6/367 ━━━━━━━━━━━━━━━━━━━━ 22s 64ms/step - loss: 0.0028 - mae: 0.0379

  7/367 ━━━━━━━━━━━━━━━━━━━━ 24s 67ms/step - loss: 0.0028 - mae: 0.0377

  8/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0029 - mae: 0.0385

  9/367 ━━━━━━━━━━━━━━━━━━━━ 24s 68ms/step - loss: 0.0028 - mae: 0.0385

 10/367 ━━━━━━━━━━━━━━━━━━━━ 24s 68ms/step - loss: 0.0027 - mae: 0.0378

 11/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0026 - mae: 0.0372

 12/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0029 - mae: 0.0382

 13/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0029 - mae: 0.0385

 14/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0030 - mae: 0.0390

 15/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0030 - mae: 0.0395

 16/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0030 - mae: 0.0390

 17/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0031 - mae: 0.0395

 18/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0030 - mae: 0.0391

 19/367 ━━━━━━━━━━━━━━━━━━━━ 22s 66ms/step - loss: 0.0029 - mae: 0.0387

 20/367 ━━━━━━━━━━━━━━━━━━━━ 22s 66ms/step - loss: 0.0028 - mae: 0.0382

 21/367 ━━━━━━━━━━━━━━━━━━━━ 22s 66ms/step - loss: 0.0028 - mae: 0.0381

 22/367 ━━━━━━━━━━━━━━━━━━━━ 22s 66ms/step - loss: 0.0028 - mae: 0.0380

 23/367 ━━━━━━━━━━━━━━━━━━━━ 22s 66ms/step - loss: 0.0028 - mae: 0.0378

 24/367 ━━━━━━━━━━━━━━━━━━━━ 22s 66ms/step - loss: 0.0029 - mae: 0.0384

 25/367 ━━━━━━━━━━━━━━━━━━━━ 22s 66ms/step - loss: 0.0029 - mae: 0.0386

 26/367 ━━━━━━━━━━━━━━━━━━━━ 22s 67ms/step - loss: 0.0029 - mae: 0.0385

 27/367 ━━━━━━━━━━━━━━━━━━━━ 22s 67ms/step - loss: 0.0029 - mae: 0.0384

 28/367 ━━━━━━━━━━━━━━━━━━━━ 22s 67ms/step - loss: 0.0029 - mae: 0.0387

 29/367 ━━━━━━━━━━━━━━━━━━━━ 22s 67ms/step - loss: 0.0029 - mae: 0.0388

 30/367 ━━━━━━━━━━━━━━━━━━━━ 22s 67ms/step - loss: 0.0032 - mae: 0.0393

 31/367 ━━━━━━━━━━━━━━━━━━━━ 22s 67ms/step - loss: 0.0031 - mae: 0.0391

 32/367 ━━━━━━━━━━━━━━━━━━━━ 22s 67ms/step - loss: 0.0031 - mae: 0.0389

 33/367 ━━━━━━━━━━━━━━━━━━━━ 22s 67ms/step - loss: 0.0031 - mae: 0.0389

 34/367 ━━━━━━━━━━━━━━━━━━━━ 22s 67ms/step - loss: 0.0031 - mae: 0.0388

 35/367 ━━━━━━━━━━━━━━━━━━━━ 22s 67ms/step - loss: 0.0031 - mae: 0.0390

 36/367 ━━━━━━━━━━━━━━━━━━━━ 22s 68ms/step - loss: 0.0031 - mae: 0.0388

 37/367 ━━━━━━━━━━━━━━━━━━━━ 22s 68ms/step - loss: 0.0031 - mae: 0.0385

 38/367 ━━━━━━━━━━━━━━━━━━━━ 22s 68ms/step - loss: 0.0032 - mae: 0.0389

 39/367 ━━━━━━━━━━━━━━━━━━━━ 22s 69ms/step - loss: 0.0031 - mae: 0.0387

 40/367 ━━━━━━━━━━━━━━━━━━━━ 22s 70ms/step - loss: 0.0031 - mae: 0.0386

 41/367 ━━━━━━━━━━━━━━━━━━━━ 22s 69ms/step - loss: 0.0031 - mae: 0.0384

 42/367 ━━━━━━━━━━━━━━━━━━━━ 22s 70ms/step - loss: 0.0031 - mae: 0.0383

 43/367 ━━━━━━━━━━━━━━━━━━━━ 22s 70ms/step - loss: 0.0031 - mae: 0.0383

 44/367 ━━━━━━━━━━━━━━━━━━━━ 22s 70ms/step - loss: 0.0031 - mae: 0.0381

 45/367 ━━━━━━━━━━━━━━━━━━━━ 22s 71ms/step - loss: 0.0031 - mae: 0.0381

 46/367 ━━━━━━━━━━━━━━━━━━━━ 22s 71ms/step - loss: 0.0031 - mae: 0.0384

 47/367 ━━━━━━━━━━━━━━━━━━━━ 22s 71ms/step - loss: 0.0031 - mae: 0.0382

 48/367 ━━━━━━━━━━━━━━━━━━━━ 22s 71ms/step - loss: 0.0031 - mae: 0.0381

 49/367 ━━━━━━━━━━━━━━━━━━━━ 22s 71ms/step - loss: 0.0031 - mae: 0.0383

 50/367 ━━━━━━━━━━━━━━━━━━━━ 22s 71ms/step - loss: 0.0031 - mae: 0.0385

 51/367 ━━━━━━━━━━━━━━━━━━━━ 22s 71ms/step - loss: 0.0031 - mae: 0.0384

 52/367 ━━━━━━━━━━━━━━━━━━━━ 22s 71ms/step - loss: 0.0031 - mae: 0.0384

 53/367 ━━━━━━━━━━━━━━━━━━━━ 22s 71ms/step - loss: 0.0031 - mae: 0.0384

 54/367 ━━━━━━━━━━━━━━━━━━━━ 22s 72ms/step - loss: 0.0031 - mae: 0.0385

 55/367 ━━━━━━━━━━━━━━━━━━━━ 22s 72ms/step - loss: 0.0031 - mae: 0.0383

 56/367 ━━━━━━━━━━━━━━━━━━━━ 22s 72ms/step - loss: 0.0031 - mae: 0.0384

 57/367 ━━━━━━━━━━━━━━━━━━━━ 22s 72ms/step - loss: 0.0031 - mae: 0.0383

 58/367 ━━━━━━━━━━━━━━━━━━━━ 22s 72ms/step - loss: 0.0031 - mae: 0.0382

 59/367 ━━━━━━━━━━━━━━━━━━━━ 22s 72ms/step - loss: 0.0031 - mae: 0.0380

 60/367 ━━━━━━━━━━━━━━━━━━━━ 22s 72ms/step - loss: 0.0030 - mae: 0.0380

 61/367 ━━━━━━━━━━━━━━━━━━━━ 22s 72ms/step - loss: 0.0030 - mae: 0.0379

 62/367 ━━━━━━━━━━━━━━━━━━━━ 22s 72ms/step - loss: 0.0031 - mae: 0.0380

 63/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0031 - mae: 0.0379

 64/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0030 - mae: 0.0379

 65/367 ━━━━━━━━━━━━━━━━━━━━ 21s 73ms/step - loss: 0.0030 - mae: 0.0377

 66/367 ━━━━━━━━━━━━━━━━━━━━ 21s 73ms/step - loss: 0.0030 - mae: 0.0375

 67/367 ━━━━━━━━━━━━━━━━━━━━ 21s 73ms/step - loss: 0.0030 - mae: 0.0373

 68/367 ━━━━━━━━━━━━━━━━━━━━ 21s 73ms/step - loss: 0.0029 - mae: 0.0372

 69/367 ━━━━━━━━━━━━━━━━━━━━ 21s 73ms/step - loss: 0.0030 - mae: 0.0373

 70/367 ━━━━━━━━━━━━━━━━━━━━ 21s 73ms/step - loss: 0.0029 - mae: 0.0371

 71/367 ━━━━━━━━━━━━━━━━━━━━ 21s 73ms/step - loss: 0.0029 - mae: 0.0371

 72/367 ━━━━━━━━━━━━━━━━━━━━ 21s 73ms/step - loss: 0.0029 - mae: 0.0368

 73/367 ━━━━━━━━━━━━━━━━━━━━ 21s 73ms/step - loss: 0.0029 - mae: 0.0368

 74/367 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - loss: 0.0029 - mae: 0.0367

 75/367 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - loss: 0.0029 - mae: 0.0367

 76/367 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - loss: 0.0029 - mae: 0.0369

 77/367 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - loss: 0.0029 - mae: 0.0368

 78/367 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - loss: 0.0029 - mae: 0.0367

 79/367 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - loss: 0.0029 - mae: 0.0367

 80/367 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - loss: 0.0029 - mae: 0.0366

 81/367 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - loss: 0.0029 - mae: 0.0366

 82/367 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - loss: 0.0029 - mae: 0.0365

 83/367 ━━━━━━━━━━━━━━━━━━━━ 21s 74ms/step - loss: 0.0029 - mae: 0.0365

 84/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0029 - mae: 0.0365

 85/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0028 - mae: 0.0364

 86/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0028 - mae: 0.0364

 87/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0028 - mae: 0.0365

 88/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0029 - mae: 0.0366

 89/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0029 - mae: 0.0366

 90/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0028 - mae: 0.0365

 91/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0028 - mae: 0.0365

 92/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0029 - mae: 0.0366

 93/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0028 - mae: 0.0364

 94/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0029 - mae: 0.0365

 95/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0029 - mae: 0.0364

 96/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0028 - mae: 0.0364

 97/367 ━━━━━━━━━━━━━━━━━━━━ 20s 74ms/step - loss: 0.0028 - mae: 0.0363

 98/367 ━━━━━━━━━━━━━━━━━━━━ 20s 75ms/step - loss: 0.0028 - mae: 0.0363

 99/367 ━━━━━━━━━━━━━━━━━━━━ 19s 74ms/step - loss: 0.0029 - mae: 0.0364

100/367 ━━━━━━━━━━━━━━━━━━━━ 19s 74ms/step - loss: 0.0029 - mae: 0.0364

101/367 ━━━━━━━━━━━━━━━━━━━━ 19s 74ms/step - loss: 0.0029 - mae: 0.0364

102/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0029 - mae: 0.0363

103/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0363

104/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0362

105/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0362

106/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0361

107/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0362

108/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0362

109/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0362

110/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0361

111/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0362

112/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0362

113/367 ━━━━━━━━━━━━━━━━━━━━ 19s 75ms/step - loss: 0.0028 - mae: 0.0362

114/367 ━━━━━━━━━━━━━━━━━━━━ 18s 75ms/step - loss: 0.0028 - mae: 0.0362

115/367 ━━━━━━━━━━━━━━━━━━━━ 18s 75ms/step - loss: 0.0028 - mae: 0.0362

116/367 ━━━━━━━━━━━━━━━━━━━━ 18s 75ms/step - loss: 0.0028 - mae: 0.0362

117/367 ━━━━━━━━━━━━━━━━━━━━ 18s 75ms/step - loss: 0.0028 - mae: 0.0363

118/367 ━━━━━━━━━━━━━━━━━━━━ 18s 75ms/step - loss: 0.0028 - mae: 0.0363

119/367 ━━━━━━━━━━━━━━━━━━━━ 18s 75ms/step - loss: 0.0028 - mae: 0.0362

120/367 ━━━━━━━━━━━━━━━━━━━━ 18s 75ms/step - loss: 0.0028 - mae: 0.0362

121/367 ━━━━━━━━━━━━━━━━━━━━ 18s 76ms/step - loss: 0.0028 - mae: 0.0362

122/367 ━━━━━━━━━━━━━━━━━━━━ 18s 76ms/step - loss: 0.0028 - mae: 0.0362

123/367 ━━━━━━━━━━━━━━━━━━━━ 18s 75ms/step - loss: 0.0028 - mae: 0.0362

124/367 ━━━━━━━━━━━━━━━━━━━━ 18s 75ms/step - loss: 0.0029 - mae: 0.0362

125/367 ━━━━━━━━━━━━━━━━━━━━ 18s 76ms/step - loss: 0.0029 - mae: 0.0362

126/367 ━━━━━━━━━━━━━━━━━━━━ 18s 76ms/step - loss: 0.0029 - mae: 0.0362

127/367 ━━━━━━━━━━━━━━━━━━━━ 18s 76ms/step - loss: 0.0028 - mae: 0.0361

128/367 ━━━━━━━━━━━━━━━━━━━━ 18s 76ms/step - loss: 0.0028 - mae: 0.0360

129/367 ━━━━━━━━━━━━━━━━━━━━ 18s 76ms/step - loss: 0.0028 - mae: 0.0360

130/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0028 - mae: 0.0361

131/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0028 - mae: 0.0360

132/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0028 - mae: 0.0360

133/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0029 - mae: 0.0362

134/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0029 - mae: 0.0362

135/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0028 - mae: 0.0362

136/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0028 - mae: 0.0362

137/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0028 - mae: 0.0362

138/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0028 - mae: 0.0361

139/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0028 - mae: 0.0362

140/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0029 - mae: 0.0362

141/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0029 - mae: 0.0362

142/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0029 - mae: 0.0362

143/367 ━━━━━━━━━━━━━━━━━━━━ 17s 76ms/step - loss: 0.0029 - mae: 0.0362

144/367 ━━━━━━━━━━━━━━━━━━━━ 16s 76ms/step - loss: 0.0029 - mae: 0.0363

145/367 ━━━━━━━━━━━━━━━━━━━━ 16s 76ms/step - loss: 0.0029 - mae: 0.0363

146/367 ━━━━━━━━━━━━━━━━━━━━ 16s 76ms/step - loss: 0.0029 - mae: 0.0363

147/367 ━━━━━━━━━━━━━━━━━━━━ 16s 76ms/step - loss: 0.0029 - mae: 0.0363

148/367 ━━━━━━━━━━━━━━━━━━━━ 16s 76ms/step - loss: 0.0029 - mae: 0.0363

149/367 ━━━━━━━━━━━━━━━━━━━━ 16s 76ms/step - loss: 0.0029 - mae: 0.0363

150/367 ━━━━━━━━━━━━━━━━━━━━ 16s 76ms/step - loss: 0.0029 - mae: 0.0363

151/367 ━━━━━━━━━━━━━━━━━━━━ 16s 76ms/step - loss: 0.0029 - mae: 0.0362

152/367 ━━━━━━━━━━━━━━━━━━━━ 16s 76ms/step - loss: 0.0028 - mae: 0.0362

153/367 ━━━━━━━━━━━━━━━━━━━━ 16s 77ms/step - loss: 0.0028 - mae: 0.0362

154/367 ━━━━━━━━━━━━━━━━━━━━ 16s 77ms/step - loss: 0.0028 - mae: 0.0361

155/367 ━━━━━━━━━━━━━━━━━━━━ 16s 77ms/step - loss: 0.0028 - mae: 0.0361

156/367 ━━━━━━━━━━━━━━━━━━━━ 16s 77ms/step - loss: 0.0028 - mae: 0.0361

157/367 ━━━━━━━━━━━━━━━━━━━━ 16s 77ms/step - loss: 0.0028 - mae: 0.0361

158/367 ━━━━━━━━━━━━━━━━━━━━ 16s 77ms/step - loss: 0.0028 - mae: 0.0361

159/367 ━━━━━━━━━━━━━━━━━━━━ 16s 77ms/step - loss: 0.0028 - mae: 0.0361

160/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0028 - mae: 0.0360

161/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0028 - mae: 0.0361

162/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0028 - mae: 0.0360

163/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0028 - mae: 0.0361

164/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0028 - mae: 0.0361

165/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0028 - mae: 0.0361

166/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0028 - mae: 0.0361

167/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0028 - mae: 0.0361

168/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0029 - mae: 0.0361

169/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0029 - mae: 0.0361

170/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0029 - mae: 0.0361

171/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0028 - mae: 0.0360

172/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0028 - mae: 0.0361

173/367 ━━━━━━━━━━━━━━━━━━━━ 15s 77ms/step - loss: 0.0029 - mae: 0.0361

174/367 ━━━━━━━━━━━━━━━━━━━━ 14s 77ms/step - loss: 0.0028 - mae: 0.0361

175/367 ━━━━━━━━━━━━━━━━━━━━ 14s 77ms/step - loss: 0.0029 - mae: 0.0361

176/367 ━━━━━━━━━━━━━━━━━━━━ 14s 77ms/step - loss: 0.0029 - mae: 0.0361

177/367 ━━━━━━━━━━━━━━━━━━━━ 14s 77ms/step - loss: 0.0029 - mae: 0.0361

178/367 ━━━━━━━━━━━━━━━━━━━━ 14s 77ms/step - loss: 0.0029 - mae: 0.0362

179/367 ━━━━━━━━━━━━━━━━━━━━ 14s 77ms/step - loss: 0.0029 - mae: 0.0361

180/367 ━━━━━━━━━━━━━━━━━━━━ 14s 77ms/step - loss: 0.0028 - mae: 0.0361

181/367 ━━━━━━━━━━━━━━━━━━━━ 14s 77ms/step - loss: 0.0029 - mae: 0.0361

182/367 ━━━━━━━━━━━━━━━━━━━━ 14s 77ms/step - loss: 0.0028 - mae: 0.0361

183/367 ━━━━━━━━━━━━━━━━━━━━ 14s 78ms/step - loss: 0.0028 - mae: 0.0361

184/367 ━━━━━━━━━━━━━━━━━━━━ 14s 78ms/step - loss: 0.0028 - mae: 0.0361

185/367 ━━━━━━━━━━━━━━━━━━━━ 14s 78ms/step - loss: 0.0028 - mae: 0.0361

186/367 ━━━━━━━━━━━━━━━━━━━━ 14s 78ms/step - loss: 0.0028 - mae: 0.0361

187/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0028 - mae: 0.0361

188/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0028 - mae: 0.0361

189/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0028 - mae: 0.0360

190/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0028 - mae: 0.0360

191/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0028 - mae: 0.0361

192/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0029 - mae: 0.0361

193/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0028 - mae: 0.0361

194/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0029 - mae: 0.0361

195/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0029 - mae: 0.0361

196/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0029 - mae: 0.0361

197/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0029 - mae: 0.0361

198/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0029 - mae: 0.0361

199/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0029 - mae: 0.0362

200/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0362

201/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0362

202/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0361

203/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0362

204/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0362

205/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0363

206/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0363

207/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0363

208/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0363

209/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0363

210/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0363

211/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0363

212/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0029 - mae: 0.0363

213/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0029 - mae: 0.0363

214/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0029 - mae: 0.0363

215/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0029 - mae: 0.0364

216/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0029 - mae: 0.0363

217/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0029 - mae: 0.0364

218/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0029 - mae: 0.0363

219/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0028 - mae: 0.0363

220/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0028 - mae: 0.0363

221/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0028 - mae: 0.0363

222/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0028 - mae: 0.0363

223/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0029 - mae: 0.0363

224/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0029 - mae: 0.0363

225/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0028 - mae: 0.0363

226/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0028 - mae: 0.0362

227/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0028 - mae: 0.0363

228/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0029 - mae: 0.0363

229/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0029 - mae: 0.0363

230/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0029 - mae: 0.0363

231/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0029 - mae: 0.0363

232/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0028 - mae: 0.0363

233/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0028 - mae: 0.0362

234/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0028 - mae: 0.0362

235/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0028 - mae: 0.0362

236/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0028 - mae: 0.0362

238/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0028 - mae: 0.0362

239/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0028 - mae: 0.0362

240/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0028 - mae: 0.0362

241/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0028 - mae: 0.0362

242/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0028 - mae: 0.0361

243/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0028 - mae: 0.0361

244/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0028 - mae: 0.0362

245/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0028 - mae: 0.0362

246/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0028 - mae: 0.0362

247/367 ━━━━━━━━━━━━━━━━━━━━ 9s 79ms/step - loss: 0.0028 - mae: 0.0361

248/367 ━━━━━━━━━━━━━━━━━━━━ 9s 79ms/step - loss: 0.0028 - mae: 0.0361

249/367 ━━━━━━━━━━━━━━━━━━━━ 9s 79ms/step - loss: 0.0028 - mae: 0.0361

250/367 ━━━━━━━━━━━━━━━━━━━━ 9s 79ms/step - loss: 0.0028 - mae: 0.0360

251/367 ━━━━━━━━━━━━━━━━━━━━ 9s 79ms/step - loss: 0.0028 - mae: 0.0360

252/367 ━━━━━━━━━━━━━━━━━━━━ 9s 79ms/step - loss: 0.0028 - mae: 0.0360

253/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

254/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

255/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

256/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

257/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

258/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

259/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

260/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

261/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

262/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

263/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

264/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

265/367 ━━━━━━━━━━━━━━━━━━━━ 8s 79ms/step - loss: 0.0028 - mae: 0.0360

266/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

267/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0359

268/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

269/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

270/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

271/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

272/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

273/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

274/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

275/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

276/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

277/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

278/367 ━━━━━━━━━━━━━━━━━━━━ 7s 79ms/step - loss: 0.0028 - mae: 0.0360

279/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

280/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

281/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

282/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

283/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

284/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

285/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

286/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

287/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

288/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

289/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

290/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

291/367 ━━━━━━━━━━━━━━━━━━━━ 6s 79ms/step - loss: 0.0028 - mae: 0.0360

292/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0360

293/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0360

294/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0360

295/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0360

296/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0359

297/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0359

298/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0359

299/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0359

300/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0359

301/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0359

302/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0359

303/367 ━━━━━━━━━━━━━━━━━━━━ 5s 79ms/step - loss: 0.0028 - mae: 0.0358

304/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

305/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0359

306/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

307/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

308/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

309/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

310/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0027 - mae: 0.0358

311/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

312/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

313/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

314/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

315/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

316/367 ━━━━━━━━━━━━━━━━━━━━ 4s 79ms/step - loss: 0.0028 - mae: 0.0358

317/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0028 - mae: 0.0358

318/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0358

319/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0357

320/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0358

321/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0357

322/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0357

323/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0357

324/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0357

325/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0357

326/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0357

327/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0356

328/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0357

329/367 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 0.0027 - mae: 0.0357

330/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0356

331/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0356

332/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0356

333/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0356

334/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0356

335/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0355

336/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0355

337/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0355

338/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0355

339/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0355

340/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0355

341/367 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - loss: 0.0027 - mae: 0.0355

342/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0354

343/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0354

344/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0354

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0354

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0354

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0354

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0354

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0354

350/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0354

351/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0353

352/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0353

353/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0353

354/367 ━━━━━━━━━━━━━━━━━━━━ 1s 79ms/step - loss: 0.0027 - mae: 0.0353

355/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0353

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0353

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0353

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0353

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0352

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0352

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0352

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0352

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0352

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0352

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0352

366/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0352

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0027 - mae: 0.0352

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 32s 86ms/step - loss: 0.0027 - mae: 0.0352 - val_loss: 0.0022 - val_mae: 0.0302 - learning_rate: 1.0000e-04

Epoch 7/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 38s 105ms/step - loss: 0.0015 - mae: 0.0275

  2/367 ━━━━━━━━━━━━━━━━━━━━ 22s 62ms/step - loss: 0.0018 - mae: 0.0311

  3/367 ━━━━━━━━━━━━━━━━━━━━ 22s 61ms/step - loss: 0.0024 - mae: 0.0320

  4/367 ━━━━━━━━━━━━━━━━━━━━ 22s 61ms/step - loss: 0.0024 - mae: 0.0324

  5/367 ━━━━━━━━━━━━━━━━━━━━ 22s 63ms/step - loss: 0.0021 - mae: 0.0302

  6/367 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - loss: 0.0023 - mae: 0.0313

  7/367 ━━━━━━━━━━━━━━━━━━━━ 23s 65ms/step - loss: 0.0024 - mae: 0.0319

  8/367 ━━━━━━━━━━━━━━━━━━━━ 23s 65ms/step - loss: 0.0022 - mae: 0.0303

  9/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0022 - mae: 0.0302

 10/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0022 - mae: 0.0303

 11/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0022 - mae: 0.0305

 12/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0023 - mae: 0.0311

 13/367 ━━━━━━━━━━━━━━━━━━━━ 24s 68ms/step - loss: 0.0023 - mae: 0.0317

 14/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0024 - mae: 0.0319

 15/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0023 - mae: 0.0311

 16/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0022 - mae: 0.0311

 17/367 ━━━━━━━━━━━━━━━━━━━━ 24s 70ms/step - loss: 0.0022 - mae: 0.0312

 18/367 ━━━━━━━━━━━━━━━━━━━━ 24s 70ms/step - loss: 0.0022 - mae: 0.0310

 19/367 ━━━━━━━━━━━━━━━━━━━━ 24s 71ms/step - loss: 0.0022 - mae: 0.0313

 20/367 ━━━━━━━━━━━━━━━━━━━━ 24s 72ms/step - loss: 0.0022 - mae: 0.0313

 21/367 ━━━━━━━━━━━━━━━━━━━━ 24s 71ms/step - loss: 0.0021 - mae: 0.0311

 22/367 ━━━━━━━━━━━━━━━━━━━━ 24s 71ms/step - loss: 0.0021 - mae: 0.0312

 23/367 ━━━━━━━━━━━━━━━━━━━━ 24s 72ms/step - loss: 0.0021 - mae: 0.0310

 24/367 ━━━━━━━━━━━━━━━━━━━━ 25s 73ms/step - loss: 0.0023 - mae: 0.0313

 25/367 ━━━━━━━━━━━━━━━━━━━━ 24s 73ms/step - loss: 0.0023 - mae: 0.0315

 26/367 ━━━━━━━━━━━━━━━━━━━━ 24s 73ms/step - loss: 0.0022 - mae: 0.0313

 27/367 ━━━━━━━━━━━━━━━━━━━━ 24s 73ms/step - loss: 0.0023 - mae: 0.0319

 28/367 ━━━━━━━━━━━━━━━━━━━━ 24s 73ms/step - loss: 0.0023 - mae: 0.0320

 29/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0023 - mae: 0.0322

 30/367 ━━━━━━━━━━━━━━━━━━━━ 25s 74ms/step - loss: 0.0024 - mae: 0.0326

 31/367 ━━━━━━━━━━━━━━━━━━━━ 25s 74ms/step - loss: 0.0024 - mae: 0.0327

 32/367 ━━━━━━━━━━━━━━━━━━━━ 25s 75ms/step - loss: 0.0024 - mae: 0.0328

 33/367 ━━━━━━━━━━━━━━━━━━━━ 25s 75ms/step - loss: 0.0024 - mae: 0.0327

 34/367 ━━━━━━━━━━━━━━━━━━━━ 25s 76ms/step - loss: 0.0023 - mae: 0.0323

 35/367 ━━━━━━━━━━━━━━━━━━━━ 25s 77ms/step - loss: 0.0023 - mae: 0.0322

 36/367 ━━━━━━━━━━━━━━━━━━━━ 25s 78ms/step - loss: 0.0023 - mae: 0.0321

 37/367 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - loss: 0.0023 - mae: 0.0321

 38/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0023 - mae: 0.0321

 39/367 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - loss: 0.0023 - mae: 0.0322

 40/367 ━━━━━━━━━━━━━━━━━━━━ 26s 81ms/step - loss: 0.0023 - mae: 0.0323

 41/367 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - loss: 0.0023 - mae: 0.0323

 42/367 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - loss: 0.0023 - mae: 0.0324

 43/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0023 - mae: 0.0326

 44/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0023 - mae: 0.0324

 45/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0023 - mae: 0.0323

 46/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0023 - mae: 0.0324

 47/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0023 - mae: 0.0325

 48/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0024 - mae: 0.0327

 49/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0024 - mae: 0.0328

 50/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0024 - mae: 0.0330

 51/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0024 - mae: 0.0330

 52/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0024 - mae: 0.0330

 53/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0024 - mae: 0.0330

 54/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0024 - mae: 0.0329

 55/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0024 - mae: 0.0329

 56/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0024 - mae: 0.0332

 57/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0024 - mae: 0.0333

 58/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0024 - mae: 0.0335

 59/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0024 - mae: 0.0334

 60/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0024 - mae: 0.0334

 61/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0024 - mae: 0.0334

 62/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0024 - mae: 0.0334

 63/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0334

 64/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0336

 65/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0336

 66/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0338

 67/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0336

 68/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0336

 69/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0337

 70/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0337

 71/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0337

 72/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0337

 73/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0024 - mae: 0.0337

 74/367 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - loss: 0.0024 - mae: 0.0336

 75/367 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - loss: 0.0024 - mae: 0.0336

 76/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0337

 77/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0337

 78/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0339

 79/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0338

 80/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0339

 81/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0025 - mae: 0.0340

 82/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0339

 83/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0339

 84/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0339

 85/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0339

 86/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0338

 87/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0338

 88/367 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - loss: 0.0024 - mae: 0.0338

 89/367 ━━━━━━━━━━━━━━━━━━━━ 24s 87ms/step - loss: 0.0024 - mae: 0.0337

 90/367 ━━━━━━━━━━━━━━━━━━━━ 24s 87ms/step - loss: 0.0024 - mae: 0.0337

 91/367 ━━━━━━━━━━━━━━━━━━━━ 24s 87ms/step - loss: 0.0024 - mae: 0.0336

 92/367 ━━━━━━━━━━━━━━━━━━━━ 23s 87ms/step - loss: 0.0024 - mae: 0.0335

 93/367 ━━━━━━━━━━━━━━━━━━━━ 23s 87ms/step - loss: 0.0024 - mae: 0.0335

 94/367 ━━━━━━━━━━━━━━━━━━━━ 23s 87ms/step - loss: 0.0024 - mae: 0.0335

 95/367 ━━━━━━━━━━━━━━━━━━━━ 23s 87ms/step - loss: 0.0024 - mae: 0.0335

 96/367 ━━━━━━━━━━━━━━━━━━━━ 23s 87ms/step - loss: 0.0024 - mae: 0.0335

 97/367 ━━━━━━━━━━━━━━━━━━━━ 23s 87ms/step - loss: 0.0024 - mae: 0.0335

 98/367 ━━━━━━━━━━━━━━━━━━━━ 23s 87ms/step - loss: 0.0023 - mae: 0.0334

 99/367 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - loss: 0.0023 - mae: 0.0333

100/367 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - loss: 0.0023 - mae: 0.0333

101/367 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - loss: 0.0023 - mae: 0.0332

102/367 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - loss: 0.0023 - mae: 0.0333

103/367 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - loss: 0.0023 - mae: 0.0333

104/367 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - loss: 0.0023 - mae: 0.0332

105/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0332

106/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0332

107/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0331

108/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0332

109/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0332

110/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0332

111/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0332

112/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0331

113/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0331

114/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0330

115/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0329

116/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0023 - mae: 0.0328

117/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0023 - mae: 0.0328

118/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0023 - mae: 0.0328

119/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0022 - mae: 0.0328

120/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0023 - mae: 0.0327

121/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0023 - mae: 0.0327

122/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0023 - mae: 0.0328

123/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0023 - mae: 0.0328

124/367 ━━━━━━━━━━━━━━━━━━━━ 21s 89ms/step - loss: 0.0023 - mae: 0.0328

125/367 ━━━━━━━━━━━━━━━━━━━━ 21s 89ms/step - loss: 0.0023 - mae: 0.0327

126/367 ━━━━━━━━━━━━━━━━━━━━ 21s 89ms/step - loss: 0.0023 - mae: 0.0328

127/367 ━━━━━━━━━━━━━━━━━━━━ 21s 89ms/step - loss: 0.0023 - mae: 0.0328

128/367 ━━━━━━━━━━━━━━━━━━━━ 21s 89ms/step - loss: 0.0023 - mae: 0.0327

129/367 ━━━━━━━━━━━━━━━━━━━━ 21s 90ms/step - loss: 0.0023 - mae: 0.0326

130/367 ━━━━━━━━━━━━━━━━━━━━ 21s 90ms/step - loss: 0.0023 - mae: 0.0327

131/367 ━━━━━━━━━━━━━━━━━━━━ 21s 90ms/step - loss: 0.0023 - mae: 0.0327

132/367 ━━━━━━━━━━━━━━━━━━━━ 21s 90ms/step - loss: 0.0023 - mae: 0.0326

133/367 ━━━━━━━━━━━━━━━━━━━━ 21s 90ms/step - loss: 0.0023 - mae: 0.0327

134/367 ━━━━━━━━━━━━━━━━━━━━ 20s 90ms/step - loss: 0.0023 - mae: 0.0327

135/367 ━━━━━━━━━━━━━━━━━━━━ 20s 90ms/step - loss: 0.0023 - mae: 0.0327

136/367 ━━━━━━━━━━━━━━━━━━━━ 20s 90ms/step - loss: 0.0023 - mae: 0.0326

137/367 ━━━━━━━━━━━━━━━━━━━━ 20s 90ms/step - loss: 0.0022 - mae: 0.0326

138/367 ━━━━━━━━━━━━━━━━━━━━ 20s 90ms/step - loss: 0.0022 - mae: 0.0326

139/367 ━━━━━━━━━━━━━━━━━━━━ 20s 90ms/step - loss: 0.0022 - mae: 0.0326

140/367 ━━━━━━━━━━━━━━━━━━━━ 20s 91ms/step - loss: 0.0022 - mae: 0.0326

141/367 ━━━━━━━━━━━━━━━━━━━━ 20s 91ms/step - loss: 0.0022 - mae: 0.0325

142/367 ━━━━━━━━━━━━━━━━━━━━ 20s 91ms/step - loss: 0.0022 - mae: 0.0325

143/367 ━━━━━━━━━━━━━━━━━━━━ 20s 91ms/step - loss: 0.0022 - mae: 0.0326

144/367 ━━━━━━━━━━━━━━━━━━━━ 20s 91ms/step - loss: 0.0023 - mae: 0.0326

145/367 ━━━━━━━━━━━━━━━━━━━━ 20s 91ms/step - loss: 0.0023 - mae: 0.0326

146/367 ━━━━━━━━━━━━━━━━━━━━ 20s 91ms/step - loss: 0.0023 - mae: 0.0326

147/367 ━━━━━━━━━━━━━━━━━━━━ 19s 91ms/step - loss: 0.0022 - mae: 0.0325

148/367 ━━━━━━━━━━━━━━━━━━━━ 19s 90ms/step - loss: 0.0022 - mae: 0.0325

149/367 ━━━━━━━━━━━━━━━━━━━━ 19s 90ms/step - loss: 0.0022 - mae: 0.0325

150/367 ━━━━━━━━━━━━━━━━━━━━ 19s 90ms/step - loss: 0.0022 - mae: 0.0324

151/367 ━━━━━━━━━━━━━━━━━━━━ 19s 90ms/step - loss: 0.0022 - mae: 0.0324

152/367 ━━━━━━━━━━━━━━━━━━━━ 19s 90ms/step - loss: 0.0022 - mae: 0.0324

153/367 ━━━━━━━━━━━━━━━━━━━━ 19s 91ms/step - loss: 0.0023 - mae: 0.0325

154/367 ━━━━━━━━━━━━━━━━━━━━ 19s 91ms/step - loss: 0.0023 - mae: 0.0325

155/367 ━━━━━━━━━━━━━━━━━━━━ 19s 91ms/step - loss: 0.0023 - mae: 0.0326

156/367 ━━━━━━━━━━━━━━━━━━━━ 19s 91ms/step - loss: 0.0023 - mae: 0.0326

157/367 ━━━━━━━━━━━━━━━━━━━━ 19s 92ms/step - loss: 0.0023 - mae: 0.0325

158/367 ━━━━━━━━━━━━━━━━━━━━ 19s 92ms/step - loss: 0.0023 - mae: 0.0325

159/367 ━━━━━━━━━━━━━━━━━━━━ 19s 92ms/step - loss: 0.0023 - mae: 0.0324

160/367 ━━━━━━━━━━━━━━━━━━━━ 19s 92ms/step - loss: 0.0023 - mae: 0.0325

161/367 ━━━━━━━━━━━━━━━━━━━━ 18s 92ms/step - loss: 0.0023 - mae: 0.0324

162/367 ━━━━━━━━━━━━━━━━━━━━ 18s 92ms/step - loss: 0.0022 - mae: 0.0324

163/367 ━━━━━━━━━━━━━━━━━━━━ 18s 92ms/step - loss: 0.0022 - mae: 0.0325

164/367 ━━━━━━━━━━━━━━━━━━━━ 18s 92ms/step - loss: 0.0022 - mae: 0.0325

165/367 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - loss: 0.0023 - mae: 0.0325

166/367 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - loss: 0.0022 - mae: 0.0324

167/367 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - loss: 0.0022 - mae: 0.0323

168/367 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - loss: 0.0022 - mae: 0.0323

169/367 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - loss: 0.0022 - mae: 0.0323

170/367 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - loss: 0.0022 - mae: 0.0324

171/367 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - loss: 0.0022 - mae: 0.0324

172/367 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - loss: 0.0022 - mae: 0.0324

173/367 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - loss: 0.0022 - mae: 0.0324

174/367 ━━━━━━━━━━━━━━━━━━━━ 18s 93ms/step - loss: 0.0022 - mae: 0.0323

175/367 ━━━━━━━━━━━━━━━━━━━━ 17s 93ms/step - loss: 0.0022 - mae: 0.0323

176/367 ━━━━━━━━━━━━━━━━━━━━ 17s 93ms/step - loss: 0.0022 - mae: 0.0323

177/367 ━━━━━━━━━━━━━━━━━━━━ 17s 93ms/step - loss: 0.0022 - mae: 0.0323

178/367 ━━━━━━━━━━━━━━━━━━━━ 17s 93ms/step - loss: 0.0022 - mae: 0.0323

179/367 ━━━━━━━━━━━━━━━━━━━━ 17s 93ms/step - loss: 0.0022 - mae: 0.0323

180/367 ━━━━━━━━━━━━━━━━━━━━ 17s 93ms/step - loss: 0.0022 - mae: 0.0322

181/367 ━━━━━━━━━━━━━━━━━━━━ 17s 93ms/step - loss: 0.0022 - mae: 0.0322

182/367 ━━━━━━━━━━━━━━━━━━━━ 17s 93ms/step - loss: 0.0022 - mae: 0.0322

183/367 ━━━━━━━━━━━━━━━━━━━━ 17s 93ms/step - loss: 0.0022 - mae: 0.0322

184/367 ━━━━━━━━━━━━━━━━━━━━ 17s 94ms/step - loss: 0.0022 - mae: 0.0321

185/367 ━━━━━━━━━━━━━━━━━━━━ 17s 94ms/step - loss: 0.0022 - mae: 0.0321

186/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0322

187/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0321

188/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0321

189/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0321

190/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0321

191/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0321

192/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0321

193/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0320

194/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0320

195/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0320

196/367 ━━━━━━━━━━━━━━━━━━━━ 16s 94ms/step - loss: 0.0022 - mae: 0.0320

197/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0320

198/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0320

199/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0320

200/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0320

201/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0320

202/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0320

203/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0319

204/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0319

205/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0319

206/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0319

207/367 ━━━━━━━━━━━━━━━━━━━━ 15s 94ms/step - loss: 0.0022 - mae: 0.0319

208/367 ━━━━━━━━━━━━━━━━━━━━ 15s 95ms/step - loss: 0.0022 - mae: 0.0319

209/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0319

210/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0318

211/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0318

212/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0319

213/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0318

214/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0319

215/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0318

216/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0318

217/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0318

218/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0318

219/367 ━━━━━━━━━━━━━━━━━━━━ 14s 95ms/step - loss: 0.0022 - mae: 0.0318

220/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0319

221/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0319

222/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0319

223/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0319

224/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0319

225/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0318

226/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0318

227/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0318

228/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0318

229/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0319

230/367 ━━━━━━━━━━━━━━━━━━━━ 13s 95ms/step - loss: 0.0022 - mae: 0.0318

231/367 ━━━━━━━━━━━━━━━━━━━━ 12s 95ms/step - loss: 0.0022 - mae: 0.0318

232/367 ━━━━━━━━━━━━━━━━━━━━ 12s 95ms/step - loss: 0.0022 - mae: 0.0318

233/367 ━━━━━━━━━━━━━━━━━━━━ 12s 96ms/step - loss: 0.0022 - mae: 0.0317

234/367 ━━━━━━━━━━━━━━━━━━━━ 12s 96ms/step - loss: 0.0022 - mae: 0.0317

235/367 ━━━━━━━━━━━━━━━━━━━━ 12s 96ms/step - loss: 0.0022 - mae: 0.0317

236/367 ━━━━━━━━━━━━━━━━━━━━ 12s 96ms/step - loss: 0.0022 - mae: 0.0318

237/367 ━━━━━━━━━━━━━━━━━━━━ 12s 96ms/step - loss: 0.0022 - mae: 0.0318

238/367 ━━━━━━━━━━━━━━━━━━━━ 12s 96ms/step - loss: 0.0022 - mae: 0.0318

239/367 ━━━━━━━━━━━━━━━━━━━━ 12s 96ms/step - loss: 0.0022 - mae: 0.0318

240/367 ━━━━━━━━━━━━━━━━━━━━ 12s 96ms/step - loss: 0.0022 - mae: 0.0318

241/367 ━━━━━━━━━━━━━━━━━━━━ 12s 96ms/step - loss: 0.0022 - mae: 0.0318

242/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0318

243/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0318

244/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0318

245/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0318

246/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0318

247/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0318

248/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0318

249/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0317

250/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0317

251/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0317

252/367 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 0.0022 - mae: 0.0317

253/367 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 0.0022 - mae: 0.0317

254/367 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 0.0022 - mae: 0.0317

255/367 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 0.0022 - mae: 0.0317

256/367 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 0.0022 - mae: 0.0317

257/367 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 0.0022 - mae: 0.0317

258/367 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 0.0022 - mae: 0.0316

259/367 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 0.0022 - mae: 0.0316

260/367 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 0.0022 - mae: 0.0317

261/367 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 0.0022 - mae: 0.0317

262/367 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 0.0022 - mae: 0.0317

263/367 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - loss: 0.0022 - mae: 0.0316

264/367 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - loss: 0.0022 - mae: 0.0316

265/367 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - loss: 0.0022 - mae: 0.0316

266/367 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - loss: 0.0022 - mae: 0.0316

267/367 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - loss: 0.0022 - mae: 0.0316

268/367 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - loss: 0.0022 - mae: 0.0316

270/367 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - loss: 0.0022 - mae: 0.0315

271/367 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - loss: 0.0021 - mae: 0.0315

272/367 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - loss: 0.0021 - mae: 0.0315

273/367 ━━━━━━━━━━━━━━━━━━━━ 9s 96ms/step - loss: 0.0021 - mae: 0.0315

274/367 ━━━━━━━━━━━━━━━━━━━━ 8s 96ms/step - loss: 0.0021 - mae: 0.0315

275/367 ━━━━━━━━━━━━━━━━━━━━ 8s 96ms/step - loss: 0.0021 - mae: 0.0314

276/367 ━━━━━━━━━━━━━━━━━━━━ 8s 96ms/step - loss: 0.0021 - mae: 0.0314

277/367 ━━━━━━━━━━━━━━━━━━━━ 8s 96ms/step - loss: 0.0021 - mae: 0.0314

278/367 ━━━━━━━━━━━━━━━━━━━━ 8s 96ms/step - loss: 0.0021 - mae: 0.0314

279/367 ━━━━━━━━━━━━━━━━━━━━ 8s 96ms/step - loss: 0.0021 - mae: 0.0314

280/367 ━━━━━━━━━━━━━━━━━━━━ 8s 96ms/step - loss: 0.0021 - mae: 0.0314

281/367 ━━━━━━━━━━━━━━━━━━━━ 8s 96ms/step - loss: 0.0021 - mae: 0.0314

282/367 ━━━━━━━━━━━━━━━━━━━━ 8s 96ms/step - loss: 0.0021 - mae: 0.0314

283/367 ━━━━━━━━━━━━━━━━━━━━ 8s 96ms/step - loss: 0.0021 - mae: 0.0314

284/367 ━━━━━━━━━━━━━━━━━━━━ 7s 96ms/step - loss: 0.0021 - mae: 0.0314

285/367 ━━━━━━━━━━━━━━━━━━━━ 7s 96ms/step - loss: 0.0021 - mae: 0.0314

286/367 ━━━━━━━━━━━━━━━━━━━━ 7s 96ms/step - loss: 0.0021 - mae: 0.0314

287/367 ━━━━━━━━━━━━━━━━━━━━ 7s 96ms/step - loss: 0.0021 - mae: 0.0314

288/367 ━━━━━━━━━━━━━━━━━━━━ 7s 96ms/step - loss: 0.0021 - mae: 0.0314

289/367 ━━━━━━━━━━━━━━━━━━━━ 7s 96ms/step - loss: 0.0021 - mae: 0.0314

290/367 ━━━━━━━━━━━━━━━━━━━━ 7s 96ms/step - loss: 0.0021 - mae: 0.0314

291/367 ━━━━━━━━━━━━━━━━━━━━ 7s 97ms/step - loss: 0.0021 - mae: 0.0314

292/367 ━━━━━━━━━━━━━━━━━━━━ 7s 97ms/step - loss: 0.0021 - mae: 0.0314

293/367 ━━━━━━━━━━━━━━━━━━━━ 7s 96ms/step - loss: 0.0021 - mae: 0.0314

294/367 ━━━━━━━━━━━━━━━━━━━━ 7s 97ms/step - loss: 0.0021 - mae: 0.0313

295/367 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - loss: 0.0021 - mae: 0.0313

296/367 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - loss: 0.0021 - mae: 0.0313

297/367 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - loss: 0.0021 - mae: 0.0313

298/367 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - loss: 0.0021 - mae: 0.0313

299/367 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - loss: 0.0021 - mae: 0.0313

300/367 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - loss: 0.0021 - mae: 0.0313

301/367 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - loss: 0.0021 - mae: 0.0313

302/367 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - loss: 0.0021 - mae: 0.0313

303/367 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - loss: 0.0021 - mae: 0.0313

304/367 ━━━━━━━━━━━━━━━━━━━━ 6s 97ms/step - loss: 0.0021 - mae: 0.0313

305/367 ━━━━━━━━━━━━━━━━━━━━ 5s 97ms/step - loss: 0.0021 - mae: 0.0313

306/367 ━━━━━━━━━━━━━━━━━━━━ 5s 97ms/step - loss: 0.0021 - mae: 0.0313

307/367 ━━━━━━━━━━━━━━━━━━━━ 5s 97ms/step - loss: 0.0021 - mae: 0.0313

308/367 ━━━━━━━━━━━━━━━━━━━━ 5s 97ms/step - loss: 0.0021 - mae: 0.0313

309/367 ━━━━━━━━━━━━━━━━━━━━ 5s 97ms/step - loss: 0.0021 - mae: 0.0313

310/367 ━━━━━━━━━━━━━━━━━━━━ 5s 97ms/step - loss: 0.0021 - mae: 0.0313

311/367 ━━━━━━━━━━━━━━━━━━━━ 5s 96ms/step - loss: 0.0021 - mae: 0.0313

312/367 ━━━━━━━━━━━━━━━━━━━━ 5s 96ms/step - loss: 0.0021 - mae: 0.0313

313/367 ━━━━━━━━━━━━━━━━━━━━ 5s 96ms/step - loss: 0.0021 - mae: 0.0313

314/367 ━━━━━━━━━━━━━━━━━━━━ 5s 96ms/step - loss: 0.0021 - mae: 0.0312

315/367 ━━━━━━━━━━━━━━━━━━━━ 5s 96ms/step - loss: 0.0021 - mae: 0.0312

316/367 ━━━━━━━━━━━━━━━━━━━━ 4s 96ms/step - loss: 0.0021 - mae: 0.0312

317/367 ━━━━━━━━━━━━━━━━━━━━ 4s 96ms/step - loss: 0.0021 - mae: 0.0312

318/367 ━━━━━━━━━━━━━━━━━━━━ 4s 97ms/step - loss: 0.0021 - mae: 0.0312

319/367 ━━━━━━━━━━━━━━━━━━━━ 4s 96ms/step - loss: 0.0021 - mae: 0.0312

320/367 ━━━━━━━━━━━━━━━━━━━━ 4s 96ms/step - loss: 0.0021 - mae: 0.0312

321/367 ━━━━━━━━━━━━━━━━━━━━ 4s 97ms/step - loss: 0.0021 - mae: 0.0312

322/367 ━━━━━━━━━━━━━━━━━━━━ 4s 97ms/step - loss: 0.0021 - mae: 0.0312

323/367 ━━━━━━━━━━━━━━━━━━━━ 4s 97ms/step - loss: 0.0021 - mae: 0.0311

324/367 ━━━━━━━━━━━━━━━━━━━━ 4s 97ms/step - loss: 0.0021 - mae: 0.0311

325/367 ━━━━━━━━━━━━━━━━━━━━ 4s 97ms/step - loss: 0.0021 - mae: 0.0311

326/367 ━━━━━━━━━━━━━━━━━━━━ 3s 96ms/step - loss: 0.0021 - mae: 0.0311

327/367 ━━━━━━━━━━━━━━━━━━━━ 3s 96ms/step - loss: 0.0021 - mae: 0.0311

328/367 ━━━━━━━━━━━━━━━━━━━━ 3s 96ms/step - loss: 0.0021 - mae: 0.0311

329/367 ━━━━━━━━━━━━━━━━━━━━ 3s 97ms/step - loss: 0.0021 - mae: 0.0311

330/367 ━━━━━━━━━━━━━━━━━━━━ 3s 97ms/step - loss: 0.0021 - mae: 0.0310

331/367 ━━━━━━━━━━━━━━━━━━━━ 3s 97ms/step - loss: 0.0021 - mae: 0.0310

332/367 ━━━━━━━━━━━━━━━━━━━━ 3s 97ms/step - loss: 0.0021 - mae: 0.0310

333/367 ━━━━━━━━━━━━━━━━━━━━ 3s 97ms/step - loss: 0.0021 - mae: 0.0310

334/367 ━━━━━━━━━━━━━━━━━━━━ 3s 97ms/step - loss: 0.0021 - mae: 0.0310

335/367 ━━━━━━━━━━━━━━━━━━━━ 3s 97ms/step - loss: 0.0021 - mae: 0.0310

336/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0310

337/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0310

338/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0310

339/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0310

340/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0311

341/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0311

342/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0311

343/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0311

344/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0311

345/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0311

346/367 ━━━━━━━━━━━━━━━━━━━━ 2s 97ms/step - loss: 0.0021 - mae: 0.0311

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - loss: 0.0021 - mae: 0.0311

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - loss: 0.0021 - mae: 0.0311

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - loss: 0.0021 - mae: 0.0311

350/367 ━━━━━━━━━━━━━━━━━━━━ 1s 97ms/step - loss: 0.0021 - mae: 0.0311

351/367 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - loss: 0.0021 - mae: 0.0311

352/367 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - loss: 0.0021 - mae: 0.0311

353/367 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - loss: 0.0021 - mae: 0.0311

354/367 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - loss: 0.0021 - mae: 0.0311

355/367 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - loss: 0.0021 - mae: 0.0310

356/367 ━━━━━━━━━━━━━━━━━━━━ 1s 96ms/step - loss: 0.0021 - mae: 0.0310

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0310

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0310

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0310

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0310

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0310

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0310

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0309

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0310

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0309

366/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0309

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 0.0021 - mae: 0.0309

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 38s 102ms/step - loss: 0.0021 - mae: 0.0309 - val_loss: 0.0019 - val_mae: 0.0289 - learning_rate: 1.0000e-04

Epoch 8/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 39s 108ms/step - loss: 0.0024 - mae: 0.0304

  2/367 ━━━━━━━━━━━━━━━━━━━━ 24s 67ms/step - loss: 0.0025 - mae: 0.0325

  3/367 ━━━━━━━━━━━━━━━━━━━━ 25s 70ms/step - loss: 0.0022 - mae: 0.0314

  4/367 ━━━━━━━━━━━━━━━━━━━━ 26s 72ms/step - loss: 0.0020 - mae: 0.0292

  5/367 ━━━━━━━━━━━━━━━━━━━━ 25s 72ms/step - loss: 0.0019 - mae: 0.0285

  6/367 ━━━━━━━━━━━━━━━━━━━━ 26s 73ms/step - loss: 0.0018 - mae: 0.0286

  7/367 ━━━━━━━━━━━━━━━━━━━━ 26s 73ms/step - loss: 0.0017 - mae: 0.0281

  8/367 ━━━━━━━━━━━━━━━━━━━━ 26s 73ms/step - loss: 0.0019 - mae: 0.0297

  9/367 ━━━━━━━━━━━━━━━━━━━━ 26s 74ms/step - loss: 0.0018 - mae: 0.0286

 10/367 ━━━━━━━━━━━━━━━━━━━━ 26s 75ms/step - loss: 0.0018 - mae: 0.0293

 11/367 ━━━━━━━━━━━━━━━━━━━━ 27s 76ms/step - loss: 0.0018 - mae: 0.0289

 12/367 ━━━━━━━━━━━━━━━━━━━━ 27s 77ms/step - loss: 0.0017 - mae: 0.0287

 13/367 ━━━━━━━━━━━━━━━━━━━━ 27s 76ms/step - loss: 0.0019 - mae: 0.0289

 14/367 ━━━━━━━━━━━━━━━━━━━━ 27s 77ms/step - loss: 0.0018 - mae: 0.0287

 15/367 ━━━━━━━━━━━━━━━━━━━━ 27s 77ms/step - loss: 0.0018 - mae: 0.0287

 16/367 ━━━━━━━━━━━━━━━━━━━━ 27s 77ms/step - loss: 0.0018 - mae: 0.0289

 17/367 ━━━━━━━━━━━━━━━━━━━━ 27s 77ms/step - loss: 0.0019 - mae: 0.0288

 18/367 ━━━━━━━━━━━━━━━━━━━━ 27s 78ms/step - loss: 0.0018 - mae: 0.0284

 19/367 ━━━━━━━━━━━━━━━━━━━━ 26s 77ms/step - loss: 0.0018 - mae: 0.0284

 20/367 ━━━━━━━━━━━━━━━━━━━━ 26s 77ms/step - loss: 0.0018 - mae: 0.0281

 21/367 ━━━━━━━━━━━━━━━━━━━━ 26s 77ms/step - loss: 0.0018 - mae: 0.0280

 22/367 ━━━━━━━━━━━━━━━━━━━━ 26s 77ms/step - loss: 0.0018 - mae: 0.0279

 23/367 ━━━━━━━━━━━━━━━━━━━━ 26s 77ms/step - loss: 0.0018 - mae: 0.0281

 24/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0018 - mae: 0.0281

 25/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0018 - mae: 0.0281

 26/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0018 - mae: 0.0280

 27/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0018 - mae: 0.0281

 28/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0018 - mae: 0.0280

 29/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0018 - mae: 0.0278

 30/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0018 - mae: 0.0282

 31/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0018 - mae: 0.0282

 32/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0018 - mae: 0.0283

 33/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0019 - mae: 0.0286

 34/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0019 - mae: 0.0286

 35/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0019 - mae: 0.0287

 36/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0019 - mae: 0.0287

 37/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0019 - mae: 0.0286

 38/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0018 - mae: 0.0285

 39/367 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - loss: 0.0019 - mae: 0.0284

 40/367 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - loss: 0.0019 - mae: 0.0284

 41/367 ━━━━━━━━━━━━━━━━━━━━ 26s 81ms/step - loss: 0.0019 - mae: 0.0286

 42/367 ━━━━━━━━━━━━━━━━━━━━ 26s 81ms/step - loss: 0.0019 - mae: 0.0285

 43/367 ━━━━━━━━━━━━━━━━━━━━ 26s 81ms/step - loss: 0.0019 - mae: 0.0284

 44/367 ━━━━━━━━━━━━━━━━━━━━ 26s 81ms/step - loss: 0.0019 - mae: 0.0285

 45/367 ━━━━━━━━━━━━━━━━━━━━ 26s 81ms/step - loss: 0.0019 - mae: 0.0284

 46/367 ━━━━━━━━━━━━━━━━━━━━ 26s 81ms/step - loss: 0.0019 - mae: 0.0285

 47/367 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - loss: 0.0019 - mae: 0.0286

 48/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0019 - mae: 0.0288

 49/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0019 - mae: 0.0288

 50/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0019 - mae: 0.0289

 51/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0019 - mae: 0.0289

 52/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0019 - mae: 0.0287

 53/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0019 - mae: 0.0286

 54/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0019 - mae: 0.0285

 55/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0019 - mae: 0.0285

 56/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0019 - mae: 0.0283

 57/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0019 - mae: 0.0286

 58/367 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - loss: 0.0019 - mae: 0.0286

 59/367 ━━━━━━━━━━━━━━━━━━━━ 26s 86ms/step - loss: 0.0019 - mae: 0.0286

 60/367 ━━━━━━━━━━━━━━━━━━━━ 26s 86ms/step - loss: 0.0019 - mae: 0.0286

 61/367 ━━━━━━━━━━━━━━━━━━━━ 26s 86ms/step - loss: 0.0019 - mae: 0.0286

 62/367 ━━━━━━━━━━━━━━━━━━━━ 26s 87ms/step - loss: 0.0019 - mae: 0.0286

 63/367 ━━━━━━━━━━━━━━━━━━━━ 26s 87ms/step - loss: 0.0019 - mae: 0.0287

 64/367 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - loss: 0.0019 - mae: 0.0287

 65/367 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - loss: 0.0019 - mae: 0.0288

 66/367 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - loss: 0.0019 - mae: 0.0288

 67/367 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - loss: 0.0019 - mae: 0.0287

 68/367 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - loss: 0.0019 - mae: 0.0286

 69/367 ━━━━━━━━━━━━━━━━━━━━ 26s 89ms/step - loss: 0.0019 - mae: 0.0286

 70/367 ━━━━━━━━━━━━━━━━━━━━ 26s 89ms/step - loss: 0.0019 - mae: 0.0287

 71/367 ━━━━━━━━━━━━━━━━━━━━ 26s 89ms/step - loss: 0.0019 - mae: 0.0287

 72/367 ━━━━━━━━━━━━━━━━━━━━ 26s 89ms/step - loss: 0.0019 - mae: 0.0287

 73/367 ━━━━━━━━━━━━━━━━━━━━ 26s 89ms/step - loss: 0.0019 - mae: 0.0286

 74/367 ━━━━━━━━━━━━━━━━━━━━ 26s 90ms/step - loss: 0.0019 - mae: 0.0286

 75/367 ━━━━━━━━━━━━━━━━━━━━ 26s 90ms/step - loss: 0.0019 - mae: 0.0287

 76/367 ━━━━━━━━━━━━━━━━━━━━ 26s 89ms/step - loss: 0.0019 - mae: 0.0287

 77/367 ━━━━━━━━━━━━━━━━━━━━ 25s 89ms/step - loss: 0.0019 - mae: 0.0286

 78/367 ━━━━━━━━━━━━━━━━━━━━ 25s 89ms/step - loss: 0.0019 - mae: 0.0286

 79/367 ━━━━━━━━━━━━━━━━━━━━ 25s 89ms/step - loss: 0.0018 - mae: 0.0286

 80/367 ━━━━━━━━━━━━━━━━━━━━ 25s 89ms/step - loss: 0.0018 - mae: 0.0285

 81/367 ━━━━━━━━━━━━━━━━━━━━ 25s 89ms/step - loss: 0.0018 - mae: 0.0286

 82/367 ━━━━━━━━━━━━━━━━━━━━ 25s 89ms/step - loss: 0.0018 - mae: 0.0285

 83/367 ━━━━━━━━━━━━━━━━━━━━ 25s 89ms/step - loss: 0.0018 - mae: 0.0285

 84/367 ━━━━━━━━━━━━━━━━━━━━ 25s 89ms/step - loss: 0.0018 - mae: 0.0283

 85/367 ━━━━━━━━━━━━━━━━━━━━ 25s 89ms/step - loss: 0.0018 - mae: 0.0283

 86/367 ━━━━━━━━━━━━━━━━━━━━ 25s 89ms/step - loss: 0.0018 - mae: 0.0283

 87/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0283

 88/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0283

 89/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0283

 90/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0283

 91/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0283

 92/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0283

 93/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0283

 94/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0283

 95/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0284

 96/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0283

 97/367 ━━━━━━━━━━━━━━━━━━━━ 24s 89ms/step - loss: 0.0018 - mae: 0.0282

 98/367 ━━━━━━━━━━━━━━━━━━━━ 23s 89ms/step - loss: 0.0018 - mae: 0.0282

 99/367 ━━━━━━━━━━━━━━━━━━━━ 23s 89ms/step - loss: 0.0018 - mae: 0.0283

100/367 ━━━━━━━━━━━━━━━━━━━━ 23s 89ms/step - loss: 0.0018 - mae: 0.0282

101/367 ━━━━━━━━━━━━━━━━━━━━ 23s 89ms/step - loss: 0.0018 - mae: 0.0282

102/367 ━━━━━━━━━━━━━━━━━━━━ 23s 89ms/step - loss: 0.0018 - mae: 0.0282

103/367 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - loss: 0.0018 - mae: 0.0282

104/367 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - loss: 0.0018 - mae: 0.0281

105/367 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - loss: 0.0018 - mae: 0.0281

106/367 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - loss: 0.0018 - mae: 0.0280

107/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0018 - mae: 0.0280

108/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0018 - mae: 0.0280

109/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0018 - mae: 0.0280

110/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0018 - mae: 0.0280

111/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0018 - mae: 0.0280

112/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0018 - mae: 0.0280

113/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0018 - mae: 0.0280

114/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0018 - mae: 0.0280

115/367 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - loss: 0.0018 - mae: 0.0280

116/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0018 - mae: 0.0280

117/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0018 - mae: 0.0280

118/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0018 - mae: 0.0280

119/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0018 - mae: 0.0279

120/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0018 - mae: 0.0280

121/367 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - loss: 0.0018 - mae: 0.0280

122/367 ━━━━━━━━━━━━━━━━━━━━ 21s 87ms/step - loss: 0.0018 - mae: 0.0280

123/367 ━━━━━━━━━━━━━━━━━━━━ 21s 87ms/step - loss: 0.0018 - mae: 0.0281

124/367 ━━━━━━━━━━━━━━━━━━━━ 21s 87ms/step - loss: 0.0018 - mae: 0.0281

125/367 ━━━━━━━━━━━━━━━━━━━━ 21s 87ms/step - loss: 0.0018 - mae: 0.0281

126/367 ━━━━━━━━━━━━━━━━━━━━ 21s 87ms/step - loss: 0.0018 - mae: 0.0281

127/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

128/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

129/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

130/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

131/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

132/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

133/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

134/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

135/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

136/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

137/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0280

138/367 ━━━━━━━━━━━━━━━━━━━━ 20s 87ms/step - loss: 0.0018 - mae: 0.0279

139/367 ━━━━━━━━━━━━━━━━━━━━ 19s 87ms/step - loss: 0.0018 - mae: 0.0279

140/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0279

141/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0280

142/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0280

143/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0280

144/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0280

145/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0017 - mae: 0.0280

146/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0280

147/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0280

148/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0281

149/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0281

150/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0281

151/367 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - loss: 0.0018 - mae: 0.0281

152/367 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - loss: 0.0018 - mae: 0.0281

153/367 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - loss: 0.0018 - mae: 0.0281

154/367 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - loss: 0.0018 - mae: 0.0281

155/367 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - loss: 0.0018 - mae: 0.0281

156/367 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - loss: 0.0018 - mae: 0.0281

157/367 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - loss: 0.0018 - mae: 0.0281

158/367 ━━━━━━━━━━━━━━━━━━━━ 18s 89ms/step - loss: 0.0018 - mae: 0.0281

159/367 ━━━━━━━━━━━━━━━━━━━━ 18s 89ms/step - loss: 0.0018 - mae: 0.0281

160/367 ━━━━━━━━━━━━━━━━━━━━ 18s 89ms/step - loss: 0.0018 - mae: 0.0281

161/367 ━━━━━━━━━━━━━━━━━━━━ 18s 89ms/step - loss: 0.0018 - mae: 0.0281

162/367 ━━━━━━━━━━━━━━━━━━━━ 18s 89ms/step - loss: 0.0018 - mae: 0.0281

163/367 ━━━━━━━━━━━━━━━━━━━━ 18s 89ms/step - loss: 0.0018 - mae: 0.0281

164/367 ━━━━━━━━━━━━━━━━━━━━ 18s 89ms/step - loss: 0.0018 - mae: 0.0281

165/367 ━━━━━━━━━━━━━━━━━━━━ 18s 89ms/step - loss: 0.0018 - mae: 0.0281

166/367 ━━━━━━━━━━━━━━━━━━━━ 17s 89ms/step - loss: 0.0018 - mae: 0.0281

167/367 ━━━━━━━━━━━━━━━━━━━━ 17s 89ms/step - loss: 0.0017 - mae: 0.0281

168/367 ━━━━━━━━━━━━━━━━━━━━ 17s 89ms/step - loss: 0.0017 - mae: 0.0281

169/367 ━━━━━━━━━━━━━━━━━━━━ 17s 90ms/step - loss: 0.0017 - mae: 0.0281

170/367 ━━━━━━━━━━━━━━━━━━━━ 17s 90ms/step - loss: 0.0018 - mae: 0.0281

171/367 ━━━━━━━━━━━━━━━━━━━━ 17s 90ms/step - loss: 0.0018 - mae: 0.0281

172/367 ━━━━━━━━━━━━━━━━━━━━ 17s 90ms/step - loss: 0.0018 - mae: 0.0281

173/367 ━━━━━━━━━━━━━━━━━━━━ 17s 90ms/step - loss: 0.0018 - mae: 0.0281

174/367 ━━━━━━━━━━━━━━━━━━━━ 17s 90ms/step - loss: 0.0018 - mae: 0.0281

175/367 ━━━━━━━━━━━━━━━━━━━━ 17s 90ms/step - loss: 0.0018 - mae: 0.0281

176/367 ━━━━━━━━━━━━━━━━━━━━ 17s 90ms/step - loss: 0.0017 - mae: 0.0281

177/367 ━━━━━━━━━━━━━━━━━━━━ 17s 90ms/step - loss: 0.0017 - mae: 0.0281

178/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0281

179/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0281

180/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0018 - mae: 0.0281

181/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0281

182/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0281

183/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0281

184/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0281

185/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0281

186/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0281

187/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0281

188/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0280

189/367 ━━━━━━━━━━━━━━━━━━━━ 16s 90ms/step - loss: 0.0017 - mae: 0.0281

190/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

191/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

192/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

193/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

194/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

195/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

196/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

197/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

198/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

199/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

200/367 ━━━━━━━━━━━━━━━━━━━━ 15s 90ms/step - loss: 0.0017 - mae: 0.0280

201/367 ━━━━━━━━━━━━━━━━━━━━ 15s 91ms/step - loss: 0.0017 - mae: 0.0279

202/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0279

203/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0279

204/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0279

205/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0279

206/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0279

207/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0280

208/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0280

209/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0280

210/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0280

211/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0280

212/367 ━━━━━━━━━━━━━━━━━━━━ 14s 91ms/step - loss: 0.0017 - mae: 0.0280

213/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0280

214/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0280

215/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0281

216/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0282

217/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0282

218/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0282

219/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0282

220/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0282

221/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0282

222/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0283

223/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0283

224/367 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 0.0017 - mae: 0.0283

225/367 ━━━━━━━━━━━━━━━━━━━━ 12s 91ms/step - loss: 0.0017 - mae: 0.0283

226/367 ━━━━━━━━━━━━━━━━━━━━ 12s 91ms/step - loss: 0.0017 - mae: 0.0283

227/367 ━━━━━━━━━━━━━━━━━━━━ 12s 91ms/step - loss: 0.0017 - mae: 0.0283

228/367 ━━━━━━━━━━━━━━━━━━━━ 12s 91ms/step - loss: 0.0017 - mae: 0.0283

229/367 ━━━━━━━━━━━━━━━━━━━━ 12s 91ms/step - loss: 0.0017 - mae: 0.0283

230/367 ━━━━━━━━━━━━━━━━━━━━ 12s 91ms/step - loss: 0.0018 - mae: 0.0283

231/367 ━━━━━━━━━━━━━━━━━━━━ 12s 91ms/step - loss: 0.0018 - mae: 0.0283

232/367 ━━━━━━━━━━━━━━━━━━━━ 12s 91ms/step - loss: 0.0018 - mae: 0.0283

233/367 ━━━━━━━━━━━━━━━━━━━━ 12s 91ms/step - loss: 0.0017 - mae: 0.0283

235/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0283

236/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0283

237/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0283

238/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0283

239/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0283

240/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0283

241/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0283

242/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0283

243/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0283

244/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0282

245/367 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 0.0017 - mae: 0.0282

246/367 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 0.0017 - mae: 0.0281

247/367 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 0.0017 - mae: 0.0281

248/367 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 0.0017 - mae: 0.0281

249/367 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 0.0017 - mae: 0.0281

250/367 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 0.0017 - mae: 0.0281

251/367 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 0.0017 - mae: 0.0281

252/367 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 0.0017 - mae: 0.0280

253/367 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 0.0017 - mae: 0.0280

254/367 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 0.0017 - mae: 0.0280

255/367 ━━━━━━━━━━━━━━━━━━━━ 10s 90ms/step - loss: 0.0017 - mae: 0.0280

256/367 ━━━━━━━━━━━━━━━━━━━━ 10s 90ms/step - loss: 0.0017 - mae: 0.0280

257/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0280

258/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0280

259/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0280

260/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0280

261/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0281

262/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0281

263/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0281

264/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0281

265/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0280

266/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0281

267/367 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 0.0017 - mae: 0.0281

268/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0281

269/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0280

270/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0280

271/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0280

272/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0280

273/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0280

274/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0280

275/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0280

276/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0280

277/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0279

278/367 ━━━━━━━━━━━━━━━━━━━━ 8s 90ms/step - loss: 0.0017 - mae: 0.0280

279/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0279

280/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0279

281/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0279

282/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0279

283/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0279

284/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0279

285/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0280

286/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0280

287/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0280

288/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0280

289/367 ━━━━━━━━━━━━━━━━━━━━ 7s 90ms/step - loss: 0.0017 - mae: 0.0280

290/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0280

291/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0280

292/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0280

293/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0280

294/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0280

295/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0280

296/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0280

297/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0280

298/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0280

299/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0280

300/367 ━━━━━━━━━━━━━━━━━━━━ 6s 90ms/step - loss: 0.0017 - mae: 0.0281

301/367 ━━━━━━━━━━━━━━━━━━━━ 5s 90ms/step - loss: 0.0017 - mae: 0.0281

302/367 ━━━━━━━━━━━━━━━━━━━━ 5s 90ms/step - loss: 0.0017 - mae: 0.0281

303/367 ━━━━━━━━━━━━━━━━━━━━ 5s 90ms/step - loss: 0.0017 - mae: 0.0281

304/367 ━━━━━━━━━━━━━━━━━━━━ 5s 90ms/step - loss: 0.0017 - mae: 0.0281

305/367 ━━━━━━━━━━━━━━━━━━━━ 5s 90ms/step - loss: 0.0017 - mae: 0.0281

306/367 ━━━━━━━━━━━━━━━━━━━━ 5s 90ms/step - loss: 0.0017 - mae: 0.0281

307/367 ━━━━━━━━━━━━━━━━━━━━ 5s 90ms/step - loss: 0.0017 - mae: 0.0281

308/367 ━━━━━━━━━━━━━━━━━━━━ 5s 90ms/step - loss: 0.0017 - mae: 0.0280

309/367 ━━━━━━━━━━━━━━━━━━━━ 5s 89ms/step - loss: 0.0017 - mae: 0.0280

310/367 ━━━━━━━━━━━━━━━━━━━━ 5s 89ms/step - loss: 0.0017 - mae: 0.0280

311/367 ━━━━━━━━━━━━━━━━━━━━ 5s 89ms/step - loss: 0.0017 - mae: 0.0280

312/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

313/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

314/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

315/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

316/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

317/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

318/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

319/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

320/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

321/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

322/367 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step - loss: 0.0017 - mae: 0.0280

323/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0280

324/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0280

325/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0280

326/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0280

327/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0280

328/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0279

329/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0279

330/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0279

331/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0279

332/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0279

333/367 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 0.0017 - mae: 0.0279

334/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0279

335/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0279

336/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0279

337/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0278

338/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0278

339/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0279

340/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0279

341/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0278

342/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0279

343/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0279

344/367 ━━━━━━━━━━━━━━━━━━━━ 2s 89ms/step - loss: 0.0017 - mae: 0.0279

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - loss: 0.0017 - mae: 0.0279

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - loss: 0.0017 - mae: 0.0278

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - loss: 0.0017 - mae: 0.0279

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - loss: 0.0017 - mae: 0.0279

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - loss: 0.0017 - mae: 0.0279

350/367 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - loss: 0.0017 - mae: 0.0279

351/367 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - loss: 0.0017 - mae: 0.0279

352/367 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - loss: 0.0017 - mae: 0.0279

353/367 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - loss: 0.0017 - mae: 0.0279

354/367 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - loss: 0.0017 - mae: 0.0278

355/367 ━━━━━━━━━━━━━━━━━━━━ 1s 89ms/step - loss: 0.0017 - mae: 0.0278

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0017 - mae: 0.0278

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0017 - mae: 0.0278

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0017 - mae: 0.0278

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0017 - mae: 0.0278

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0017 - mae: 0.0278

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0017 - mae: 0.0278

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0017 - mae: 0.0278

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 0.0017 - mae: 0.0278

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0017 - mae: 0.0278

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0017 - mae: 0.0278

366/367 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0017 - mae: 0.0278

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 0.0017 - mae: 0.0278

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 35s 95ms/step - loss: 0.0017 - mae: 0.0278 - val_loss: 0.0017 - val_mae: 0.0277 - learning_rate: 1.0000e-04

Epoch 9/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 41s 113ms/step - loss: 0.0010 - mae: 0.0241

  2/367 ━━━━━━━━━━━━━━━━━━━━ 24s 68ms/step - loss: 0.0014 - mae: 0.0270

  3/367 ━━━━━━━━━━━━━━━━━━━━ 24s 66ms/step - loss: 0.0013 - mae: 0.0263

  4/367 ━━━━━━━━━━━━━━━━━━━━ 23s 65ms/step - loss: 0.0012 - mae: 0.0251

  5/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0013 - mae: 0.0264

  6/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0015 - mae: 0.0270

  7/367 ━━━━━━━━━━━━━━━━━━━━ 23s 65ms/step - loss: 0.0014 - mae: 0.0259

  8/367 ━━━━━━━━━━━━━━━━━━━━ 23s 65ms/step - loss: 0.0013 - mae: 0.0251

  9/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0013 - mae: 0.0247

 10/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0015 - mae: 0.0258

 11/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0015 - mae: 0.0257

 12/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0015 - mae: 0.0259

 13/367 ━━━━━━━━━━━━━━━━━━━━ 24s 70ms/step - loss: 0.0015 - mae: 0.0259

 14/367 ━━━━━━━━━━━━━━━━━━━━ 24s 70ms/step - loss: 0.0016 - mae: 0.0268

 15/367 ━━━━━━━━━━━━━━━━━━━━ 24s 70ms/step - loss: 0.0017 - mae: 0.0272

 16/367 ━━━━━━━━━━━━━━━━━━━━ 24s 71ms/step - loss: 0.0017 - mae: 0.0272

 17/367 ━━━━━━━━━━━━━━━━━━━━ 24s 71ms/step - loss: 0.0016 - mae: 0.0267

 18/367 ━━━━━━━━━━━━━━━━━━━━ 25s 72ms/step - loss: 0.0016 - mae: 0.0265

 19/367 ━━━━━━━━━━━━━━━━━━━━ 25s 72ms/step - loss: 0.0016 - mae: 0.0265

 20/367 ━━━━━━━━━━━━━━━━━━━━ 25s 73ms/step - loss: 0.0017 - mae: 0.0273

 21/367 ━━━━━━━━━━━━━━━━━━━━ 25s 73ms/step - loss: 0.0016 - mae: 0.0269

 22/367 ━━━━━━━━━━━━━━━━━━━━ 25s 73ms/step - loss: 0.0017 - mae: 0.0273

 23/367 ━━━━━━━━━━━━━━━━━━━━ 25s 74ms/step - loss: 0.0016 - mae: 0.0269

 24/367 ━━━━━━━━━━━━━━━━━━━━ 25s 74ms/step - loss: 0.0016 - mae: 0.0266

 25/367 ━━━━━━━━━━━━━━━━━━━━ 25s 74ms/step - loss: 0.0016 - mae: 0.0266

 26/367 ━━━━━━━━━━━━━━━━━━━━ 25s 75ms/step - loss: 0.0016 - mae: 0.0264

 27/367 ━━━━━━━━━━━━━━━━━━━━ 25s 75ms/step - loss: 0.0015 - mae: 0.0262

 28/367 ━━━━━━━━━━━━━━━━━━━━ 25s 77ms/step - loss: 0.0015 - mae: 0.0260

 29/367 ━━━━━━━━━━━━━━━━━━━━ 25s 76ms/step - loss: 0.0015 - mae: 0.0262

 30/367 ━━━━━━━━━━━━━━━━━━━━ 25s 77ms/step - loss: 0.0015 - mae: 0.0261

 31/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0015 - mae: 0.0259

 32/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0015 - mae: 0.0259

 33/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0015 - mae: 0.0257

 34/367 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - loss: 0.0015 - mae: 0.0258

 35/367 ━━━━━━━━━━━━━━━━━━━━ 26s 81ms/step - loss: 0.0015 - mae: 0.0258

 36/367 ━━━━━━━━━━━━━━━━━━━━ 26s 81ms/step - loss: 0.0015 - mae: 0.0258

 37/367 ━━━━━━━━━━━━━━━━━━━━ 26s 81ms/step - loss: 0.0015 - mae: 0.0262

 38/367 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - loss: 0.0015 - mae: 0.0262

 39/367 ━━━━━━━━━━━━━━━━━━━━ 27s 83ms/step - loss: 0.0015 - mae: 0.0262

 40/367 ━━━━━━━━━━━━━━━━━━━━ 27s 84ms/step - loss: 0.0015 - mae: 0.0263

 41/367 ━━━━━━━━━━━━━━━━━━━━ 27s 84ms/step - loss: 0.0015 - mae: 0.0263

 42/367 ━━━━━━━━━━━━━━━━━━━━ 27s 84ms/step - loss: 0.0015 - mae: 0.0262

 43/367 ━━━━━━━━━━━━━━━━━━━━ 27s 83ms/step - loss: 0.0015 - mae: 0.0262

 44/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0015 - mae: 0.0261

 45/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0015 - mae: 0.0261

 46/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0015 - mae: 0.0262

 47/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0015 - mae: 0.0260

 48/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0015 - mae: 0.0259

 49/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0015 - mae: 0.0259

 50/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0015 - mae: 0.0259

 51/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0015 - mae: 0.0259

 52/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0015 - mae: 0.0259

 53/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0015 - mae: 0.0259

 54/367 ━━━━━━━━━━━━━━━━━━━━ 25s 83ms/step - loss: 0.0015 - mae: 0.0258

 55/367 ━━━━━━━━━━━━━━━━━━━━ 25s 83ms/step - loss: 0.0015 - mae: 0.0258

 56/367 ━━━━━━━━━━━━━━━━━━━━ 25s 83ms/step - loss: 0.0015 - mae: 0.0258

 57/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0258

 58/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0259

 59/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0258

 60/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0260

 61/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0260

 62/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0260

 63/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0260

 64/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0259

 65/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0258

 66/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0257

 67/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0015 - mae: 0.0257

 68/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0014 - mae: 0.0256

 69/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0014 - mae: 0.0255

 70/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0014 - mae: 0.0255

 71/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0015 - mae: 0.0257

 72/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0257

 73/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0256

 74/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0255

 75/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0256

 76/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0257

 77/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0255

 78/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0257

 79/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0257

 80/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0257

 81/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0257

 82/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0257

 83/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0015 - mae: 0.0257

 84/367 ━━━━━━━━━━━━━━━━━━━━ 23s 85ms/step - loss: 0.0015 - mae: 0.0258

 85/367 ━━━━━━━━━━━━━━━━━━━━ 23s 85ms/step - loss: 0.0015 - mae: 0.0259

 86/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0015 - mae: 0.0259

 87/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0015 - mae: 0.0259

 88/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0015 - mae: 0.0259

 89/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0015 - mae: 0.0259

 90/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0015 - mae: 0.0260

 91/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0015 - mae: 0.0261

 92/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0015 - mae: 0.0260

 93/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0015 - mae: 0.0259

 94/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0015 - mae: 0.0259

 95/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0015 - mae: 0.0259

 96/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0015 - mae: 0.0258

 97/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0015 - mae: 0.0259

 98/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0015 - mae: 0.0258

 99/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0015 - mae: 0.0258

100/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0015 - mae: 0.0257

101/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0015 - mae: 0.0257

102/367 ━━━━━━━━━━━━━━━━━━━━ 22s 83ms/step - loss: 0.0015 - mae: 0.0259

103/367 ━━━━━━━━━━━━━━━━━━━━ 22s 83ms/step - loss: 0.0015 - mae: 0.0259

104/367 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 0.0015 - mae: 0.0259

105/367 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 0.0015 - mae: 0.0258

106/367 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 0.0015 - mae: 0.0258

107/367 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 0.0015 - mae: 0.0258

108/367 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 0.0015 - mae: 0.0256

109/367 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 0.0015 - mae: 0.0257

110/367 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 0.0015 - mae: 0.0257

111/367 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 0.0015 - mae: 0.0258

112/367 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 0.0015 - mae: 0.0258

113/367 ━━━━━━━━━━━━━━━━━━━━ 21s 83ms/step - loss: 0.0015 - mae: 0.0258

114/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0258

115/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0258

116/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0258

117/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0258

118/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0259

119/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0259

120/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0259

121/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0259

122/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0258

123/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0259

124/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0259

125/367 ━━━━━━━━━━━━━━━━━━━━ 20s 83ms/step - loss: 0.0015 - mae: 0.0258

126/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 0.0015 - mae: 0.0258

127/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 0.0015 - mae: 0.0258

128/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 0.0015 - mae: 0.0259

129/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 0.0015 - mae: 0.0258

130/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 0.0015 - mae: 0.0258

131/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 0.0015 - mae: 0.0258

132/367 ━━━━━━━━━━━━━━━━━━━━ 19s 84ms/step - loss: 0.0015 - mae: 0.0258

133/367 ━━━━━━━━━━━━━━━━━━━━ 19s 84ms/step - loss: 0.0015 - mae: 0.0258

134/367 ━━━━━━━━━━━━━━━━━━━━ 19s 84ms/step - loss: 0.0015 - mae: 0.0258

135/367 ━━━━━━━━━━━━━━━━━━━━ 19s 84ms/step - loss: 0.0015 - mae: 0.0258

136/367 ━━━━━━━━━━━━━━━━━━━━ 19s 85ms/step - loss: 0.0015 - mae: 0.0258

137/367 ━━━━━━━━━━━━━━━━━━━━ 19s 85ms/step - loss: 0.0015 - mae: 0.0258

138/367 ━━━━━━━━━━━━━━━━━━━━ 19s 85ms/step - loss: 0.0015 - mae: 0.0258

139/367 ━━━━━━━━━━━━━━━━━━━━ 19s 85ms/step - loss: 0.0015 - mae: 0.0258

140/367 ━━━━━━━━━━━━━━━━━━━━ 19s 85ms/step - loss: 0.0015 - mae: 0.0258

141/367 ━━━━━━━━━━━━━━━━━━━━ 19s 85ms/step - loss: 0.0015 - mae: 0.0258

142/367 ━━━━━━━━━━━━━━━━━━━━ 19s 85ms/step - loss: 0.0015 - mae: 0.0258

143/367 ━━━━━━━━━━━━━━━━━━━━ 19s 85ms/step - loss: 0.0015 - mae: 0.0259

144/367 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - loss: 0.0015 - mae: 0.0259

145/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0259

146/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0259

147/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0259

148/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0259

149/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0258

150/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0259

151/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0259

152/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0259

153/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0259

154/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0260

155/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0260

156/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0260

157/367 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - loss: 0.0015 - mae: 0.0259

158/367 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - loss: 0.0015 - mae: 0.0259

159/367 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - loss: 0.0015 - mae: 0.0260

160/367 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - loss: 0.0015 - mae: 0.0260

161/367 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - loss: 0.0015 - mae: 0.0260

162/367 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - loss: 0.0015 - mae: 0.0260

163/367 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - loss: 0.0015 - mae: 0.0260

164/367 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - loss: 0.0015 - mae: 0.0260

165/367 ━━━━━━━━━━━━━━━━━━━━ 17s 85ms/step - loss: 0.0015 - mae: 0.0260

166/367 ━━━━━━━━━━━━━━━━━━━━ 17s 85ms/step - loss: 0.0015 - mae: 0.0259

167/367 ━━━━━━━━━━━━━━━━━━━━ 17s 85ms/step - loss: 0.0015 - mae: 0.0260

168/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0260

169/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0260

170/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0259

171/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0259

172/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0259

173/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0259

174/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0260

175/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0260

176/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0260

177/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0259

178/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0259

179/367 ━━━━━━━━━━━━━━━━━━━━ 16s 85ms/step - loss: 0.0015 - mae: 0.0259

180/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0259

181/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0259

182/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0258

183/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0258

184/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0258

185/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0258

186/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0258

187/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0258

188/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0258

189/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0258

190/367 ━━━━━━━━━━━━━━━━━━━━ 15s 85ms/step - loss: 0.0015 - mae: 0.0258

191/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0258

192/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0258

193/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0258

194/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0258

195/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0258

196/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0259

197/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0259

198/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0259

199/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0259

200/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0259

201/367 ━━━━━━━━━━━━━━━━━━━━ 14s 85ms/step - loss: 0.0015 - mae: 0.0259

202/367 ━━━━━━━━━━━━━━━━━━━━ 13s 85ms/step - loss: 0.0015 - mae: 0.0259

203/367 ━━━━━━━━━━━━━━━━━━━━ 13s 85ms/step - loss: 0.0015 - mae: 0.0259

204/367 ━━━━━━━━━━━━━━━━━━━━ 13s 85ms/step - loss: 0.0015 - mae: 0.0259

205/367 ━━━━━━━━━━━━━━━━━━━━ 13s 85ms/step - loss: 0.0015 - mae: 0.0259

206/367 ━━━━━━━━━━━━━━━━━━━━ 13s 85ms/step - loss: 0.0015 - mae: 0.0259

207/367 ━━━━━━━━━━━━━━━━━━━━ 13s 85ms/step - loss: 0.0015 - mae: 0.0258

208/367 ━━━━━━━━━━━━━━━━━━━━ 13s 85ms/step - loss: 0.0015 - mae: 0.0259

209/367 ━━━━━━━━━━━━━━━━━━━━ 13s 85ms/step - loss: 0.0015 - mae: 0.0259

210/367 ━━━━━━━━━━━━━━━━━━━━ 13s 84ms/step - loss: 0.0015 - mae: 0.0258

211/367 ━━━━━━━━━━━━━━━━━━━━ 13s 84ms/step - loss: 0.0015 - mae: 0.0258

212/367 ━━━━━━━━━━━━━━━━━━━━ 13s 84ms/step - loss: 0.0015 - mae: 0.0259

213/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0259

214/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0258

215/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0259

216/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0259

217/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0258

218/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0258

219/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0258

220/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0258

221/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0014 - mae: 0.0257

222/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0258

223/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0258

224/367 ━━━━━━━━━━━━━━━━━━━━ 12s 84ms/step - loss: 0.0015 - mae: 0.0258

225/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

226/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

227/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

228/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0259

229/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

230/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

231/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

232/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

233/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

234/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

235/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

236/367 ━━━━━━━━━━━━━━━━━━━━ 11s 84ms/step - loss: 0.0015 - mae: 0.0258

237/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0015 - mae: 0.0258

238/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0015 - mae: 0.0258

239/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0015 - mae: 0.0258

240/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0015 - mae: 0.0257

241/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0015 - mae: 0.0257

242/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0014 - mae: 0.0257

243/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0014 - mae: 0.0257

244/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0014 - mae: 0.0257

245/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0014 - mae: 0.0257

246/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0014 - mae: 0.0257

247/367 ━━━━━━━━━━━━━━━━━━━━ 10s 84ms/step - loss: 0.0014 - mae: 0.0257

248/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0014 - mae: 0.0257

249/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0014 - mae: 0.0257

250/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0014 - mae: 0.0257

251/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0015 - mae: 0.0257

252/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0015 - mae: 0.0257

253/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0015 - mae: 0.0257

254/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0015 - mae: 0.0257

255/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0015 - mae: 0.0258

256/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0015 - mae: 0.0258

257/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0015 - mae: 0.0258

258/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0015 - mae: 0.0258

259/367 ━━━━━━━━━━━━━━━━━━━━ 9s 84ms/step - loss: 0.0015 - mae: 0.0258

260/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

261/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

262/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

263/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

264/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

265/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

266/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

267/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

268/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

269/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

270/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

271/367 ━━━━━━━━━━━━━━━━━━━━ 8s 84ms/step - loss: 0.0015 - mae: 0.0258

272/367 ━━━━━━━━━━━━━━━━━━━━ 7s 84ms/step - loss: 0.0015 - mae: 0.0258

273/367 ━━━━━━━━━━━━━━━━━━━━ 7s 84ms/step - loss: 0.0015 - mae: 0.0258

274/367 ━━━━━━━━━━━━━━━━━━━━ 7s 84ms/step - loss: 0.0015 - mae: 0.0258

275/367 ━━━━━━━━━━━━━━━━━━━━ 7s 84ms/step - loss: 0.0015 - mae: 0.0258

276/367 ━━━━━━━━━━━━━━━━━━━━ 7s 84ms/step - loss: 0.0015 - mae: 0.0258

277/367 ━━━━━━━━━━━━━━━━━━━━ 7s 84ms/step - loss: 0.0015 - mae: 0.0258

278/367 ━━━━━━━━━━━━━━━━━━━━ 7s 84ms/step - loss: 0.0015 - mae: 0.0258

279/367 ━━━━━━━━━━━━━━━━━━━━ 7s 83ms/step - loss: 0.0015 - mae: 0.0258

280/367 ━━━━━━━━━━━━━━━━━━━━ 7s 83ms/step - loss: 0.0015 - mae: 0.0258

281/367 ━━━━━━━━━━━━━━━━━━━━ 7s 83ms/step - loss: 0.0015 - mae: 0.0258

282/367 ━━━━━━━━━━━━━━━━━━━━ 7s 83ms/step - loss: 0.0015 - mae: 0.0258

283/367 ━━━━━━━━━━━━━━━━━━━━ 7s 83ms/step - loss: 0.0015 - mae: 0.0258

284/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0258

285/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0257

286/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0257

287/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0257

288/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0257

289/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0257

290/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0257

291/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0257

292/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0257

293/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0257

294/367 ━━━━━━━━━━━━━━━━━━━━ 6s 83ms/step - loss: 0.0015 - mae: 0.0257

295/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0015 - mae: 0.0257

296/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0015 - mae: 0.0257

297/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0015 - mae: 0.0256

298/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0015 - mae: 0.0256

299/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0015 - mae: 0.0257

300/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0015 - mae: 0.0257

301/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0014 - mae: 0.0256

302/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0014 - mae: 0.0256

303/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0014 - mae: 0.0256

304/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0014 - mae: 0.0256

305/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0014 - mae: 0.0256

306/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0014 - mae: 0.0256

307/367 ━━━━━━━━━━━━━━━━━━━━ 5s 83ms/step - loss: 0.0014 - mae: 0.0256

308/367 ━━━━━━━━━━━━━━━━━━━━ 4s 84ms/step - loss: 0.0014 - mae: 0.0256

309/367 ━━━━━━━━━━━━━━━━━━━━ 4s 83ms/step - loss: 0.0014 - mae: 0.0256

310/367 ━━━━━━━━━━━━━━━━━━━━ 4s 84ms/step - loss: 0.0014 - mae: 0.0255

311/367 ━━━━━━━━━━━━━━━━━━━━ 4s 84ms/step - loss: 0.0014 - mae: 0.0255

312/367 ━━━━━━━━━━━━━━━━━━━━ 4s 84ms/step - loss: 0.0014 - mae: 0.0255

313/367 ━━━━━━━━━━━━━━━━━━━━ 4s 84ms/step - loss: 0.0014 - mae: 0.0255

314/367 ━━━━━━━━━━━━━━━━━━━━ 4s 84ms/step - loss: 0.0014 - mae: 0.0255

315/367 ━━━━━━━━━━━━━━━━━━━━ 4s 84ms/step - loss: 0.0014 - mae: 0.0255

316/367 ━━━━━━━━━━━━━━━━━━━━ 4s 84ms/step - loss: 0.0014 - mae: 0.0255

317/367 ━━━━━━━━━━━━━━━━━━━━ 4s 83ms/step - loss: 0.0014 - mae: 0.0255

318/367 ━━━━━━━━━━━━━━━━━━━━ 4s 83ms/step - loss: 0.0014 - mae: 0.0255

319/367 ━━━━━━━━━━━━━━━━━━━━ 4s 83ms/step - loss: 0.0014 - mae: 0.0255

320/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

321/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

322/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

323/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

324/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

325/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

326/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

327/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

328/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

329/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

330/367 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 0.0014 - mae: 0.0255

331/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

332/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

333/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

334/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

335/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

336/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

337/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

338/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

339/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

340/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

341/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

342/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

343/367 ━━━━━━━━━━━━━━━━━━━━ 2s 83ms/step - loss: 0.0014 - mae: 0.0255

344/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

350/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

351/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0254

352/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

353/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

354/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

355/367 ━━━━━━━━━━━━━━━━━━━━ 1s 83ms/step - loss: 0.0014 - mae: 0.0255

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

366/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.0014 - mae: 0.0255

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 33s 89ms/step - loss: 0.0014 - mae: 0.0255 - val_loss: 0.0015 - val_mae: 0.0251 - learning_rate: 1.0000e-04

Epoch 10/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 34s 96ms/step - loss: 0.0017 - mae: 0.0284

  2/367 ━━━━━━━━━━━━━━━━━━━━ 21s 59ms/step - loss: 0.0012 - mae: 0.0246

  3/367 ━━━━━━━━━━━━━━━━━━━━ 22s 61ms/step - loss: 0.0010 - mae: 0.0225

  4/367 ━━━━━━━━━━━━━━━━━━━━ 22s 62ms/step - loss: 0.0011 - mae: 0.0233

  5/367 ━━━━━━━━━━━━━━━━━━━━ 22s 61ms/step - loss: 0.0011 - mae: 0.0227

  6/367 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - loss: 0.0011 - mae: 0.0228

  7/367 ━━━━━━━━━━━━━━━━━━━━ 22s 64ms/step - loss: 0.0011 - mae: 0.0226

  8/367 ━━━━━━━━━━━━━━━━━━━━ 22s 63ms/step - loss: 0.0012 - mae: 0.0236

  9/367 ━━━━━━━━━━━━━━━━━━━━ 22s 63ms/step - loss: 0.0013 - mae: 0.0243

 10/367 ━━━━━━━━━━━━━━━━━━━━ 22s 63ms/step - loss: 0.0013 - mae: 0.0243

 11/367 ━━━━━━━━━━━━━━━━━━━━ 22s 63ms/step - loss: 0.0013 - mae: 0.0241

 12/367 ━━━━━━━━━━━━━━━━━━━━ 22s 65ms/step - loss: 0.0013 - mae: 0.0241

 13/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0012 - mae: 0.0238

 14/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0012 - mae: 0.0234

 15/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0012 - mae: 0.0240

 16/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0012 - mae: 0.0241

 17/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0012 - mae: 0.0239

 18/367 ━━━━━━━━━━━━━━━━━━━━ 24s 70ms/step - loss: 0.0014 - mae: 0.0246

 19/367 ━━━━━━━━━━━━━━━━━━━━ 24s 71ms/step - loss: 0.0014 - mae: 0.0254

 20/367 ━━━━━━━━━━━━━━━━━━━━ 24s 72ms/step - loss: 0.0015 - mae: 0.0256

 21/367 ━━━━━━━━━━━━━━━━━━━━ 25s 73ms/step - loss: 0.0014 - mae: 0.0254

 22/367 ━━━━━━━━━━━━━━━━━━━━ 25s 73ms/step - loss: 0.0014 - mae: 0.0250

 23/367 ━━━━━━━━━━━━━━━━━━━━ 25s 73ms/step - loss: 0.0014 - mae: 0.0252

 24/367 ━━━━━━━━━━━━━━━━━━━━ 25s 75ms/step - loss: 0.0014 - mae: 0.0250

 25/367 ━━━━━━━━━━━━━━━━━━━━ 25s 75ms/step - loss: 0.0014 - mae: 0.0250

 26/367 ━━━━━━━━━━━━━━━━━━━━ 25s 75ms/step - loss: 0.0013 - mae: 0.0248

 27/367 ━━━━━━━━━━━━━━━━━━━━ 25s 75ms/step - loss: 0.0013 - mae: 0.0244

 28/367 ━━━━━━━━━━━━━━━━━━━━ 25s 74ms/step - loss: 0.0013 - mae: 0.0246

 29/367 ━━━━━━━━━━━━━━━━━━━━ 25s 74ms/step - loss: 0.0013 - mae: 0.0245

 30/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0013 - mae: 0.0243

 31/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0013 - mae: 0.0242

 32/367 ━━━━━━━━━━━━━━━━━━━━ 24s 73ms/step - loss: 0.0013 - mae: 0.0241

 33/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0013 - mae: 0.0241

 34/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0012 - mae: 0.0237

 35/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0013 - mae: 0.0240

 36/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0013 - mae: 0.0240

 37/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0012 - mae: 0.0238

 38/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0012 - mae: 0.0238

 39/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0012 - mae: 0.0238

 40/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0012 - mae: 0.0236

 41/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0012 - mae: 0.0237

 42/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0012 - mae: 0.0237

 43/367 ━━━━━━━━━━━━━━━━━━━━ 23s 74ms/step - loss: 0.0012 - mae: 0.0238

 44/367 ━━━━━━━━━━━━━━━━━━━━ 23s 74ms/step - loss: 0.0012 - mae: 0.0237

 45/367 ━━━━━━━━━━━━━━━━━━━━ 23s 74ms/step - loss: 0.0012 - mae: 0.0236

 46/367 ━━━━━━━━━━━━━━━━━━━━ 23s 74ms/step - loss: 0.0012 - mae: 0.0235

 47/367 ━━━━━━━━━━━━━━━━━━━━ 23s 74ms/step - loss: 0.0012 - mae: 0.0235

 48/367 ━━━━━━━━━━━━━━━━━━━━ 23s 74ms/step - loss: 0.0012 - mae: 0.0238

 49/367 ━━━━━━━━━━━━━━━━━━━━ 23s 74ms/step - loss: 0.0012 - mae: 0.0238

 50/367 ━━━━━━━━━━━━━━━━━━━━ 23s 73ms/step - loss: 0.0012 - mae: 0.0240

 51/367 ━━━━━━━━━━━━━━━━━━━━ 23s 73ms/step - loss: 0.0013 - mae: 0.0241

 52/367 ━━━━━━━━━━━━━━━━━━━━ 23s 73ms/step - loss: 0.0012 - mae: 0.0241

 53/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0013 - mae: 0.0241

 54/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0012 - mae: 0.0241

 55/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0012 - mae: 0.0241

 56/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0012 - mae: 0.0241

 57/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0012 - mae: 0.0241

 58/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0012 - mae: 0.0241

 59/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0013 - mae: 0.0242

 60/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0012 - mae: 0.0241

 61/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0012 - mae: 0.0240

 62/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0012 - mae: 0.0241

 63/367 ━━━━━━━━━━━━━━━━━━━━ 22s 73ms/step - loss: 0.0012 - mae: 0.0240

 64/367 ━━━━━━━━━━━━━━━━━━━━ 21s 73ms/step - loss: 0.0012 - mae: 0.0240

 65/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0012 - mae: 0.0241

 66/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0012 - mae: 0.0241

 67/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0013 - mae: 0.0242

 68/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0013 - mae: 0.0241

 69/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0013 - mae: 0.0242

 70/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0013 - mae: 0.0242

 71/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0013 - mae: 0.0242

 72/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0013 - mae: 0.0242

 73/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0013 - mae: 0.0242

 74/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0013 - mae: 0.0242

 75/367 ━━━━━━━━━━━━━━━━━━━━ 21s 72ms/step - loss: 0.0013 - mae: 0.0242

 76/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0242

 77/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0242

 78/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0242

 79/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0242

 80/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0243

 81/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0243

 82/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0243

 83/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0243

 84/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0243

 85/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0244

 86/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0243

 87/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0243

 88/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0244

 89/367 ━━━━━━━━━━━━━━━━━━━━ 20s 72ms/step - loss: 0.0013 - mae: 0.0245

 90/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0245

 91/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0246

 92/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0246

 93/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0247

 94/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0247

 95/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0247

 96/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0246

 97/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0245

 98/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0246

 99/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0246

100/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0246

101/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0247

102/367 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - loss: 0.0013 - mae: 0.0247

103/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0248

104/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0247

105/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0247

106/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0247

107/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0247

108/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0247

109/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0246

110/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0246

111/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0246

112/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0247

113/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0246

114/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0246

115/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0247

116/367 ━━━━━━━━━━━━━━━━━━━━ 18s 72ms/step - loss: 0.0013 - mae: 0.0247

117/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0248

118/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0248

119/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0248

120/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0248

121/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0248

122/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0248

123/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0249

124/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0249

125/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0249

126/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0014 - mae: 0.0250

127/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0250

128/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0249

129/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0249

130/367 ━━━━━━━━━━━━━━━━━━━━ 17s 72ms/step - loss: 0.0013 - mae: 0.0249

131/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0249

132/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0249

133/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0249

134/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0248

135/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0248

136/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0248

137/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0248

138/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0247

139/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0247

140/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0247

141/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0247

142/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0247

143/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0247

144/367 ━━━━━━━━━━━━━━━━━━━━ 16s 72ms/step - loss: 0.0013 - mae: 0.0246

145/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0246

146/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0245

147/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0245

148/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0245

149/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0245

150/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0245

151/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0245

152/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0245

153/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0245

154/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0244

155/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0245

156/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0244

157/367 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - loss: 0.0013 - mae: 0.0245

158/367 ━━━━━━━━━━━━━━━━━━━━ 14s 71ms/step - loss: 0.0013 - mae: 0.0244

159/367 ━━━━━━━━━━━━━━━━━━━━ 14s 72ms/step - loss: 0.0013 - mae: 0.0244

160/367 ━━━━━━━━━━━━━━━━━━━━ 14s 72ms/step - loss: 0.0013 - mae: 0.0244

162/367 ━━━━━━━━━━━━━━━━━━━━ 14s 71ms/step - loss: 0.0013 - mae: 0.0244

163/367 ━━━━━━━━━━━━━━━━━━━━ 14s 71ms/step - loss: 0.0013 - mae: 0.0244

164/367 ━━━━━━━━━━━━━━━━━━━━ 14s 71ms/step - loss: 0.0013 - mae: 0.0244

165/367 ━━━━━━━━━━━━━━━━━━━━ 14s 71ms/step - loss: 0.0013 - mae: 0.0244

166/367 ━━━━━━━━━━━━━━━━━━━━ 14s 71ms/step - loss: 0.0013 - mae: 0.0245

167/367 ━━━━━━━━━━━━━━━━━━━━ 14s 71ms/step - loss: 0.0013 - mae: 0.0245

168/367 ━━━━━━━━━━━━━━━━━━━━ 14s 71ms/step - loss: 0.0013 - mae: 0.0244

169/367 ━━━━━━━━━━━━━━━━━━━━ 14s 71ms/step - loss: 0.0013 - mae: 0.0245

170/367 ━━━━━━━━━━━━━━━━━━━━ 14s 71ms/step - loss: 0.0013 - mae: 0.0244

171/367 ━━━━━━━━━━━━━━━━━━━━ 14s 72ms/step - loss: 0.0013 - mae: 0.0244

172/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

173/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

174/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

175/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

176/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

177/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

178/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

179/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

180/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

181/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

182/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

183/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

184/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0244

185/367 ━━━━━━━━━━━━━━━━━━━━ 13s 72ms/step - loss: 0.0013 - mae: 0.0243

186/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0243

187/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0243

188/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0243

189/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0243

190/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0243

191/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0244

192/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0244

193/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0244

194/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0244

195/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0243

196/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0244

197/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0244

198/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0244

199/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0244

200/367 ━━━━━━━━━━━━━━━━━━━━ 12s 72ms/step - loss: 0.0013 - mae: 0.0244

201/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

202/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

203/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

204/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0245

205/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

206/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

207/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

208/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

209/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

210/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

211/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

212/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

213/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

214/367 ━━━━━━━━━━━━━━━━━━━━ 11s 72ms/step - loss: 0.0013 - mae: 0.0244

215/367 ━━━━━━━━━━━━━━━━━━━━ 10s 72ms/step - loss: 0.0013 - mae: 0.0245

216/367 ━━━━━━━━━━━━━━━━━━━━ 10s 72ms/step - loss: 0.0013 - mae: 0.0244

217/367 ━━━━━━━━━━━━━━━━━━━━ 10s 72ms/step - loss: 0.0013 - mae: 0.0245

218/367 ━━━━━━━━━━━━━━━━━━━━ 10s 72ms/step - loss: 0.0013 - mae: 0.0245

219/367 ━━━━━━━━━━━━━━━━━━━━ 10s 73ms/step - loss: 0.0013 - mae: 0.0245

220/367 ━━━━━━━━━━━━━━━━━━━━ 10s 72ms/step - loss: 0.0013 - mae: 0.0245

221/367 ━━━━━━━━━━━━━━━━━━━━ 10s 72ms/step - loss: 0.0013 - mae: 0.0245

222/367 ━━━━━━━━━━━━━━━━━━━━ 10s 73ms/step - loss: 0.0013 - mae: 0.0244

223/367 ━━━━━━━━━━━━━━━━━━━━ 10s 73ms/step - loss: 0.0013 - mae: 0.0244

224/367 ━━━━━━━━━━━━━━━━━━━━ 10s 73ms/step - loss: 0.0013 - mae: 0.0244

225/367 ━━━━━━━━━━━━━━━━━━━━ 10s 73ms/step - loss: 0.0013 - mae: 0.0244

226/367 ━━━━━━━━━━━━━━━━━━━━ 10s 73ms/step - loss: 0.0013 - mae: 0.0244

227/367 ━━━━━━━━━━━━━━━━━━━━ 10s 73ms/step - loss: 0.0013 - mae: 0.0244

228/367 ━━━━━━━━━━━━━━━━━━━━ 10s 73ms/step - loss: 0.0013 - mae: 0.0244

229/367 ━━━━━━━━━━━━━━━━━━━━ 10s 73ms/step - loss: 0.0013 - mae: 0.0244

230/367 ━━━━━━━━━━━━━━━━━━━━ 10s 73ms/step - loss: 0.0013 - mae: 0.0244

231/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

232/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

233/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

234/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

235/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

236/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

237/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

238/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

239/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

240/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

241/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

242/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

243/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

244/367 ━━━━━━━━━━━━━━━━━━━━ 9s 73ms/step - loss: 0.0013 - mae: 0.0244

245/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

246/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

247/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

248/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

249/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

250/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

251/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

252/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

253/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0243

254/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

255/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

256/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0243

257/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0243

258/367 ━━━━━━━━━━━━━━━━━━━━ 8s 73ms/step - loss: 0.0013 - mae: 0.0244

259/367 ━━━━━━━━━━━━━━━━━━━━ 7s 73ms/step - loss: 0.0013 - mae: 0.0243

260/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0243

261/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0243

262/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0243

263/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0243

264/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0243

265/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0243

266/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0243

267/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0243

268/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0242

269/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0243

270/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0242

271/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0242

272/367 ━━━━━━━━━━━━━━━━━━━━ 7s 74ms/step - loss: 0.0013 - mae: 0.0243

273/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

274/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

275/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

276/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

277/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0242

278/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

279/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

280/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

281/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

282/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

283/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

284/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

285/367 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - loss: 0.0013 - mae: 0.0243

286/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

287/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

288/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

289/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

290/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

291/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

292/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

293/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

294/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

295/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

296/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

297/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

298/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

299/367 ━━━━━━━━━━━━━━━━━━━━ 5s 74ms/step - loss: 0.0013 - mae: 0.0243

300/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0242

301/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0243

302/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0242

303/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0242

304/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0242

305/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0242

306/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0242

307/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0241

308/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0241

309/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0242

310/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0242

311/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0242

312/367 ━━━━━━━━━━━━━━━━━━━━ 4s 74ms/step - loss: 0.0013 - mae: 0.0242

313/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

314/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

315/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

316/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

317/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

318/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

319/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

320/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

321/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

322/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

323/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

324/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0242

325/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0241

326/367 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 0.0013 - mae: 0.0241

327/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0241

328/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0241

329/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

330/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

331/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

332/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

333/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

334/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

335/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

336/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

337/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

338/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

339/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

340/367 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - loss: 0.0013 - mae: 0.0242

341/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

342/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

343/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

344/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

350/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

351/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

352/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

353/367 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - loss: 0.0013 - mae: 0.0242

354/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0242

355/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0242

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0242

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0242

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0242

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0242

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0242

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0242

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0241

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0242

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0241

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0241

366/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0241

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.0013 - mae: 0.0241

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - loss: 0.0013 - mae: 0.0241 - val_loss: 0.0013 - val_mae: 0.0232 - learning_rate: 1.0000e-04

Epoch 11/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 37s 103ms/step - loss: 0.0010 - mae: 0.0240

  3/367 ━━━━━━━━━━━━━━━━━━━━ 18s 51ms/step - loss: 0.0013 - mae: 0.0248

  4/367 ━━━━━━━━━━━━━━━━━━━━ 20s 55ms/step - loss: 0.0012 - mae: 0.0231

  5/367 ━━━━━━━━━━━━━━━━━━━━ 20s 57ms/step - loss: 9.6212e-04 - mae: 0.0207

  6/367 ━━━━━━━━━━━━━━━━━━━━ 21s 59ms/step - loss: 0.0011 - mae: 0.0220

  7/367 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - loss: 0.0011 - mae: 0.0218

  8/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0012 - mae: 0.0227

  9/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0013 - mae: 0.0229

 10/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0014 - mae: 0.0239

 11/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0014 - mae: 0.0239

 12/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0014 - mae: 0.0239

 13/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0013 - mae: 0.0233

 14/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0013 - mae: 0.0235

 15/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0014 - mae: 0.0240

 16/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0014 - mae: 0.0244

 17/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0014 - mae: 0.0247

 18/367 ━━━━━━━━━━━━━━━━━━━━ 23s 68ms/step - loss: 0.0014 - mae: 0.0244

 19/367 ━━━━━━━━━━━━━━━━━━━━ 23s 68ms/step - loss: 0.0014 - mae: 0.0241

 20/367 ━━━━━━━━━━━━━━━━━━━━ 23s 69ms/step - loss: 0.0013 - mae: 0.0238

 21/367 ━━━━━━━━━━━━━━━━━━━━ 23s 69ms/step - loss: 0.0013 - mae: 0.0237

 22/367 ━━━━━━━━━━━━━━━━━━━━ 24s 70ms/step - loss: 0.0013 - mae: 0.0237

 23/367 ━━━━━━━━━━━━━━━━━━━━ 24s 70ms/step - loss: 0.0013 - mae: 0.0236

 24/367 ━━━━━━━━━━━━━━━━━━━━ 23s 70ms/step - loss: 0.0013 - mae: 0.0235

 25/367 ━━━━━━━━━━━━━━━━━━━━ 23s 70ms/step - loss: 0.0013 - mae: 0.0236

 26/367 ━━━━━━━━━━━━━━━━━━━━ 24s 71ms/step - loss: 0.0013 - mae: 0.0237

 27/367 ━━━━━━━━━━━━━━━━━━━━ 24s 71ms/step - loss: 0.0013 - mae: 0.0234

 28/367 ━━━━━━━━━━━━━━━━━━━━ 24s 72ms/step - loss: 0.0013 - mae: 0.0235

 29/367 ━━━━━━━━━━━━━━━━━━━━ 24s 72ms/step - loss: 0.0013 - mae: 0.0236

 31/367 ━━━━━━━━━━━━━━━━━━━━ 23s 71ms/step - loss: 0.0013 - mae: 0.0237

 32/367 ━━━━━━━━━━━━━━━━━━━━ 23s 71ms/step - loss: 0.0013 - mae: 0.0239

 33/367 ━━━━━━━━━━━━━━━━━━━━ 23s 71ms/step - loss: 0.0013 - mae: 0.0237

 34/367 ━━━━━━━━━━━━━━━━━━━━ 23s 71ms/step - loss: 0.0012 - mae: 0.0237

 35/367 ━━━━━━━━━━━━━━━━━━━━ 23s 72ms/step - loss: 0.0012 - mae: 0.0237

 36/367 ━━━━━━━━━━━━━━━━━━━━ 23s 72ms/step - loss: 0.0012 - mae: 0.0236

 37/367 ━━━━━━━━━━━━━━━━━━━━ 24s 74ms/step - loss: 0.0012 - mae: 0.0237

 38/367 ━━━━━━━━━━━━━━━━━━━━ 24s 75ms/step - loss: 0.0012 - mae: 0.0237

 39/367 ━━━━━━━━━━━━━━━━━━━━ 24s 75ms/step - loss: 0.0012 - mae: 0.0237

 40/367 ━━━━━━━━━━━━━━━━━━━━ 24s 76ms/step - loss: 0.0012 - mae: 0.0237

 41/367 ━━━━━━━━━━━━━━━━━━━━ 25s 77ms/step - loss: 0.0012 - mae: 0.0237

 42/367 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - loss: 0.0012 - mae: 0.0236

 43/367 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - loss: 0.0012 - mae: 0.0235

 44/367 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - loss: 0.0012 - mae: 0.0236

 45/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0012 - mae: 0.0235

 46/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0012 - mae: 0.0234

 47/367 ━━━━━━━━━━━━━━━━━━━━ 27s 84ms/step - loss: 0.0012 - mae: 0.0236

 48/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0012 - mae: 0.0235

 49/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0012 - mae: 0.0233

 50/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0012 - mae: 0.0234

 51/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0012 - mae: 0.0233

 52/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0012 - mae: 0.0233

 53/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0012 - mae: 0.0233

 54/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0012 - mae: 0.0231

 55/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0012 - mae: 0.0230

 56/367 ━━━━━━━━━━━━━━━━━━━━ 25s 83ms/step - loss: 0.0012 - mae: 0.0232

 57/367 ━━━━━━━━━━━━━━━━━━━━ 25s 83ms/step - loss: 0.0012 - mae: 0.0232

 58/367 ━━━━━━━━━━━━━━━━━━━━ 25s 83ms/step - loss: 0.0012 - mae: 0.0232

 59/367 ━━━━━━━━━━━━━━━━━━━━ 25s 83ms/step - loss: 0.0012 - mae: 0.0232

 60/367 ━━━━━━━━━━━━━━━━━━━━ 25s 83ms/step - loss: 0.0012 - mae: 0.0232

 61/367 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - loss: 0.0012 - mae: 0.0232

 62/367 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - loss: 0.0012 - mae: 0.0231

 63/367 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - loss: 0.0012 - mae: 0.0232

 64/367 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - loss: 0.0012 - mae: 0.0232

 65/367 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - loss: 0.0012 - mae: 0.0232

 66/367 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - loss: 0.0012 - mae: 0.0232

 67/367 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - loss: 0.0012 - mae: 0.0232

 68/367 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - loss: 0.0012 - mae: 0.0232

 69/367 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - loss: 0.0012 - mae: 0.0231

 70/367 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - loss: 0.0012 - mae: 0.0230

 71/367 ━━━━━━━━━━━━━━━━━━━━ 24s 81ms/step - loss: 0.0012 - mae: 0.0230

 72/367 ━━━━━━━━━━━━━━━━━━━━ 23s 81ms/step - loss: 0.0011 - mae: 0.0230

 73/367 ━━━━━━━━━━━━━━━━━━━━ 23s 81ms/step - loss: 0.0012 - mae: 0.0230

 74/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0230

 75/367 ━━━━━━━━━━━━━━━━━━━━ 23s 81ms/step - loss: 0.0012 - mae: 0.0231

 76/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0230

 77/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0230

 78/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0230

 79/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0230

 80/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0231

 81/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0231

 82/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0232

 83/367 ━━━━━━━━━━━━━━━━━━━━ 23s 83ms/step - loss: 0.0012 - mae: 0.0232

 84/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0232

 85/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0232

 86/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0232

 87/367 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - loss: 0.0012 - mae: 0.0232

 88/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0232

 89/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0232

 90/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0232

 91/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0232

 92/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0232

 93/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0233

 94/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0232

 95/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0233

 96/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0233

 97/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0233

 98/367 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - loss: 0.0012 - mae: 0.0233

 99/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0233

100/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0233

101/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0233

102/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0233

103/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0232

104/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0233

105/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0232

106/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0233

107/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0233

108/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0233

109/367 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - loss: 0.0012 - mae: 0.0233

110/367 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - loss: 0.0012 - mae: 0.0233

111/367 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - loss: 0.0012 - mae: 0.0233

112/367 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - loss: 0.0012 - mae: 0.0233

113/367 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - loss: 0.0012 - mae: 0.0233

114/367 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - loss: 0.0012 - mae: 0.0233

115/367 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - loss: 0.0012 - mae: 0.0234

116/367 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - loss: 0.0012 - mae: 0.0233

117/367 ━━━━━━━━━━━━━━━━━━━━ 20s 81ms/step - loss: 0.0012 - mae: 0.0233

118/367 ━━━━━━━━━━━━━━━━━━━━ 20s 81ms/step - loss: 0.0012 - mae: 0.0232

119/367 ━━━━━━━━━━━━━━━━━━━━ 20s 81ms/step - loss: 0.0012 - mae: 0.0232

120/367 ━━━━━━━━━━━━━━━━━━━━ 20s 81ms/step - loss: 0.0012 - mae: 0.0232

121/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0232

122/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0232

123/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0233

124/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0233

125/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0233

126/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0232

127/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0232

128/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0232

129/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0232

130/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0232

131/367 ━━━━━━━━━━━━━━━━━━━━ 19s 81ms/step - loss: 0.0012 - mae: 0.0232

132/367 ━━━━━━━━━━━━━━━━━━━━ 18s 81ms/step - loss: 0.0012 - mae: 0.0232

133/367 ━━━━━━━━━━━━━━━━━━━━ 18s 81ms/step - loss: 0.0012 - mae: 0.0232

134/367 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - loss: 0.0012 - mae: 0.0232

135/367 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - loss: 0.0012 - mae: 0.0232

136/367 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - loss: 0.0012 - mae: 0.0231

137/367 ━━━━━━━━━━━━━━━━━━━━ 18s 81ms/step - loss: 0.0012 - mae: 0.0231

138/367 ━━━━━━━━━━━━━━━━━━━━ 18s 81ms/step - loss: 0.0012 - mae: 0.0230

139/367 ━━━━━━━━━━━━━━━━━━━━ 18s 81ms/step - loss: 0.0012 - mae: 0.0230

140/367 ━━━━━━━━━━━━━━━━━━━━ 18s 81ms/step - loss: 0.0012 - mae: 0.0230

141/367 ━━━━━━━━━━━━━━━━━━━━ 18s 81ms/step - loss: 0.0012 - mae: 0.0230

142/367 ━━━━━━━━━━━━━━━━━━━━ 18s 81ms/step - loss: 0.0011 - mae: 0.0229

143/367 ━━━━━━━━━━━━━━━━━━━━ 18s 81ms/step - loss: 0.0011 - mae: 0.0229

144/367 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - loss: 0.0011 - mae: 0.0229

145/367 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - loss: 0.0012 - mae: 0.0229

146/367 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - loss: 0.0011 - mae: 0.0229

147/367 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - loss: 0.0011 - mae: 0.0229

148/367 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - loss: 0.0011 - mae: 0.0229

149/367 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - loss: 0.0011 - mae: 0.0229

150/367 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - loss: 0.0011 - mae: 0.0229

151/367 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - loss: 0.0011 - mae: 0.0229

152/367 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - loss: 0.0011 - mae: 0.0229

153/367 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - loss: 0.0011 - mae: 0.0229

154/367 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - loss: 0.0011 - mae: 0.0229

155/367 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - loss: 0.0011 - mae: 0.0229

156/367 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - loss: 0.0012 - mae: 0.0230

157/367 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - loss: 0.0011 - mae: 0.0229

158/367 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - loss: 0.0011 - mae: 0.0229

159/367 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - loss: 0.0011 - mae: 0.0229

160/367 ━━━━━━━━━━━━━━━━━━━━ 16s 79ms/step - loss: 0.0011 - mae: 0.0229

161/367 ━━━━━━━━━━━━━━━━━━━━ 16s 79ms/step - loss: 0.0011 - mae: 0.0229

162/367 ━━━━━━━━━━━━━━━━━━━━ 16s 79ms/step - loss: 0.0011 - mae: 0.0229

163/367 ━━━━━━━━━━━━━━━━━━━━ 16s 79ms/step - loss: 0.0011 - mae: 0.0229

164/367 ━━━━━━━━━━━━━━━━━━━━ 16s 79ms/step - loss: 0.0011 - mae: 0.0229

165/367 ━━━━━━━━━━━━━━━━━━━━ 16s 79ms/step - loss: 0.0011 - mae: 0.0229

166/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0011 - mae: 0.0229

167/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0011 - mae: 0.0229

168/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0011 - mae: 0.0229

169/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0011 - mae: 0.0229

170/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0012 - mae: 0.0230

171/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0012 - mae: 0.0230

172/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0012 - mae: 0.0231

173/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0012 - mae: 0.0230

174/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0012 - mae: 0.0230

175/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0012 - mae: 0.0230

176/367 ━━━━━━━━━━━━━━━━━━━━ 15s 79ms/step - loss: 0.0012 - mae: 0.0230

177/367 ━━━━━━━━━━━━━━━━━━━━ 14s 79ms/step - loss: 0.0012 - mae: 0.0230

178/367 ━━━━━━━━━━━━━━━━━━━━ 14s 79ms/step - loss: 0.0012 - mae: 0.0231

179/367 ━━━━━━━━━━━━━━━━━━━━ 14s 79ms/step - loss: 0.0012 - mae: 0.0231

180/367 ━━━━━━━━━━━━━━━━━━━━ 14s 79ms/step - loss: 0.0012 - mae: 0.0232

181/367 ━━━━━━━━━━━━━━━━━━━━ 14s 79ms/step - loss: 0.0012 - mae: 0.0232

182/367 ━━━━━━━━━━━━━━━━━━━━ 14s 79ms/step - loss: 0.0012 - mae: 0.0232

183/367 ━━━━━━━━━━━━━━━━━━━━ 14s 78ms/step - loss: 0.0012 - mae: 0.0232

184/367 ━━━━━━━━━━━━━━━━━━━━ 14s 78ms/step - loss: 0.0012 - mae: 0.0232

185/367 ━━━━━━━━━━━━━━━━━━━━ 14s 78ms/step - loss: 0.0012 - mae: 0.0232

186/367 ━━━━━━━━━━━━━━━━━━━━ 14s 78ms/step - loss: 0.0012 - mae: 0.0232

187/367 ━━━━━━━━━━━━━━━━━━━━ 14s 78ms/step - loss: 0.0012 - mae: 0.0231

188/367 ━━━━━━━━━━━━━━━━━━━━ 14s 78ms/step - loss: 0.0012 - mae: 0.0232

189/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

190/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

191/367 ━━━━━━━━━━━━━━━━━━━━ 13s 79ms/step - loss: 0.0012 - mae: 0.0231

192/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

193/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

194/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

195/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

196/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

197/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

198/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

199/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

200/367 ━━━━━━━━━━━━━━━━━━━━ 13s 78ms/step - loss: 0.0012 - mae: 0.0231

201/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0231

202/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0231

203/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0231

204/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0231

205/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0231

206/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0232

207/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0232

208/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0232

209/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0232

210/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0232

211/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0232

212/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0232

213/367 ━━━━━━━━━━━━━━━━━━━━ 12s 78ms/step - loss: 0.0012 - mae: 0.0232

214/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0232

215/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0232

216/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0232

217/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0232

218/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0231

219/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0231

220/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0231

221/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0231

222/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0231

223/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0231

224/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0231

225/367 ━━━━━━━━━━━━━━━━━━━━ 11s 78ms/step - loss: 0.0012 - mae: 0.0231

226/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0231

227/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0231

228/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0231

229/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0231

230/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0232

231/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0232

232/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0231

233/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0231

234/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0231

235/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0231

236/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0231

237/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0012 - mae: 0.0231

238/367 ━━━━━━━━━━━━━━━━━━━━ 10s 78ms/step - loss: 0.0011 - mae: 0.0231

239/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0011 - mae: 0.0230

240/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0012 - mae: 0.0231

241/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0011 - mae: 0.0230

242/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0011 - mae: 0.0230

243/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0011 - mae: 0.0230

244/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0011 - mae: 0.0230

245/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0011 - mae: 0.0230

246/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0012 - mae: 0.0231

247/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0012 - mae: 0.0231

248/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0012 - mae: 0.0231

249/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0012 - mae: 0.0231

250/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0012 - mae: 0.0231

251/367 ━━━━━━━━━━━━━━━━━━━━ 9s 78ms/step - loss: 0.0012 - mae: 0.0231

252/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

253/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

254/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

255/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

256/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

257/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

258/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

259/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

260/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

261/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

262/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

263/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0231

264/367 ━━━━━━━━━━━━━━━━━━━━ 8s 78ms/step - loss: 0.0012 - mae: 0.0232

265/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0232

266/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

267/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

268/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

269/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

270/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

271/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

272/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

273/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

274/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

275/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

276/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

277/367 ━━━━━━━━━━━━━━━━━━━━ 7s 78ms/step - loss: 0.0012 - mae: 0.0231

278/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0012 - mae: 0.0230

279/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0012 - mae: 0.0231

280/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0012 - mae: 0.0231

281/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0012 - mae: 0.0230

282/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0012 - mae: 0.0230

283/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0012 - mae: 0.0230

284/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0012 - mae: 0.0230

285/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0011 - mae: 0.0230

286/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0012 - mae: 0.0230

287/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0012 - mae: 0.0230

288/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0012 - mae: 0.0230

289/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0011 - mae: 0.0230

290/367 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - loss: 0.0011 - mae: 0.0230

291/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0230

292/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0230

293/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0230

294/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0230

295/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0230

296/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0229

297/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0229

298/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0229

299/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0229

300/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0229

301/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0229

302/367 ━━━━━━━━━━━━━━━━━━━━ 5s 78ms/step - loss: 0.0011 - mae: 0.0229

303/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

304/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

305/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

306/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

307/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

308/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

309/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

310/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

311/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

312/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

313/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

314/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

315/367 ━━━━━━━━━━━━━━━━━━━━ 4s 78ms/step - loss: 0.0011 - mae: 0.0229

316/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

317/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

318/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

319/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

320/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

321/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

322/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

323/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

324/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0229

325/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

326/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

327/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

328/367 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 0.0011 - mae: 0.0228

329/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

330/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

331/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

332/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

333/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

334/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

335/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

336/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

337/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

338/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

339/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

340/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0228

341/367 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - loss: 0.0011 - mae: 0.0227

342/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

343/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

344/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

350/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

351/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

352/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

353/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

354/367 ━━━━━━━━━━━━━━━━━━━━ 1s 78ms/step - loss: 0.0011 - mae: 0.0227

355/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

366/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0011 - mae: 0.0227

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 31s 85ms/step - loss: 0.0011 - mae: 0.0227 - val_loss: 0.0013 - val_mae: 0.0231 - learning_rate: 1.0000e-04

Epoch 12/12

  1/367 ━━━━━━━━━━━━━━━━━━━━ 38s 104ms/step - loss: 7.4012e-04 - mae: 0.0192

  2/367 ━━━━━━━━━━━━━━━━━━━━ 23s 63ms/step - loss: 8.9621e-04 - mae: 0.0219

  4/367 ━━━━━━━━━━━━━━━━━━━━ 20s 56ms/step - loss: 0.0014 - mae: 0.0267

  5/367 ━━━━━━━━━━━━━━━━━━━━ 21s 60ms/step - loss: 0.0014 - mae: 0.0264

  6/367 ━━━━━━━━━━━━━━━━━━━━ 22s 63ms/step - loss: 0.0013 - mae: 0.0253

  7/367 ━━━━━━━━━━━━━━━━━━━━ 23s 64ms/step - loss: 0.0012 - mae: 0.0240

  8/367 ━━━━━━━━━━━━━━━━━━━━ 23s 66ms/step - loss: 0.0012 - mae: 0.0238

  9/367 ━━━━━━━━━━━━━━━━━━━━ 23s 67ms/step - loss: 0.0012 - mae: 0.0233

 10/367 ━━━━━━━━━━━━━━━━━━━━ 24s 67ms/step - loss: 0.0011 - mae: 0.0228

 11/367 ━━━━━━━━━━━━━━━━━━━━ 24s 68ms/step - loss: 0.0011 - mae: 0.0224

 12/367 ━━━━━━━━━━━━━━━━━━━━ 24s 69ms/step - loss: 0.0010 - mae: 0.0220

 13/367 ━━━━━━━━━━━━━━━━━━━━ 25s 71ms/step - loss: 0.0010 - mae: 0.0218

 14/367 ━━━━━━━━━━━━━━━━━━━━ 25s 71ms/step - loss: 9.9741e-04 - mae: 0.0216

 15/367 ━━━━━━━━━━━━━━━━━━━━ 25s 71ms/step - loss: 9.6157e-04 - mae: 0.0212

 16/367 ━━━━━━━━━━━━━━━━━━━━ 25s 71ms/step - loss: 9.4353e-04 - mae: 0.0211

 17/367 ━━━━━━━━━━━━━━━━━━━━ 25s 72ms/step - loss: 9.8500e-04 - mae: 0.0213

 18/367 ━━━━━━━━━━━━━━━━━━━━ 25s 72ms/step - loss: 9.8740e-04 - mae: 0.0212

 19/367 ━━━━━━━━━━━━━━━━━━━━ 25s 73ms/step - loss: 9.8791e-04 - mae: 0.0212

 20/367 ━━━━━━━━━━━━━━━━━━━━ 25s 73ms/step - loss: 9.9056e-04 - mae: 0.0212

 21/367 ━━━━━━━━━━━━━━━━━━━━ 25s 74ms/step - loss: 0.0010 - mae: 0.0215

 22/367 ━━━━━━━━━━━━━━━━━━━━ 25s 74ms/step - loss: 9.9119e-04 - mae: 0.0213

 23/367 ━━━━━━━━━━━━━━━━━━━━ 25s 75ms/step - loss: 9.7755e-04 - mae: 0.0212

 24/367 ━━━━━━━━━━━━━━━━━━━━ 25s 75ms/step - loss: 0.0010 - mae: 0.0215

 25/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0010 - mae: 0.0217

 26/367 ━━━━━━━━━━━━━━━━━━━━ 26s 77ms/step - loss: 0.0010 - mae: 0.0216

 27/367 ━━━━━━━━━━━━━━━━━━━━ 26s 77ms/step - loss: 0.0010 - mae: 0.0214

 28/367 ━━━━━━━━━━━━━━━━━━━━ 26s 77ms/step - loss: 0.0010 - mae: 0.0215

 29/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0010 - mae: 0.0218

 30/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0011 - mae: 0.0219

 31/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0011 - mae: 0.0220

 32/367 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - loss: 0.0011 - mae: 0.0220

 33/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0011 - mae: 0.0222

 34/367 ━━━━━━━━━━━━━━━━━━━━ 26s 78ms/step - loss: 0.0011 - mae: 0.0222

 35/367 ━━━━━━━━━━━━━━━━━━━━ 25s 78ms/step - loss: 0.0011 - mae: 0.0222

 36/367 ━━━━━━━━━━━━━━━━━━━━ 25s 78ms/step - loss: 0.0011 - mae: 0.0222

 37/367 ━━━━━━━━━━━━━━━━━━━━ 25s 78ms/step - loss: 0.0011 - mae: 0.0221

 38/367 ━━━━━━━━━━━━━━━━━━━━ 25s 78ms/step - loss: 0.0011 - mae: 0.0222

 39/367 ━━━━━━━━━━━━━━━━━━━━ 25s 78ms/step - loss: 0.0011 - mae: 0.0221

 40/367 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - loss: 0.0011 - mae: 0.0219

 41/367 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - loss: 0.0010 - mae: 0.0218

 42/367 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - loss: 0.0010 - mae: 0.0216

 43/367 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - loss: 0.0010 - mae: 0.0215

 44/367 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - loss: 0.0010 - mae: 0.0216

 45/367 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - loss: 0.0010 - mae: 0.0216

 46/367 ━━━━━━━━━━━━━━━━━━━━ 25s 81ms/step - loss: 0.0010 - mae: 0.0216

 47/367 ━━━━━━━━━━━━━━━━━━━━ 25s 81ms/step - loss: 0.0010 - mae: 0.0217

 48/367 ━━━━━━━━━━━━━━━━━━━━ 25s 81ms/step - loss: 0.0010 - mae: 0.0216

 49/367 ━━━━━━━━━━━━━━━━━━━━ 25s 81ms/step - loss: 0.0010 - mae: 0.0216

 50/367 ━━━━━━━━━━━━━━━━━━━━ 25s 81ms/step - loss: 0.0010 - mae: 0.0215

 51/367 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - loss: 0.0010 - mae: 0.0215

 52/367 ━━━━━━━━━━━━━━━━━━━━ 26s 83ms/step - loss: 0.0010 - mae: 0.0215

 53/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0010 - mae: 0.0215

 54/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0010 - mae: 0.0216

 55/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0010 - mae: 0.0216

 56/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0010 - mae: 0.0216

 57/367 ━━━━━━━━━━━━━━━━━━━━ 26s 84ms/step - loss: 0.0010 - mae: 0.0215

 58/367 ━━━━━━━━━━━━━━━━━━━━ 25s 84ms/step - loss: 0.0010 - mae: 0.0215

 59/367 ━━━━━━━━━━━━━━━━━━━━ 26s 86ms/step - loss: 0.0010 - mae: 0.0216

 60/367 ━━━━━━━━━━━━━━━━━━━━ 26s 86ms/step - loss: 0.0010 - mae: 0.0215

 61/367 ━━━━━━━━━━━━━━━━━━━━ 26s 86ms/step - loss: 0.0010 - mae: 0.0216

 62/367 ━━━━━━━━━━━━━━━━━━━━ 26s 86ms/step - loss: 0.0010 - mae: 0.0215

 63/367 ━━━━━━━━━━━━━━━━━━━━ 26s 86ms/step - loss: 0.0010 - mae: 0.0215

 64/367 ━━━━━━━━━━━━━━━━━━━━ 26s 86ms/step - loss: 0.0010 - mae: 0.0215

 65/367 ━━━━━━━━━━━━━━━━━━━━ 26s 86ms/step - loss: 9.9804e-04 - mae: 0.0214

 66/367 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - loss: 0.0010 - mae: 0.0215

 67/367 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - loss: 0.0010 - mae: 0.0215

 68/367 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - loss: 0.0010 - mae: 0.0215

 69/367 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - loss: 0.0010 - mae: 0.0216

 70/367 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - loss: 0.0010 - mae: 0.0215

 71/367 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - loss: 0.0010 - mae: 0.0215

 72/367 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - loss: 0.0010 - mae: 0.0215

 73/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 0.0010 - mae: 0.0215

 74/367 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - loss: 9.9731e-04 - mae: 0.0215

 75/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0010 - mae: 0.0216

 76/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0010 - mae: 0.0216

 77/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0010 - mae: 0.0216

 78/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0010 - mae: 0.0217

 79/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0010 - mae: 0.0216

 80/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0010 - mae: 0.0215

 81/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 9.9963e-04 - mae: 0.0216

 82/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0010 - mae: 0.0216

 83/367 ━━━━━━━━━━━━━━━━━━━━ 24s 85ms/step - loss: 0.0010 - mae: 0.0217

 84/367 ━━━━━━━━━━━━━━━━━━━━ 23s 85ms/step - loss: 0.0010 - mae: 0.0217

 85/367 ━━━━━━━━━━━━━━━━━━━━ 23s 85ms/step - loss: 0.0010 - mae: 0.0216

 86/367 ━━━━━━━━━━━━━━━━━━━━ 23s 85ms/step - loss: 0.0010 - mae: 0.0216

 87/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0010 - mae: 0.0216

 88/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0010 - mae: 0.0216

 89/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0010 - mae: 0.0217

 90/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0010 - mae: 0.0216

 91/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0010 - mae: 0.0216

 92/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 9.9947e-04 - mae: 0.0215

 93/367 ━━━━━━━━━━━━━━━━━━━━ 23s 84ms/step - loss: 0.0010 - mae: 0.0216

 94/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0010 - mae: 0.0216

 95/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0010 - mae: 0.0216

 96/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0010 - mae: 0.0216

 97/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0010 - mae: 0.0215

 98/367 ━━━━━━━━━━━━━━━━━━━━ 22s 84ms/step - loss: 0.0010 - mae: 0.0215

 99/367 ━━━━━━━━━━━━━━━━━━━━ 22s 85ms/step - loss: 0.0010 - mae: 0.0215

100/367 ━━━━━━━━━━━━━━━━━━━━ 22s 85ms/step - loss: 0.0010 - mae: 0.0215

101/367 ━━━━━━━━━━━━━━━━━━━━ 22s 85ms/step - loss: 9.9799e-04 - mae: 0.0215

102/367 ━━━━━━━━━━━━━━━━━━━━ 22s 85ms/step - loss: 9.9596e-04 - mae: 0.0215

103/367 ━━━━━━━━━━━━━━━━━━━━ 22s 85ms/step - loss: 9.9388e-04 - mae: 0.0215

104/367 ━━━━━━━━━━━━━━━━━━━━ 22s 85ms/step - loss: 0.0010 - mae: 0.0216

105/367 ━━━━━━━━━━━━━━━━━━━━ 22s 85ms/step - loss: 9.9665e-04 - mae: 0.0215

106/367 ━━━━━━━━━━━━━━━━━━━━ 22s 85ms/step - loss: 9.9597e-04 - mae: 0.0215

107/367 ━━━━━━━━━━━━━━━━━━━━ 21s 85ms/step - loss: 9.9560e-04 - mae: 0.0215

108/367 ━━━━━━━━━━━━━━━━━━━━ 21s 84ms/step - loss: 9.9601e-04 - mae: 0.0215

109/367 ━━━━━━━━━━━━━━━━━━━━ 21s 84ms/step - loss: 9.9502e-04 - mae: 0.0215

110/367 ━━━━━━━━━━━━━━━━━━━━ 21s 84ms/step - loss: 9.9204e-04 - mae: 0.0214

111/367 ━━━━━━━━━━━━━━━━━━━━ 21s 84ms/step - loss: 9.8960e-04 - mae: 0.0214

112/367 ━━━━━━━━━━━━━━━━━━━━ 21s 84ms/step - loss: 9.9088e-04 - mae: 0.0215

113/367 ━━━━━━━━━━━━━━━━━━━━ 21s 84ms/step - loss: 9.9458e-04 - mae: 0.0215

114/367 ━━━━━━━━━━━━━━━━━━━━ 21s 84ms/step - loss: 9.9840e-04 - mae: 0.0215

115/367 ━━━━━━━━━━━━━━━━━━━━ 21s 84ms/step - loss: 0.0010 - mae: 0.0216

116/367 ━━━━━━━━━━━━━━━━━━━━ 21s 84ms/step - loss: 9.9725e-04 - mae: 0.0215

117/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 0.0010 - mae: 0.0215

118/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 0.0010 - mae: 0.0215

119/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 0.0010 - mae: 0.0216

120/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 0.0010 - mae: 0.0215

121/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 0.0010 - mae: 0.0215

122/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 9.9896e-04 - mae: 0.0214

123/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 9.9897e-04 - mae: 0.0214

124/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 9.9487e-04 - mae: 0.0214

125/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 9.9157e-04 - mae: 0.0213

126/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 9.8752e-04 - mae: 0.0213

127/367 ━━━━━━━━━━━━━━━━━━━━ 20s 84ms/step - loss: 9.8647e-04 - mae: 0.0213

128/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 9.8935e-04 - mae: 0.0213

129/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 9.8728e-04 - mae: 0.0213

130/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 9.9033e-04 - mae: 0.0213

131/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 9.8681e-04 - mae: 0.0213

132/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 9.8846e-04 - mae: 0.0213

133/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 9.8879e-04 - mae: 0.0213

134/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 9.8648e-04 - mae: 0.0213

135/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 9.8257e-04 - mae: 0.0212

136/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 9.8130e-04 - mae: 0.0212

137/367 ━━━━━━━━━━━━━━━━━━━━ 19s 83ms/step - loss: 9.8131e-04 - mae: 0.0212

138/367 ━━━━━━━━━━━━━━━━━━━━ 18s 83ms/step - loss: 9.8859e-04 - mae: 0.0213

139/367 ━━━━━━━━━━━━━━━━━━━━ 18s 83ms/step - loss: 9.8815e-04 - mae: 0.0213

140/367 ━━━━━━━━━━━━━━━━━━━━ 18s 83ms/step - loss: 9.8352e-04 - mae: 0.0212

141/367 ━━━━━━━━━━━━━━━━━━━━ 18s 83ms/step - loss: 9.8447e-04 - mae: 0.0212

142/367 ━━━━━━━━━━━━━━━━━━━━ 18s 83ms/step - loss: 9.9078e-04 - mae: 0.0213

143/367 ━━━━━━━━━━━━━━━━━━━━ 18s 83ms/step - loss: 9.8946e-04 - mae: 0.0213

144/367 ━━━━━━━━━━━━━━━━━━━━ 18s 83ms/step - loss: 9.8840e-04 - mae: 0.0213

145/367 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - loss: 9.8637e-04 - mae: 0.0213

146/367 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - loss: 9.8274e-04 - mae: 0.0213

147/367 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - loss: 9.8164e-04 - mae: 0.0212

148/367 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - loss: 9.7963e-04 - mae: 0.0212

149/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.7657e-04 - mae: 0.0212

150/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.7237e-04 - mae: 0.0212

151/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.7553e-04 - mae: 0.0212

152/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.7284e-04 - mae: 0.0211

153/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.6918e-04 - mae: 0.0211

154/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.6781e-04 - mae: 0.0211

155/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.6714e-04 - mae: 0.0211

156/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.6762e-04 - mae: 0.0211

157/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.6457e-04 - mae: 0.0210

158/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.6476e-04 - mae: 0.0210

159/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.6827e-04 - mae: 0.0211

160/367 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - loss: 9.7039e-04 - mae: 0.0211

161/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7260e-04 - mae: 0.0211

162/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7091e-04 - mae: 0.0211

163/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7546e-04 - mae: 0.0212

164/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7532e-04 - mae: 0.0212

165/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7549e-04 - mae: 0.0211

166/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7190e-04 - mae: 0.0211

167/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7331e-04 - mae: 0.0211

168/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7460e-04 - mae: 0.0211

169/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7242e-04 - mae: 0.0211

170/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7637e-04 - mae: 0.0211

171/367 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - loss: 9.7407e-04 - mae: 0.0211

172/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.7324e-04 - mae: 0.0211

173/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.7091e-04 - mae: 0.0211

174/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.7002e-04 - mae: 0.0211

175/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.6773e-04 - mae: 0.0211

176/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.6587e-04 - mae: 0.0210

177/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.6255e-04 - mae: 0.0210

178/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.6779e-04 - mae: 0.0210

179/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.6683e-04 - mae: 0.0210

180/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.6356e-04 - mae: 0.0210

181/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.6296e-04 - mae: 0.0210

182/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.6606e-04 - mae: 0.0210

183/367 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - loss: 9.6504e-04 - mae: 0.0210

184/367 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - loss: 9.6316e-04 - mae: 0.0210

185/367 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - loss: 9.6077e-04 - mae: 0.0210

186/367 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - loss: 9.5877e-04 - mae: 0.0209

187/367 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - loss: 9.5862e-04 - mae: 0.0210

188/367 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - loss: 9.5754e-04 - mae: 0.0209

189/367 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - loss: 9.5740e-04 - mae: 0.0209

190/367 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - loss: 9.5602e-04 - mae: 0.0209

191/367 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - loss: 9.5426e-04 - mae: 0.0209

192/367 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - loss: 9.5344e-04 - mae: 0.0209

193/367 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - loss: 9.5924e-04 - mae: 0.0209

194/367 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - loss: 9.5734e-04 - mae: 0.0209

195/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.5745e-04 - mae: 0.0209

196/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.5766e-04 - mae: 0.0209

197/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.5472e-04 - mae: 0.0209

198/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.5963e-04 - mae: 0.0209

199/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.5794e-04 - mae: 0.0209

200/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.6016e-04 - mae: 0.0209

201/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.6186e-04 - mae: 0.0210

202/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.6364e-04 - mae: 0.0210

203/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.6438e-04 - mae: 0.0210

204/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.6495e-04 - mae: 0.0210

205/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.6277e-04 - mae: 0.0210

206/367 ━━━━━━━━━━━━━━━━━━━━ 13s 81ms/step - loss: 9.6623e-04 - mae: 0.0210

207/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.6878e-04 - mae: 0.0210

208/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.7137e-04 - mae: 0.0210

209/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.7114e-04 - mae: 0.0210

210/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.7032e-04 - mae: 0.0210

211/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.7628e-04 - mae: 0.0211

212/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.7396e-04 - mae: 0.0211

213/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.9734e-04 - mae: 0.0211

214/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.9607e-04 - mae: 0.0211

215/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.9737e-04 - mae: 0.0211

216/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.9639e-04 - mae: 0.0211

217/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.9922e-04 - mae: 0.0211

218/367 ━━━━━━━━━━━━━━━━━━━━ 12s 81ms/step - loss: 9.9683e-04 - mae: 0.0211

219/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9880e-04 - mae: 0.0212

220/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9744e-04 - mae: 0.0211

221/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9766e-04 - mae: 0.0211

222/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9721e-04 - mae: 0.0211

223/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9685e-04 - mae: 0.0211

224/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9624e-04 - mae: 0.0212

225/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9602e-04 - mae: 0.0212

226/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9506e-04 - mae: 0.0212

227/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9387e-04 - mae: 0.0212

228/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9416e-04 - mae: 0.0212

229/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 9.9623e-04 - mae: 0.0212

230/367 ━━━━━━━━━━━━━━━━━━━━ 11s 81ms/step - loss: 0.0010 - mae: 0.0212

231/367 ━━━━━━━━━━━━━━━━━━━━ 10s 81ms/step - loss: 9.9890e-04 - mae: 0.0212

232/367 ━━━━━━━━━━━━━━━━━━━━ 10s 81ms/step - loss: 9.9707e-04 - mae: 0.0212

233/367 ━━━━━━━━━━━━━━━━━━━━ 10s 81ms/step - loss: 9.9547e-04 - mae: 0.0212

234/367 ━━━━━━━━━━━━━━━━━━━━ 10s 81ms/step - loss: 9.9316e-04 - mae: 0.0212

235/367 ━━━━━━━━━━━━━━━━━━━━ 10s 81ms/step - loss: 9.9495e-04 - mae: 0.0212

236/367 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - loss: 9.9377e-04 - mae: 0.0212

237/367 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - loss: 9.9243e-04 - mae: 0.0212

238/367 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - loss: 9.9185e-04 - mae: 0.0212

239/367 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - loss: 9.8905e-04 - mae: 0.0211

240/367 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - loss: 9.8765e-04 - mae: 0.0211

241/367 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - loss: 9.8603e-04 - mae: 0.0211

242/367 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - loss: 9.8910e-04 - mae: 0.0211

243/367 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - loss: 9.8917e-04 - mae: 0.0211

244/367 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - loss: 9.8778e-04 - mae: 0.0211

245/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.8890e-04 - mae: 0.0211

246/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.9015e-04 - mae: 0.0211

247/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.9343e-04 - mae: 0.0211

248/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.9320e-04 - mae: 0.0211

249/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.9125e-04 - mae: 0.0211

250/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.8857e-04 - mae: 0.0211

251/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.9112e-04 - mae: 0.0211

252/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.9288e-04 - mae: 0.0211

253/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.9109e-04 - mae: 0.0211

254/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.9255e-04 - mae: 0.0211

255/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.9191e-04 - mae: 0.0211

256/367 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - loss: 9.9140e-04 - mae: 0.0211

257/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.9370e-04 - mae: 0.0211

258/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.9403e-04 - mae: 0.0211

259/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.9385e-04 - mae: 0.0211

260/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.9167e-04 - mae: 0.0211

261/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.9135e-04 - mae: 0.0211

262/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.9081e-04 - mae: 0.0211

263/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.8862e-04 - mae: 0.0211

264/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.8814e-04 - mae: 0.0211

265/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.8792e-04 - mae: 0.0211

266/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.9008e-04 - mae: 0.0211

267/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.8984e-04 - mae: 0.0211

268/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.9283e-04 - mae: 0.0211

269/367 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - loss: 9.9426e-04 - mae: 0.0211

270/367 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - loss: 9.9368e-04 - mae: 0.0211

271/367 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - loss: 9.9238e-04 - mae: 0.0211

272/367 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - loss: 9.9203e-04 - mae: 0.0211

273/367 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - loss: 9.9204e-04 - mae: 0.0211

274/367 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - loss: 9.9098e-04 - mae: 0.0211

275/367 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - loss: 9.9191e-04 - mae: 0.0211

276/367 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - loss: 9.9280e-04 - mae: 0.0212

277/367 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - loss: 9.9359e-04 - mae: 0.0212

278/367 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - loss: 9.9388e-04 - mae: 0.0212

279/367 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - loss: 9.9651e-04 - mae: 0.0212

280/367 ━━━━━━━━━━━━━━━━━━━━ 7s 81ms/step - loss: 9.9692e-04 - mae: 0.0212

281/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9675e-04 - mae: 0.0212

282/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9861e-04 - mae: 0.0212

283/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9666e-04 - mae: 0.0212

284/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9661e-04 - mae: 0.0212

285/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9579e-04 - mae: 0.0212

286/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9881e-04 - mae: 0.0212

287/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9862e-04 - mae: 0.0212

288/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9859e-04 - mae: 0.0212

289/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9902e-04 - mae: 0.0212

290/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9749e-04 - mae: 0.0212

291/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9641e-04 - mae: 0.0212

292/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9568e-04 - mae: 0.0212

293/367 ━━━━━━━━━━━━━━━━━━━━ 6s 81ms/step - loss: 9.9396e-04 - mae: 0.0212

294/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9197e-04 - mae: 0.0212

295/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9203e-04 - mae: 0.0212

296/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9205e-04 - mae: 0.0212

297/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9491e-04 - mae: 0.0212

298/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9565e-04 - mae: 0.0212

299/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9349e-04 - mae: 0.0212

300/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9202e-04 - mae: 0.0212

301/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9558e-04 - mae: 0.0212

302/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9523e-04 - mae: 0.0212

303/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9593e-04 - mae: 0.0212

304/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9397e-04 - mae: 0.0212

305/367 ━━━━━━━━━━━━━━━━━━━━ 5s 81ms/step - loss: 9.9324e-04 - mae: 0.0212

306/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9216e-04 - mae: 0.0212

307/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9024e-04 - mae: 0.0211

308/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9382e-04 - mae: 0.0212

309/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9456e-04 - mae: 0.0212

310/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9820e-04 - mae: 0.0212

311/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9648e-04 - mae: 0.0212

312/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9695e-04 - mae: 0.0212

313/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9621e-04 - mae: 0.0212

314/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9555e-04 - mae: 0.0212

315/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9495e-04 - mae: 0.0212

316/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9397e-04 - mae: 0.0212

317/367 ━━━━━━━━━━━━━━━━━━━━ 4s 81ms/step - loss: 9.9367e-04 - mae: 0.0212

318/367 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - loss: 9.9471e-04 - mae: 0.0212

319/367 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - loss: 0.0010 - mae: 0.0212

320/367 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - loss: 0.0010 - mae: 0.0212

321/367 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - loss: 0.0010 - mae: 0.0212

322/367 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - loss: 0.0010 - mae: 0.0212

323/367 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - loss: 0.0010 - mae: 0.0212

324/367 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - loss: 9.9995e-04 - mae: 0.0212

325/367 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - loss: 9.9861e-04 - mae: 0.0212

326/367 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - loss: 0.0010 - mae: 0.0212

327/367 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - loss: 0.0010 - mae: 0.0212

328/367 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - loss: 0.0010 - mae: 0.0213

329/367 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - loss: 0.0010 - mae: 0.0213

330/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

331/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

332/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

333/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

334/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

335/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

336/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

337/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

338/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

339/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

340/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

341/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0213

342/367 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - loss: 0.0010 - mae: 0.0214

343/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0213

344/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0213

345/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0214

346/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0214

347/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0214

348/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0214

349/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0214

350/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0214

351/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0214

352/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0214

353/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0214

354/367 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - loss: 0.0010 - mae: 0.0214

355/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0214

356/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0214

357/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0213

358/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0214

359/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0214

360/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0213

361/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0213

362/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0213

363/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0213

364/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0213

365/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0213

366/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0213

367/367 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.0010 - mae: 0.0213

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

367/367 ━━━━━━━━━━━━━━━━━━━━ 32s 86ms/step - loss: 0.0010 - mae: 0.0213 - val_loss: 0.0012 - val_mae: 0.0220 - learning_rate: 1.0000e-04

## 7. Curvas y evaluacion por comando

In [8]:
history_df = pd.DataFrame(history.history)
history_df.to_csv(FIGURES / "training_history.csv", index=False)
fig, axes = plt.subplots(1, 2, figsize=(10, 4))
axes[0].plot(history_df.loss, label="train")
axes[0].plot(history_df.val_loss, label="validation")
axes[0].set_title("MSE")
axes[0].set_xlabel("Epoca")
axes[0].legend()
axes[1].plot(history_df.mae, label="train")
axes[1].plot(history_df.val_mae, label="validation")
axes[1].axhline(0.05, color="red", linestyle="--", label="objetivo 0.05")
axes[1].set_title("MAE (rad)")
axes[1].set_xlabel("Epoca")
axes[1].legend()
plt.tight_layout()
plt.savefig(FIGURES / "training_curves.png", dpi=180)
plt.show()

predictions = model.predict(val_gen, verbose=0).reshape(-1)
actual = val_df.steering_angle.to_numpy(dtype=np.float32)
evaluation = []
for command, name in COMMANDS.items():
    mask = val_df.command.to_numpy() == command
    evaluation.append({
        "command": name,
        "samples": int(mask.sum()),
        "mae_rad": float(np.mean(np.abs(predictions[mask] - actual[mask]))),
    })
metrics = {
    "validation_mae_rad": float(np.mean(np.abs(predictions - actual))),
    "validation_mse": float(np.mean(np.square(predictions - actual))),
    "per_command": evaluation,
    "augmented_samples": int(len(augmented_df)),
    "train_samples": int(len(train_df)),
    "validation_samples": int(len(val_df)),
    "source_overlap": 0,
}
print(json.dumps(metrics, indent=2))
display(pd.DataFrame(evaluation))

/var/folders/50/pzhcqw5j5212_pw_y99p2ky80000gn/T/ipykernel_87500/3378205313.py:17: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

{
  "validation_mae_rad": 0.022006014361977577,
  "validation_mse": 0.001179361017420888,
  "per_command": [
    {
      "command": "STRAIGHT",
      "samples": 240,
      "mae_rad": 0.01518306229263544
    },
    {
      "command": "LEFT",
      "samples": 379,
      "mae_rad": 0.024078940972685814
    },
    {
      "command": "RIGHT",
      "samples": 607,
      "mae_rad": 0.02340942621231079
    }
  ],
  "augmented_samples": 12956,
  "train_samples": 11730,
  "validation_samples": 1226,
  "source_overlap": 0
}

    command  samples   mae_rad
0  STRAIGHT      240  0.015183
1      LEFT      379  0.024079
2     RIGHT      607  0.023409

## 8. Exportacion para Webots

In [9]:
final_model = MODEL_DIR / "cil_model.h5"
model.save(final_model)
metadata = {
    "image_height": IMG_H,
    "image_width": IMG_W,
    "channels": 3,
    "crop_top_ratio": 0.25,
    "normalization": "uint8/255.0",
    "commands": {str(key): value for key, value in COMMANDS.items()},
    "seed": SEED,
    "validation_mae_target_rad": 0.05,
}
(MODEL_DIR / "model_metadata.json").write_text(json.dumps(metadata, indent=2))
(MODEL_DIR / "training_metrics.json").write_text(json.dumps(metrics, indent=2))
print("Modelo:", final_model)
print("MAE validacion:", metrics["validation_mae_rad"])
assert metrics["validation_mae_rad"] <= 0.05, "El modelo no alcanza el objetivo MAE"

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Modelo: /content/proyecto-final-cil-equipo19/controllers/cil_autonomous_driver/cil_model.h5
MAE validacion: 0.022006014361977577

## Conclusion

El artefacto exportado conserva tres comandos verificables y un
preprocesamiento documentado. La validacion final se realiza en World 2
mediante las rutas recta, derecha e izquierda y el arbitro de seguridad.